<?php
use DDD\Service\Taxes;
use Library\Finance\CreditCard\CreditCard;
use Library\Utility\Helper;
use DDD\Service\Booking\BookingAddon;

$itemName = 'Point of Sale Charges';
$this->headTitle()->setSeparator(' - ');
$this->headTitle($itemName);

if ($this->itemId) {
    $breadcrumb = [
        ['Dashboards'],
        ['Concierge Dashboard', $this->url('backoffice/default', ['controller' => 'concierge-dashboard', 'action' => 'index'])],
        [$this->data['group_name'], $this->url('backoffice/default', [ 'controller' => 'concierge',  'action' => 'item', 'id' => $this->itemId])],
        [$itemName],
    ];
} else {
    $breadcrumb = [
        [$itemName]
    ];
}

$this->layout()->breadcrumb = $this->breadcrumb($breadcrumb);

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/pages/frontier.charge.js');
$this->headLink()->appendStylesheet( $this->basePath() . '/css/pages/frontier-charge.css');
$data = $this->data['booking_data'];

//Guest Balance
$guestBalance = $this->data['balance'];

if ($guestBalance > 0) {
    $ginosiBalanceTextClass = 'label-warning';
} elseif ($guestBalance == 0) {
    $ginosiBalanceTextClass = 'label-success';
} elseif ($guestBalance < 0) {
    $ginosiBalanceTextClass = 'label-danger';
}
?>
<script>
    var GLOBAL_ADDONS_LIST = $.parseJSON('<?= json_encode($this->data['addons_array'])?>');
    var GLOBAL_FRONTIER_CHARGE = '<?= $this->url('backoffice/default', array('controller' => 'frontier', 'action' => 'ajax-frontier-charge'))?>';
    var GLOBAL_GROUP_URL = '<?= $this->url('backoffice/default', array('controller' => 'concierge', 'action' => 'item', 'id' => $this->itemId))?>';
    var GLOBAL_NEW_CC = '<?= $this->url('backoffice/default', array('controller' => 'frontier', 'action' => 'ajax-cc-new-data'))?>';
    var GLOBAL_GET_PARKING_SPOTS  = '<?= $this->url('backoffice/default', ['controller' => 'booking', 'action' => 'ajax-get-parking-spots'])?>';
    var NIGHTS_COUNT = <?=$data['night_count']?>;
    var PARKING_FEE = <?= BookingAddon::ADDON_TYPE_PARKING ?>;
    var GROUP_ID = <?= $this->itemId ?>;
    var MSG_NO_CARD= '<?= addslashes(\Library\Constants\TextConstants::ERROR_NO_CARD)?>';
    var GUEST_BALANCE = '<?= $guestBalance ?>';
    var CHARGE_LIST = [
        <?=BookingAddon::ADDON_TYPE_DAMAGE?>,
        <?=BookingAddon::ADDON_TYPE_PARKING?>,
        <?=BookingAddon::ADDON_TYPE_CLEANING_FEE?>
    ];
    var LIMIT_AMOUNT = <?= $this->limitAmount ?>;
    var PARKING_SPOT_PRIORITY = $.parseJSON('<?=json_encode($this->spotsPriority)?>');
</script>
<div id="balance-amount" type="hidden" value=""></div>

<div class="row">
    <div class="col-sm-8">
        <h1><?php echo $itemName; ?></h1>
    </div>
    <div class="col-sm-4 text-right">
        <h3 class="margin-top-25">
            <span class="label <?= $ginosiBalanceTextClass ?>">Current Balance <?= number_format($guestBalance, 2, '.', '') . ' (' . $data['apartment_currency_code'].')' ?></span>
        </h3>
    </div>
</div>
<form id="frontier-charge-form" name="frontier-charge-form" class="form-horizontal">
    <div class="row">
        <div class="col-sm-6">
            <fieldset>
                <legend>Charges <span id="chargePending"></span></legend>
            </fieldset>
            <table class="table table-striped table-bordered table-condensed" id="chargesTable">
                <thead>
                <tr>
                    <th width="25%">Type</th>
                    <th>Date</th>
                    <th class="hidden-xs">Value</th>
                    <th width="17%">Price (<?= $data['apartment_currency_code'] ?>)</th>
                    <th width="10%">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->data['charges']) {
                    foreach ($this->data['charges'] as $charge) { ?>
                        <tr>
                            <td
                                <?php if ($charge->getAddons_type() == BookingAddon::ADDON_TYPE_ACC && $charge->getRateName()) {
                                    echo ' data-nightly-id="' . $charge->getReservationNightlyId() . '"';
                                    echo ' data-night-date="' . $charge->getReservationNightlyDate() . '"';
                            }
                            ?>


                                >
                                <?php
                                if ($charge->getAddon()) {
                                    echo $charge->getAddon();
                                } elseif ($charge->getType() == 'p') {
                                    echo 'Penalty';
                                } elseif ($charge->getType() == 'g') {
                                    echo 'Penalty Ginosi';
                                } else {
                                    echo 'Other';
                                }
                                ?>
                            </td>
                            <td class="text-center"><?=$charge->getReservationNightlyDate()?></td>
                            <td class="hidden-xs text-right">
                                <?php
                                if (($charge->getAddons_type() == BookingAddon::ADDON_TYPE_ACC || $charge->getAddons_type() == BookingAddon::ADDON_TYPE_PARKING) && $charge->getRateName()) {
                                    echo $charge->getRateName();
                                } elseif($charge->getAddons_value() > 0) {
                                    echo $charge->getAddons_value();

                                    if ($charge->getTaxType() == Taxes::TAXES_TYPE_PERCENT) {
                                        echo ' %';
                                    } elseif ($charge->getTaxType() == Taxes::TAXES_TYPE_PER_NIGHT) {
                                        echo ' p/n';
                                    } elseif ($charge->getTaxType() == Taxes::TAXES_TYPE_PER_PERSON) {
                                        echo ' p/p';
                                    }
                                }
                                ?>
                            <td class="text-right"><?= $charge->getAcc_amount() ?></td>
                            <td></td>
                        </tr>
                    <?php }
                } ?>
                </tbody>
                <tfoot>
                <tr>

                    <td colspan="2"><b>Total</b></td>
                    <td class="hidden-xs"></td>
                    <td class="text-right"><span id="total_price_span"></span></td>
                    <td><a href="javascript:void(0)" class="btn btn-sm btn-primary" id="addNewChargeRow">Add new</a></td>
                </tr>
                </tfoot>
            </table>
            <?php if (isset($this->data['taxes']['tot_included'])) { ?>
                <input type="hidden" value="<?=$this->data['taxes']['tot_included']?>" id="tot_included" name="tot_included" />
            <?php } ?>
            <?php if (isset($this->data['taxes']['vat_included'])) { ?>
                <input type="hidden" value="<?=$this->data['taxes']['vat_included']?>" id="vat_included" name="vat_included" />
            <?php } ?>
            <?php if (isset($this->data['taxes']['tot_included'])) { ?>
                <input type="hidden" value="<?=$this->data['taxes']['sales_tax_included']?>" id="sales_tax_included" name="sales_tax_included" />
            <?php } ?>
            <?php if (isset($this->data['taxes']['tot_included'])) { ?>
                <input type="hidden" value="<?=$this->data['taxes']['city_tax_included']?>" id="city_tax_included" name="city_tax_included" />
            <?php } ?>

            <?php if (isset($this->data['taxes']['tot_type']) && isset($this->data['taxes']['tot_apartment'])) { ?>
                <input type="hidden" value="<?=$this->data['taxes']['tot_apartment']?>" id="tot" name="tot" />
                <input type="hidden" value="<?=$this->data['taxes']['tot_type']?>" id="tot_type" name="tot_type" />
                <input type="hidden" value="<?=$this->data['taxes']['tot_exact_value']?>" id="tot_exact_value" name="tot_exact_value" />
            <?php } ?>

            <?php if (isset($this->data['taxes']['vat_type']) && isset($this->data['taxes']['vat_apartment'])) { ?>
                <input type="hidden" value="<?=$this->data['taxes']['vat_apartment']?>" id="vat" name="vat" />
                <input type="hidden" value="<?=$this->data['taxes']['vat_type']?>" id="vat_type" name="vat_type" />
                <input type="hidden" value="<?=$this->data['taxes']['vat_exact_value']?>" id="vat_exact_value" name="vat_exact_value" />
            <?php } ?>

            <?php if (isset($this->data['taxes']['sales_tax_type']) && isset($this->data['taxes']['sales_tax_apartment'])) { ?>
                <input type="hidden" value="<?=$this->data['taxes']['sales_tax_apartment']?>" id="sales_tax" name="sales_tax" />
                <input type="hidden" value="<?=$this->data['taxes']['sales_tax_type']?>" id="sales_tax_type" name="sales_tax_type" />
                <input type="hidden" value="<?=$this->data['taxes']['sales_tax_exact_value']?>" id="sales_tax_exact_value" name="sales_tax_exact_value" />
            <?php } ?>

            <?php if (isset($this->data['taxes']['city_tax_type']) && isset($this->data['taxes']['city_tax_apartment'])) { ?>
                <input type="hidden" value="<?=$this->data['taxes']['city_tax_apartment']?>" id="city_tax" name="city_tax" />
                <input type="hidden" value="<?=$this->data['taxes']['city_tax_type']?>" id="city_tax_type" name="city_tax_type" />
                <input type="hidden" value="<?=$this->data['taxes']['city_tax_exact_value']?>" id="city_tax_exact_value" name="city_tax_exact_value" />
            <?php } ?>

            <input type="hidden" value="<?=$data['current_customer_currency_rate']?>" id="current_customer_currency_rate" name="current_customer_currency_rate" />
            <input type="hidden" value="<?=$data['currency_rate']?>" id="customer_currency_rate" name="customer_currency_rate" />
            <input type="hidden" value="<?=$data['acc_currency_rate']?>" id="acc_currency_rate" name="acc_currency_rate" />
            <input type="hidden" id="accPrice" name="accPrice" value="<?=number_format($data['price'], 2, '.', '')?>" />
            <input type="hidden" id="customerPrice" name="customerPrice" value="<?=number_format($data['booker_price'], 2, '.', '');?>" />
            <input type="hidden" id="bookingId" name="bookingId" value="<?=$data['id']?>" />
            <input type="hidden" id="apartmentId" name="apartmentId" value="<?=$data['apartment_id_assigned']?>" />
        </div>
        <div class="col-sm-6">
            <fieldset>
                <legend>Details</legend>
            </fieldset>
            <?php
            $currentBalanceForPay = number_format(abs($this->data['balance'] < 0 ? $this->data['balance'] : 0 ), 2, '.', '');

            if ($guestBalance > 0) {
                $chargeAmount = number_format(0, 2, '.', '');
                $newBalance   = number_format($guestBalance, 2, '.', '');
            } elseif ($guestBalance < 0) {
                $chargeAmount = number_format(abs($guestBalance), 2, '.', '');
                $newBalance   = number_format(0, 2, '.', '');
            } else {
                $chargeAmount = number_format(0, 2, '.', '');
                $newBalance   = number_format(0, 2, '.', '');
            }
            ?>
            <input type="hidden" id="balance" name="balance" value="<?=$guestBalance?>" class="form-control" />
            <div class="form-group">
                <label class="col-sm-5 control-label">Amount (<?= $data['apartment_currency_code'] ?>)</label>
                <div class="col-sm-4 checkbox">
                    <input type="text" id="transaction_amount_apartment_currency" name="transaction_amount_apartment_currency" class="form-control amount" value="<?= $chargeAmount ?>"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 control-label">CC List</label>
                <div class="col-sm-7 checkbox">
                    <input type="hidden" id="cc_id" name="cc_id" value="0">

                    <?php if ($this->creditCards && count($this->creditCards) > 0) {?>
                        <ul class="list-unstyled credit-card-list">
                            <?php

                            foreach ($this->creditCards as $creditCard) {
                                $active = $default = $cardTransactionStatus = $cc_number = $cardType = '';
                                $isFirst = !isset($isFirst);

                                if ($isFirst) {
                                    $active = 'active';
                                }

                                if (isset($creditCard['is_default']) && $creditCard['is_default']) {
                                    $default = 'default';
                                }

                                $cardType = 'valid-card';

                                $cardTransactionStatus = $creditCard['transaction_status'];
                                $ccPartNumber = $creditCard['cc_number'];
                                $cc_number = substr($ccPartNumber, 0, 6) . 'XX XXXX XXXX';

                                $cardStatus = CreditCard::getCardStatusNameById($creditCard['card_status']);
                                ?>

                                <li class="clearfix <?= $active ?> <?= $default ?> <?= $cardType ?> transition" data-card-id="<?= $creditCard['cc_id'] ?>">
                                    <div class="ribbon-container">
                                        <div class="ribbon">
                                            <a href="#"><i class="glyphicon glyphicon-star"></i></a>
                                        </div>
                                    </div>
                                    <div class="card-type">
                                        <img src="<?= $this->basePath() ?>/img/cc-icons/<?= CreditCard::getNameById($creditCard['card_type'], $cc_number) ?>.png">
                                    </div>
                                    <div class="card-display-name ellipsis"><?= $cc_number ?></div>
                                    <div class="received">Card ID <?= $creditCard['cc_id'] ?></div>
                                    <div class="status <?= $cardStatus[0] ?>" data-toggle="tooltip" title="<?= $cardStatus[1] ?>" data-status="<?= $creditCard['card_status'] ?>"></div>

                                    <?php if ($cardTransactionStatus == CreditCard::TRANSACTION_VALID) { ?>
                                        <div class="transaction-status transaction-status-approved">
                                            <span class="glyphicon glyphicon-ok" data-toggle="tooltip" title="Valid"></span>
                                        </div>
                                    <?php } elseif ($cardTransactionStatus == CreditCard::TRANSACTION_INVALID) { ?>
                                        <div class="transaction-status transaction-status-declined">
                                            <span class="glyphicon glyphicon-remove" data-toggle="tooltip" title="Invalid"></span>
                                        </div>
                                    <?php } ?>
                                </li>
                            <?php } ?>
                        </ul>
                    <?php } else { ?>
                        <span class="label label-danger text-size-14">No credit card</span>
                    <?php } ?>
                    <a href="#addNewCreditCardModal" data-toggle="modal" class="btn btn-primary col-xs-12 margin-top-20"><span class=" glyphicon glyphicon-plus"></span> Add new card</a>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 control-label" for="charge_comment">Comment</label>
                <div class="col-sm-7">
                    <textarea rows="5" name="charge_comment" id="charge_comment" class="form-control"></textarea>
                </div>
            </div>
            <fieldset>
                <legend>Guest Details</legend>
            </fieldset>
            <div class="form-group">
                <label class="col-sm-5 col-xs-4 control-label">Guest</label>
                <div class="col-sm-7 col-xs-8 checkbox"><?=$data['guest_first_name'] . ' ' . $data['guest_last_name']?></div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 col-xs-4 control-label">Reservation</label>
                <div class="col-sm-7 col-xs-8 checkbox"><?=$data['res_number']?></div>
            </div>
            <div class="form-group">
                <label class="col-sm-5 col-xs-4 control-label">Duration</label>
                <div class="col-sm-7 col-xs-8 checkbox"><?=$data['night_count']?> night stay</div>
            </div>
        </div>
    </div>
    <input type="hidden" name="chargeClick" id="chargeClick" value="" />
    <div class="page-actions container">
        <div class="row text-right">
            <a href="javascript:void(0)" class="btn btn-primary col-sm-2 col-xs-12 pull-right margin-left-5" id="chargingProcess">Charge</a>
            <a href="javascript:void(0)" class="btn btn-default col-sm-2 col-xs-12 pull-right" id="cancelChargingProcess">Cancel</a>
        </div>
    </div>
</form>

<div id="addNewCreditCardModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary text-primary">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 id="myModalLabel" class="modal-title">Add New Credit Card</h4>
            </div>
            <div class="modal-body">
                <?php
                $form = $this->creditCardForm;
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formInput($form->get('credit_card_type'));
                ?>
                <div class="row">
                    <div class="col-sm-12 col-md-6 grid-sep">
                        <label for="number">Credit Card Number</label>
                        <?php
                        echo $this->formInput($form->get('number'));
                        ?>
                    </div>

                    <div class="col-sm-12 col-md-6 grid-sep">
                        <label for="cc" class="hidden-xs hidden-sm">&nbsp;</label>
                        <ul class="credit-cards">
                            <li class="visa">Visa</li>
                            <li class="mastercard">Master Card</li>
                            <li class="amex">AMEX</li>
                            <li class="discover">Discover</li>
                            <li class="jcb">JCB</li>
                            <li class="diners-club">Diners Club</li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 grid-sep">
                        <label for="form-cc-holder-name">Holder Name</label>
                        <?=$this->formInput($form->get('holder'))?>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6 grid-sep">
                        <div class="row">
                            <div class="col-xs-12">
                                <p>Expiration Date</p>
                            </div>
                            <div class="col-xs-6">
                                <?=$this->formElement($form->get('month'))?>
                            </div>
                            <div class="col-xs-6">
                                <?=$this->formElement($form->get('year'))?>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="row">
                            <div class="col-xs-9 col-sm-8 grid-sep">
                                <p>Security Code</p>
                                <?=$this->formElement($form->get('cvc'))?>
                            </div>
                            <div class="col-xs-3 col-sm-4 grid-sep">
                                <p>&nbsp;</p>
                                <img alt="" src="<?=$this->basePath()?>/img/cc_cvc.png" class="cvc">
                            </div>
                        </div>
                    </div>
                </div>
                <?= $this->form()->closeTag() ?>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button class="btn btn-primary" id="createNewCreditCard">Create New Credit Card</button>
            </div>
        </div>
    </div>
</div>
