<?php
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->layout()->apartmentName . ' - Apartment Reviews');

	$this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/apartment.reviews.js');
    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath () . '/css/apartment/common.css');
?>
<script>
    var GLOBAL_DELETE = '<?=$this->url("apartment/review", ['controller' => 'review', 'action'=>'delete', 'apartment_id' => $this->apartmentId])?>';
    var GLOBAL_SAVE_REVIEW_CATEGORY = '<?=$this->url("apartment/review", ['controller'=>'review', 'action' => 'ajax-save-review-category', 'apartment_id' => $this->apartmentId])?>';
    var aaData = <?= $aaData ?>;
</script>
<div class="row">
    <div class="col-sm-12">
        <hr>
        <?= $this->apartmentNavigation($this->apartmentId, $this->apartmentStatus, 'apartment/review')?>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <fieldset>
            <legend>Last 2 Years</legend>
                <div class="row">
                    <div class="offset1 col-sm-12">
                        <p>
                            <span class="label label-warning">Review Score <?php if(isset($this->options['scoreLastTwoYears'])) echo $this->options['scoreLastTwoYears'];?></span>
                        </p>
                    <?php
                        if(isset($this->options['reviewCategoryLastTwoYears'])) {
                            foreach ($this->options['reviewCategoryLastTwoYears'] as $row) {?>
                            <p><?=$row['count']. ' ' . $row['name'] . ' ' . (($row['type'] == 1 ) ? '<span class=" glyphicon glyphicon-thumbs-up"></span>' :
                                                                                                    '<span class=" glyphicon glyphicon-thumbs-down"></span>')?></p>
                    <?php }
                        }
                    ?>
                    </div>
               </div>
        </fieldset>
    </div>
    <div class="col-sm-6">
        <fieldset>
            <legend>Last 3 Months</legend>
            <div class="row">
                <div class="offset1 col-sm-12">
                    <p>
                        <span class="label label-warning">Review Score <?php if(isset($this->options['scoreLastThreeMonth'])) echo $this->options['scoreLastThreeMonth'];?></span>
                    </p>
                <?php
                    if(isset($this->options['reviewCategoryLastThreeMonth'])) {
                        foreach ($this->options['reviewCategoryLastThreeMonth'] as $row) {?>
                            <p><?=$row['count']. ' ' . $row['name'] . ' ' . (($row['type'] == 1 ) ? '<span class=" glyphicon glyphicon-thumbs-up"></span>' :
                                                                                                    '<span class=" glyphicon glyphicon-thumbs-down"></span>')?></p>
                <?php   }
                    }
                ?>
                </div>
               </div>
        </fieldset>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <table id="review" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> R# </th>
                <th> <span class="glyphicon glyphicon-star-empty"></span> </th>
                <th> Date </th>
                <th> Status </th>
                <th> Review </th>
                <th> Comment </th>
                <th> Codification </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<input type="hidden" name="review_id" id="review_id" value="0" />
<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 id="myModalLabel" class="modal-title">Delete Review<span id="delete_group"></span></h4>
            </div>
            <div class="modal-body">
                <p>Are you sure to delete the review ?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <a class="btn btn-danger" href="" id="delete_review">Delete Review</a>
            </div>
        </div>
    </div>
</div>
