<?php

use Mailer\Constants\Inline;

?><tr>
    <td style="padding: 20px">
        <!-- header: start -->
        <table border="0" cellpadding="0" cellspacing="0" align="center" data-editable="text" style="<?php echo Inline::WIDTH. Inline::BORDER_RADIUS . Inline::BACKGROUND_WHITE; ?>margin-bottom:20px;">
            <tbody>
            <tr>
                <td style="padding:20px; text-align:left; font-size:100%">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td>
                                <a href="https://www.ginosi.com<?= isset($this->analyticsQuery) ? '?' . $this->analyticsQuery : '' ?>" style="text-decoration: none;">
                                    <img src="https://www.ginosi.com/images/emails/logo-grey-new.png" alt="Ginosi Apartments" title="Ginosi Apartments" style="width:100px;"/>
                                </a>
                            </td>
                            <td align="right" valign="middle" style="font-size: 14px;">
                                <?php if ($this->phone1) { ?>
                                    <a href="tel:<?= $this->phone1 ?>" style="text-decoration: none; color: #757575;">
                                        <?= $this->phone1 ?>
                                    </a>
                                <?php } ?>
                                <?php if($this->phone2 && $this->phone2 != $this->phone1) { ?>
                                    <br>
                                    <a href="tel:<?= $this->phone2 ?>" style="text-decoration: none; color: #757575;">
                                        <?= $this->phone2 ?>
                                    </a>
                                <?php } ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="<?php echo Inline::getBG('#95a1af', 'https://www.ginosi.com/images/emails/cancellation_background.jpg'); ?>">
                    <table border="0" cellpadding="0" cellspacing="0" align="left">
                        <tbody>
                            <tr>
                                <td style="<?php echo Inline::getCover(); ?>">
                                    <p style="<?php echo Inline::SUBHEADING_P . Inline::COLOR_WHITE; ?>">
                                        <?= $this->title ?>
                                    </p>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding: 20px;" align="center">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td>
                                <p style="font-size: 22px; margin: 0 0 10px 0">
                                    <?= $this->textline(1309, true) ?>
                                </p>
                                <p style="font-size: 14px; margin: 0">
                                    <?= $this->cancelInfo ?>
                                </p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            </tbody>
        </table>
        <!-- header: end -->

        <table border="0" cellpadding="0" cellspacing="0" align="center" data-editable="text" style="<?php echo Inline::MAX_WIDTH . Inline::WIDTH_100 . Inline::BORDER_RADIUS . Inline::BACKGROUND_WHITE; ?>margin:20px auto 0 auto ;color: #757575;">
            <tbody>
                <tr>
                    <td style="padding: 20px; font-size: 14px;" align="center">
                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <tr>
                                <td style="padding: 5px 0;font-weight:bold;" colspan="2">
                                    <?= $this->textline(1306, true) ?>
                                </td>
                                <td align="right" style="padding: 5px 0;">
                                    <?= $this->reservationId ?>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 7px 0 5px; width: 25px;">
                                    <img src="https://www.ginosi.com/images/emails/checkin.png" alt="">
                                </td>
                                <td style="padding: 5px 0;font-weight:bold; color: #757575">
                                    <?= $this->textline(706, true) ?>
                                </td>
                                <td align="right" style="padding: 5px 0;">
                                    <?= $this->checkInDate ?>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 7px 0 5px; width: 25px;">
                                    <img src="https://www.ginosi.com/images/emails/checkout.png" alt="">
                                </td>
                                <td style="padding: 5px 0;font-weight:bold; color: #757575">
                                    <?= $this->textline(707, true) ?>
                                </td>
                                <td align="right" style="padding: 5px 0;">
                                    <?= $this->checkOutDate ?>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 5px 0;font-weight:bold;" colspan="2">
                                    <?= $this->textline(708, true) ?> <?= ucfirst($this->textline(669, true)) ?>
                                </td>
                                <td align="right" style="padding: 5px 0;">
                                    <?= $this->totalNight ?>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 5px 0 10px 0;font-weight:bold;" colspan="2">
                                    <?= $this->textline(1669, true) ?>
                                </td>
                                <td align="right" style="padding: 5px 0;">
                                    <?= $this->totalPrice ?>
                                </td>
                            </tr>
                            <tr>
                                <td style="border-top: 1px solid #E0E0E0; padding: 10px 0 0 0;font-weight:bold;" colspan="2">
                                    <?= $this->textline(1670, true) ?>
                                </td>
                                <td align="right" style="border-top: 1px solid #E0E0E0; padding: 10px 0 0 0;">
                                    <?= $this->penalty ?>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </td>
</tr>
