<?php

use Mailer\Constants\Inline;

?><tr>
    <td style="padding: 50px 20px 20px" align="center">
        <table cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF" width="100%" style="<?php echo Inline::MAX_WIDTH . Inline::BACKGROUND_WHITE . Inline::BORDER_RADIUS; ?>">
            <tr>
                <td style="<?php echo Inline::PADDING_20 . Inline::ALIGN_LEFT; ?>">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td>
                                <a href="https://www.ginosi.com?<?= $this->analyticsQuery ?>" style="text-decoration: none;">
                                    <img src="https://www.ginosi.com/images/emails/logo-grey-new.png" alt="Ginosi Apartments" title="Ginosi Apartments" style="width:100px"/>
                                </a>
                            </td>
                            <td align="right" valign="top" style="font-size: 14px;">
                                <?php if ($this->phone1) { ?>
                                    <a href="tel:<?= $this->phone1 ?>" style="text-decoration: none; color: #757575;">
                                        <?= $this->phone1 ?>
                                    </a>
                                <?php } ?>
                                <?php if($this->phone2 && $this->phone2 != $this->phone1) { ?>
                                    <br>
                                    <a href="tel:<?= $this->phone2 ?>" style="text-decoration: none; color: #757575;">
                                        <?= $this->phone2 ?>
                                    </a>
                                <?php } ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="<?php echo Inline::getBG('#ea496b', 'https://www.ginosi.com/images/emails/red-bg.jpg') . Inline::getCover(); ?>">
                    <p style="<?php echo Inline::SUBHEADING_P; ?>">
                        <b>
                            <?= $this->dearGuestName ?>
                        </b>
                    </p>
                    <span style="<?php echo Inline::COLOR_WHITE; ?>"><?= $this->textline1575 ?></span>
                </td>
            </tr>
            <tr>
                <td style="padding: 20px; padding-top: 24px;padding-bottom: 8px;">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td style="<?php echo Inline::ALIGN_CENTER; ?>">
                                <a href="<?= $this->cccaPageLink ?>" style="<?php echo Inline::getPrimaryText('#ea496b'); ?>">
                                  <?= $this->viewButtonText ?>
                                </a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="<?php echo Inline::PADDING_0_20 . Inline::PADDING_BOTTOM_5; ?>">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td style="font-size:15px!important">
                                <?= $this->textline1667 ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>
</tr>
