                <tr>
                    <td align="center" valign="top" style="margin:0;padding:0;">
                        <table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" data-editable="text">
                            <tbody><tr>

<!-- header: start -->
<td valign="top" align="center" style="padding: 10px 29px 10px 20px; margin: 0px; font-family: Verdana, sans-serif; color: rgb(0, 58, 77); background-color: rgb(221, 238, 255); border-top-left-radius: 7px; border-top-right-radius: 7px; border-bottom-right-radius: 7px; border-bottom-left-radius: 7px;">
    <div style="text-align: left;">
        <font size="22" style="font-size: 22px;">
            <?= $this->title ?>
        </font>
</div>
</td>
<!-- header: end -->

                            </tr>
                        </tbody></table>
                    </td>
                </tr>


                <tr>
                    <td align="left" valign="top" style="padding:0;margin:0;">

                    </td>
                </tr>
                <tr>
<!-- body: start -->
<td align="left" valign="top" style="margin:0;padding:0;">
<table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" data-editable="text">
    <tbody><tr>
        <td valign="top" align="justify" style="padding: 20px 20px 23px; margin: 0px; font-family: Helvetica, sans-serif; color: rgb(28, 83, 121);">
            <div style="">
                <font size="20" style="font-size: 20px; color: rgb(28, 83, 121); font-family: Verdana, sans-serif;">

<!-- MODIFIED: START -->
                    <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" data-editable="preheader" style="margin-right: auto; margin-left: auto;"><tbody><tr><td align="center" style="padding: 8px; font-family: Helvetica, Arial, sans-serif; color: rgb(38, 38, 38); background-color: rgb(225, 230, 225); border: 2px solid rgb(189, 222, 189); border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px;">
                        <div style="text-align: justify;"><span style="background-color: transparent; color: rgb(38, 118, 38);"><font size="14" style="font-size: 14px;">

                        <?= $this->modified; ?>

                        </font></span></div>
                    </td></tr></tbody></table>
                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>
<!-- MODIFIED: END -->

<?php if ($this->cubilis) { ?>
<!-- CUBILIS: START -->
                    <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" data-editable="preheader" style="margin-right: auto; margin-left: auto;"><tbody><tr><td align="center" style="padding: 8px; font-family: Helvetica, Arial, sans-serif; color: rgb(38, 38, 38); background-color: rgb(225, 230, 225); border: 2px solid rgb(189, 222, 189); border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px;">
                        <div style="text-align: justify;"><span style="background-color: transparent; color: rgb(38, 118, 38);"><font size="14" style="font-size: 14px;">

                        <?= $this->cubilis; ?>

                        </font></span></div>
                    </td></tr></tbody></table>
                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>
<!-- CUBILIS: END -->
<?php } ?>

<?php if ($this->overbooking) { ?>
<!-- OVERBOOKING: START -->
                    <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" data-editable="preheader" style="margin-right: auto; margin-left: auto;"><tbody><tr><td align="center" style="padding: 8px; font-family: Helvetica, Arial, sans-serif; color: rgb(38, 38, 38); background-color: rgb(255, 245, 245); border: 2px solid rgb(236, 190, 190); border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px;">
                        <div style="text-align: justify;"><span style="background-color: transparent; color: rgb(196, 20, 20);"><font size="14" style="font-size: 14px;">

                        <?= $this->overbooking; ?>

                        </font></span></div>
                    </td></tr></tbody></table>
                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>
<!-- OVERBOOKING: END -->
<?php } ?>

                    <?= $this->creditCard ?>

                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>

                    <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" data-editable="preheader" style="margin-right: auto; margin-left: auto;"><tbody><tr><td align="center" style="padding: 8px; font-family: Helvetica, Arial, sans-serif; color: rgb(38, 38, 38); background-color: rgb(221, 238, 255); border: 2px solid rgb(0, 120, 164); border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px;"><div style="text-align: left;"><span style="background-color: transparent; color: rgb(28, 83, 121);"><font size="14" style="font-size: 14px;">

                        <?= $this->roomParams ?>

                        <br>
                        <div style="text-align: left;"><span style="background-color: transparent; color: rgb(28,83,121);"><font style="font-size: 12px;" size="12">
                        <ul style="margin:0 5px 0 25px;padding:0">
                            <li style="list-style-type:none; display:block; line-height:16px;">
                                <?= $this->cancelTitle ?>
                            </li>
                            <li style="list-style-type:none;display:block;line-height:16px">
                                <?= $this->cancelInfo ?></li>
                        </ul>
                        </font></span></div>

                    </font></span></div></td></tr></tbody></table>

                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>

<!-- button: start -->
<table border="0" cellpadding="0" cellspacing="0" align="center" data-editable="button" style="margin-right: auto; margin-left: auto;">
    <tbody><tr>
        <td valign="top" align="left" style="border: 0px solid rgb(255, 255, 255); padding: 12px 31px; margin: 0px; background-color: rgb(0, 171, 231); text-align: left; border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px;">
            <a href="<?= $this->ticketLink ?>" style="font-family: Verdana, sans-serif; color: rgb(255, 255, 255); font-size: 22px; font-weight: bold; text-decoration: none;">
                &#187; Open in Backoffice &#171;
            </a>
        </td>
    </tr>
</tbody></table>
<!-- button: end -->

                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>

                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>

                    <div style="text-align: left; padding-bottom: 6px;"><span style="background-color: transparent; color: rgb(0,120,164);"><font size="14" style="font-size: 20px;" size="20">
                        &nbsp;&nbsp;<?= $this->resDetails ?>
                    </font></span></div>

                    <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center" data-editable="text" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="left" style="padding: 10px; margin: 0px; font-family: Arial, Helvetica, sans-serif; color: rgb(38, 38, 38); border-top-left-radius: 8px; border-top-right-radius: 8px; border-bottom-right-radius: 8px; border-bottom-left-radius: 8px; border: 4px solid rgb(191, 223, 255);"><font size="14" style="font-size: 14px; color: rgb(0, 120, 164);">

                    <div style="text-align: left;"><span style="background-color: transparent; color: rgb(0,120,164);"><font style="font-size: 16px; font-weight: bold" size="16">
                        <?= $this->productName ?>
                    </font></span></div>
                        <p>
                        <?= $this->address ?>
                        </p>
                        <?= $this->guestName ?>
                        <br>
                        <?= $this->guestEmail ?>
                        <br>
                        <?= $this->guestPhone ?>
                        <br>
                        <?= $this->checkInDate ?>
                        <br>
                        <?= $this->checkOutDate ?>
                        <br>
                        <?= $this->checkInTime ?>
                        <?php if ($this->arrivalTime !== '') { ?>
                        <br>
                        <?= $this->arrivalTime ?>
                        <?php } ?>
                        <br>
                        <?= $this->totalNight ?>
                        <p>
                        <?= $this->remarks ?>
                        </p>
                    </font></td></tr></tbody></table>

                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>


                    <div style="text-align: right;"><span style="background-color: transparent; color: rgb(28,83,121);"><font style="font-size: 16px; font-weight: bold" size="16">
                    <?= $this->totalPrice ?>
                    </font></span></div>

                    <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 10px 0px; margin: 0px;"><div style="height: 1px; line-height: 1px; border-top-width: 3px; border-top-style: solid; border-top-color: rgb(221, 238, 255);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>

                </font>
            </div>
        </td>
    </tr>
</tbody></table>
</td>
<td align="left" valign="top" style="margin:0;padding:0;">

</td>

<!-- body: end -->

                </tr>
                <tr>
                                <td align="center" valign="top" style="margin-right: auto; margin-left: auto; padding: 0px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tbody><tr><td style="margin-right: auto; margin-left: auto;" align="center" valign="top">

                                </td></tr></tbody></table></td>
                            </tr><tr><td style="" align="left" valign="top"><table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" data-editable="text">
                            <tbody><tr>
                                <td valign="top" align="center" style="padding: 10px 29px 10px 20px; margin: 0px; font-family: Verdana, sans-serif; color: rgb(255, 255, 255); background-color: transparent; border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px;"><div style="text-align: left;"><span style="font-family: Verdana, sans-serif;"><font size="16" style="font-size: 16px;"><span style="color: rgb(58, 105, 121);"><?=$this->textLine1478?></span></font></span></div><div style="text-align: left;"><span style="font-family: Verdana, sans-serif;"><font size="16" style="font-size: 16px;"><span style="color: rgb(58, 105, 121);"><?=$this->textLine1479?></span></font></span></div>
                                </td>
                            </tr>
                        </tbody></table></td></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="">
                            <tbody><tr>
                                <td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);">
                                        <img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;">
                                    </div></td>
                            </tr>
                        </tbody></table></td></tr>