                <tr>
                    <td align="center" valign="top" style="margin:0;padding:0;">
                        <table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" data-editable="text">
                            <tbody><tr>
<!-- header: start -->
<td valign="top" align="center" style="padding: 10px 29px 10px 20px; margin: 0px; font-family: Verdana, sans-serif; color: rgb(0, 58, 77); background-color: rgb(221, 238, 255); border-top-left-radius: 7px; border-top-right-radius: 7px; border-bottom-right-radius: 7px; border-bottom-left-radius: 7px;">
    <div style="text-align: left;">
        <font size="24" style="font-size: 24px;">
            <?= $this->title ?>
        </font>
</div>
</td>
<!-- header: end -->
                            </tr>
                        </tbody></table>
                    </td>
                </tr>

<!-- body: start -->

                <tr>
                    <td align="left" valign="top" style="padding:0;margin:0;">

                    </td>
                </tr>
                <tr>
                    <td align="left" valign="top" style="margin:0;padding:0;">
                        <table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" data-editable="text">
                            <tbody>
                                <tr>
                                    <td valign="top" align="left" style="padding:20px 20px 0px 23px;margin:0px;font-family:Verdana,sans-serif">
                                        <div>
                                            <font size="20" style="font-size:20px;color:rgb(28,83,121);font-family:Verdana,sans-serif">
                                                <?=$this->details?>
                                            </font>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" valign="top" style="margin-right: auto; margin-left: auto; padding: 0px;"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tbody><tr><td style="margin-right: auto; margin-left: auto;" align="center" valign="top">

                        <!-- button: start -->
                        <table border="0" cellpadding="0" cellspacing="0" align="center" data-editable="button" style="margin-right: auto; margin-left: auto;">
                            <tbody><tr>
                                <td valign="top" align="left" style="border: 0px solid rgb(255, 255, 255); padding: 12px 31px; margin: 0px; background-color: rgb(0, 171, 231); text-align: left; border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px;">
                                    <a href="<?= $this->link ?>" style="font-family: Verdana, sans-serif; color: rgb(255, 255, 255); font-size: 22px; font-weight: bold; text-decoration: none;">
                                        &#187; Open in Backoffice &#171;
                                    </a>
                                </td>
                            </tr>
                        </tbody></table>
                        <!-- button: end -->
                    </td></tr></tbody></table></td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr><td>
                        <table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="margin-right: auto; margin-left: auto;"><tbody><tr><td valign="top" align="center" style="padding: 10px 0px; margin: 0px; background-color: transparent; border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px;"><div style="height: 1px; line-height: 1px; border-top-width: 3px; border-top-style: solid; border-top-color: rgb(221, 238, 255);"><img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;"></div></td></tr></tbody></table>
                    </td></tr><tr><td style="" align="left" valign="top"><table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" data-editable="text">
                <tbody><tr>
                    <td valign="top" align="center" style="padding: 10px 29px 10px 20px; margin: 0px; font-family: Verdana, sans-serif; color: rgb(255, 255, 255); background-color: transparent; border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px;"><div style="text-align: left;"><span style="font-family: Verdana, sans-serif;"><font size="16" style="font-size: 16px;"><span style="color: rgb(58, 105, 121);"><?=$this->textLine1478?></span></font></span></div><div style="text-align: left;"><span style="font-family: Verdana, sans-serif;"><font size="16" style="font-size: 16px;"><span style="color: rgb(58, 105, 121);"><?=$this->textLine1479?></span></font></span></div>
                        </td>
                </tr>
            </tbody></table></td></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" align="center" width="100%" data-editable="line" style="">
                <tbody><tr>
                    <td valign="top" align="center" style="padding: 15px 0px; margin: 0px; background-color: rgb(255, 255, 255);"><div style="height: 1px; line-height: 1px; border-top-width: 1px; border-top-style: none; border-top-color: rgb(104, 121, 94);">
                            <img src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" alt="" width="1" height="1" style="display:block;">
                        </div></td>
                </tr>
            </tbody></table></td></tr>