<?php

use Mailer\Constants\Inline;
use DDD\Domain\Booking\ReservationConfirmationEmail;

/** @var ReservationConfirmationEmail $reservation */
$reservation = $this->reservation;

?><!-- Header -->
<tr>
    <td style="padding: 50px 20px 10px" align="center">
        <table cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF" width="100%" style="<?php echo Inline::MAX_WIDTH . Inline::BORDER_RADIUS; ?>">
            <tr>
                <td style="padding: 20px">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td>
                                <a href="https://www.ginosi.com?<?= $this->analyticsQuery ?>" style="text-decoration: none;">
                                    <img src="https://www.ginosi.com/images/emails/logo-grey-new.png" alt="Ginosi Apartments" title="Ginosi Apartments" style="width:100px"/>
                                </a>
                            </td>
                            <td align="right" valign="top" style="font-size: 14px;">
                                <?php if ($reservation->getCountryPhoneApartment()) { ?>
                                    <a href="tel:<?= $reservation->getCountryPhoneApartment() ?>" style="text-decoration: none; color: #757575;"><?= $reservation->getCountryPhoneApartment() ?></a>
                                <?php } ?>
                                <?php if($reservation->getCountryPhoneGuest() && $reservation->getCountryPhoneGuest() != $reservation->getCountryPhoneApartment()) { ?>
                                    <br><a href="tel:<?= $reservation->getCountryPhoneGuest() ?>" style="text-decoration: none; color: #757575;"><?= $reservation->getCountryPhoneGuest() ?></a>
                                <?php } ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="<?php echo Inline::getBG('#3DAAE2', 'https://www.ginosi.com/images/emails/blue-bg.jpg') . Inline::getCover(); ?>">
                    <p style="<?php echo Inline::SUBHEADING_P; ?>">
                        <b>
                            <?= $this->textline(842) ?>
                            <?= $reservation->getGuestFullName() ?>,
                        </b>
                    </p>
                    <?= $this->textline(754) ?>
                </td>
            </tr>
            <tr>
                <td style="<?php echo Inline::PADDING_20; ?>">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td style="padding: 5px 0 0; max-width: 40px" valign="top">
                                <img src="https://www.ginosi.com/images/emails/bulb.png" alt="" />
                            </td>
                            <td>
                                <?= $this->textline(1106) ?>
                            </td>
                        </tr>
                        <tr>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>
</tr>
<tr>
    <td style="padding: 10px 20px" align="center">
        <table cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF" width="100%" style="<?php echo Inline::BORDER_RADIUS . Inline::MAX_WIDTH; ?>border-bottom: 1px;">
            <tr>
                <td style="padding: 20px;">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-bottom: 1px solid #EEEEEE">
                        <tr>
                            <td colspan="3" style="font-size: 20px; padding-bottom: 10px;">
                                <?= $reservation->getApartmentName() ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td style="padding: 7px 0 5px; max-width: 25px;">
                                <img src="https://www.ginosi.com/images/emails/location.png" alt="">
                            </td>
                            <td style="padding: 5px 0; font-weight:bold; color: #757575">
                                <?= $this->textline(785) ?>
                            </td>
                            <td align="right" style="padding: 5px 0;">
                                <?= $reservation->getApartmentAssignedAddress()
                                . ' ' . $this->cityName($reservation->getApartmentCityId())
                                . ' ' . $this->countryName($reservation->getApartmentCountryId()); ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td style="padding: 7px 0 5px; max-width: 25px;">
                                <img src="https://www.ginosi.com/images/emails/checkin.png" alt="">
                            </td>
                            <td style="padding: 5px 0;font-weight:bold; color: #757575">
                                <?= $this->textline(706); ?>
                            </td>
                            <td align="right" style="padding: 5px 0;">
                                <?= $reservation->getCheckInDatetime() ?>
                            </td>
                        </tr>
                        <tr style="border-bottom: 1px solid #BDBDBD; font-size: 14px;" valign="top">
                            <td style="padding: 7px 0 20px; max-width: 25px;">
                                <img src="https://www.ginosi.com/images/emails/checkout.png" alt="">
                            </td>
                            <td style="padding: 5px 0 20px; font-weight:bold; color: #757575">
                                <?= $this->textline(707) ?>
                            </td>
                            <td align="right" style="padding: 5px 0 20px;">
                                <?= $reservation->getCheckOutDatetime() ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding: 0 20px 20px;">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-bottom: 1px solid #EEEEEE">
                        <tr>
                            <td colspan="3" style="font-size: 20px; padding-bottom: 10px;">
                                <?= $this->textline(1265) ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td colspan="2" style="font-weight:bold; color: #757575">
                                <?= $this->textline(1307) ?>
                            </td>
                            <td align="right" style="padding: 5px 0;">
                                <?= $reservation->getGuestFullName() ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td colspan="2" style="font-weight:bold; color: #757575">
                                <?= $this->textline(635) ?>
                            </td>
                            <td align="right" style="padding: 5px 0;">
                                <?= $this->to ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td colspan="2" style="font-weight:bold; color: #757575">
                                <?= $this->textline(1240) ?>
                            </td>
                            <td align="right" style="padding: 5px 0">
                                <?= $reservation->getGuestPhone() ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td colspan="2" style="padding: 5px 0 20px; font-weight:bold; color: #757575">
                                <?= $this->textline(1268) ?>
                            </td>
                            <td align="right" style="padding: 5px 0 20px;">
                                <?= $reservation->getGuestAddress() ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding: 0 20px 20px;">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-bottom: 1px solid #EEEEEE">
                        <tr>
                            <td colspan="3" style="font-size: 20px; padding-bottom: 10px;">
                                <?= $this->textline(1230) ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td colspan="2" style="font-weight:bold; color: #757575">
                                <?= $this->textline(1306) ?>
                            </td>
                            <td align="right" style="padding: 5px 0;">
                                <?= $reservation->getResNumber() ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td colspan="2" style="font-weight:bold; color: #757575">
                                <?= $this->textline(708) . ' ' . $this->textline(($this->totalNights === '1' ? 730 : 669)) ?>
                            </td>
                            <td align="right" style="padding: 5px 0;">
                                <?= $this->totalNights ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td colspan="2" style="font-weight:bold; color: #757575">
                                <?= $this->textline(1233) ?>
                            </td>
                            <td align="right" style="padding: 5px 0">
                                <?= $reservation->getOccupancy() ?>
                            </td>
                        </tr>
                        <tr style="font-size: 14px;" valign="top">
                            <td colspan="2" style="padding: 5px 0 20px; font-weight:bold; color: #757575">
                                <?= $this->textline(1289) ?>
                            </td>
                            <td align="right" style="padding: 5px 0 20px;">
                                <?= $reservation->getRateName() ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding: 0 20px 20px;">
                    <?= $this->partial('partial/payments', ['chargesList' => $this->chargesList])?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<tr>
    <td style="padding: 10px 20px 20px 20px" align="center">
        <table cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF" width="100%" style="<?php echo Inline::BORDER_RADIUS . Inline::MAX_WIDTH; ?>">
            <tr>
                <td style="padding: 20px">
                    <p style="font-size: 22px; margin: 0;"><?= $this->textline(1309) ?></p>
                    <p style="font-size: 14px; margin: 5px 0 0;"><?= $this->cancelInfo ?></p>
                    <p style="font-size: 22px; margin: 10px 0 0;"><?= $this->textline(1654) ?></p>
                    <p style="font-size: 14px; margin: 5px 0 0;"> <?= $this->textline(1653) ?></p>
                    <p style="font-size: 22px; margin: 10px 0 0;"><?= $this->textline(1310) ?></p>
                    <p style="font-size: 14px; margin: 5px 0 0;"><?= $this->textline(1171) ?></p>
                </td>
            </tr>
        </table>
    </td>
</tr>
