<?php
	$this->layout()->viewTitle = 'Suppliers Management';
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->layout()->viewTitle);
	$this->layout()->breadcrumb = $this->breadcrumb([
		['Finance'],
		[$this->layout()->viewTitle]
	]);

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/suppliers.js');

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

?>

<div id="status-switch">
    <div class="btn-group fn-buttons pull-right">
        <a href="#all" class="btn btn-sm btn-default" data-status="all">All</a>
        <a href="#active" class="btn btn-sm btn-default active" data-status="active">Active</a>
        <a href="#inactive" class="btn btn-sm btn-default" data-status="inactive">Inactive</a>
    </div>
    <input type="hidden" name="show_status" id="show-status" value="1" />
</div>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable_suppliers_info" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> ST </th>
                <th> Name </th>
                <th> Description </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div class="container page-actions">
    <div class="row text-right">
        <a href="/finance/suppliers/add" class="btn btn-primary pull-right col-sm-2 col-xs-12">Add Supplier</a>
    </div>
</div>

<form id="loginForm" action="//<?php echo $this->partnersUrl ?>/login/authenticate" method="post" target="_blank" style="display: none;">
    <input type="text" name="gid" id="login-id" value="empty">
    <input type="password" name="password" id="login-password" value="empty">
    <input type="submit">
</form>
