<?php

use \Library\Constants\Objects;

$this->headTitle()->setSeparator(' - ');
$apartmentTitle = $this->layout()->apartmentName . ' - Apartment General';
if (!$this->apartmentId) {
    $this->layout()->breadcrumb = $this->breadcrumb([
        ['Apartments'],
        ['Add New']
    ]);
    $apartmentTitle = 'Add Apartment';
}

$this->headTitle($apartmentTitle);
$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/plugins/jquery.datetimepicker.css')
    ->appendStylesheet($this->basePath () . '/css/apartment/common.css');

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.form.min.js')
    ->appendFile($this->basePath() . '/js/pages/apartment.general.js')
    ->appendFile($this->basePath() . '/js/plugins/jquery.datetimepicker.full.min.js')
    ->appendFile($this->basePath() . '/js/validation/apartment.general.js');

$environment = getenv('APPLICATION_ENV') ?: 'production';

echo "<script src='{$this->basePath()}/js/vendor/tinymce/tinymce.min.js' type='text/javascript'></script>";

?>

<script>
    var CHECK_DISABLE_POSSIBILITY = '<?= $this->url("apartment/general/check-disable-possibility", array('apartment_id' => $this->apartmentId)) ?>';
    var SAVE_DATA = '<?= $this->url("apartment/general/save", array('apartment_id' => $this->apartmentId)) ?>';
    var STATUS_DISABLED = <?= Objects::PRODUCT_STATUS_DISABLED; ?>;
    $(function() {
		tinymce.init({
			selector: ".tinymce",
            skin: "clean",
			plugins: [
                "code", "link"
            ],
            menu : {},
            height: 468,
            browser_spellcheck : true,
            extended_valid_elements : "i[*]",
            verify_html : false,
            toolbar: "undo redo | styleselect | bold italic underline |  aligncenter alignjustify alignleft alignright | bullist numlist outdent indent | link | print | fontsizeselect | code | removeformat"
		});
    });
    var getBuildingSectionURL = '<?= $this->url("apartment/location/get-building-section", ['apartment_id' => $this->apartmentId]) ?>';
</script>
<?php if($this->apartmentId > 0) { ?>
<div class="row">
    <div class="col-sm-12">
        <hr>
        <?= $this->apartmentNavigation($this->apartmentId, $this->apartmentStatus, 'apartment/general')?>
    </div>
</div>
<?php
    } else {
    	$this->layout()->viewTitle = 'Add Apartment';
    }
?>
<?= $this->formOutput ?>

<div class="modal fade" id="disable-warning-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-warning text-warning">
                <h4 class="modal-title">Warning!</h4>
            </div>
            <div class="modal-body">
                Disabling this apartment will
                <ul>
                    <li>
                        Delete all the rate plans related to this apartment
                    </li>
                    <li>
                        Disable all connections (Cublis)
                    </li>
                    <li>
                        Block access to all inventory tabs (Calendar, Rates, Inventory)
                    </li>
                    <li>
                        Remove it from all groups
                    </li>
                </ul>

                <p>
                    This process is <span class="text-danger">irreversible</span>. Are you sure you want to proceed?
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-warning" id="confirm-disable">Proceed</button>
            </div>
        </div>
    </div>
</div>
