
    <h2 class="margin-top-0"><?=$this->textline(1265)?></h2>
    <p><strong><?=$this->textline(1307)?></strong><span class="pull-right"><?= $this->data['fullName'] ?></span></p>
    <p><strong><?=$this->textline(635)?></strong><span class="pull-right"><?= $this->data['email'] ?></span></p>
    <p><strong><?=$this->textline(1240)?></strong><span class="pull-right"><?= $this->data['phone'] ?></span></p>
    <p><strong><?=$this->textline(1268)?></strong><span class="pull-right"><?= $this->data['address'] ?></span></p>
