
    <h2 class="margin-top-0"><?=$this->textline(1230)?></h2>
    <p><strong><?=$this->textline(1306)?></strong><span class="pull-right"><?= $this->data['reservationNumber'] ?></span></p>
    <p><strong><?=$this->textline(1234)?></strong><span class="pull-right"><?= $this->data['totalNights'] ?></span></p>
    <p><strong><?=$this->textline(1233)?></strong><span class="pull-right"><?= $this->data['numberOfGuests'] ?></span></p>
    <p><strong><?=$this->textline(1289)?></strong><span class="pull-right"><?= $this->data['rateName'] ?></span></p>
