<?php

$this->headTitle()->setSeparator(' - ');
$this->layout()->viewTitle = 'New Universal Textline';
$this->headTitle($this->layout()->viewTitle);
$this->layout()->breadcrumb = $this->breadcrumb([
	['Content'],
	['Textlines', $this->url('backoffice/default', ['controller' => 'translation'])],
	['New Universal Textline']
]);

echo "<script src='{$this->basePath()}/js/vendor/tinymce/tinymce.min.js' type='text/javascript'></script>";
$this->InlineScript()->appendFile($this->basePath() . '/js/pages/translation.js');
?>

<script>
var GLOBAL_PAGE_TYPES = JSON.parse('<?= $this->pageTypes?>');

    $(function() {
		tinymce.init({
			selector: ".tinymce",
            skin: "clean",
			plugins: [
                "code", "autoresize", "link"
            ],
            menu : {},
            toolbar: "undo redo | styleselect | bold italic underline |  aligncenter alignjustify alignleft alignright | bullist numlist outdent indent | link | print | fontsizeselect | code | removeformat",
            autoresize_min_height:280,
            browser_spellcheck : true,
            extended_valid_elements : "i[*]",
            verify_html : false
		});
    });
</script>
<form method="post">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
				<input type="text" id="add-textline-page" name="add-textline-page" class="form-control" value="" placeholder="Page Type" multiple="" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <textarea name="content" class="tinymce" rows="4" id="content" aria-hidden="true"></textarea>
            </div>
        </div>
    </div>
	<div class="row">
	    <div class="col-sm-12">
	        <fieldset name="Description">
	            <legend>Description</legend>
	            <div class="form-group">
					<textarea name="description" id="description" class="form-control"></textarea>
	            </div>
			</fieldset>
		</div>
	</div>
<div class="page-actions container">
    <div class="row text-right">
        <button type="submit" class="btn btn-primary state col-sm-2 col-xs-12 pull-right" data-loading-text="Publishing..."  value="">Save Textline</button>
    </div>
</div>
    </form>
