<?php

$this->layout()->viewTitle = 'Textlines';
$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);
$this->layout()->breadcrumb = $this->breadcrumb([
	['Content'],
	[$this->layout()->viewTitle]
]);

$this->InlineScript()
	->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/plugins/fnReloadAjax.js')
	->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/pages/translation.js');

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/pages/translation.css');

?>
<script>
	var FIND_PRODUCT_BY_ADDRESS_AUTOCOMPLETE_URL = '<?= $this->url('apartments', ['controller' => 'apartment', 'action' => 'search-by-address-components'])?>';
	var GLOBAL_SEARCH_AUTOCOMPLETE_URL = '<?= $this->url('backoffice/default', ['controller' => 'Translation', 'action' => 'search-autocomplate'])?>';
    var AJAX_SOURCE_URL = '<?= $ajaxSourceUrl ?>';
</script>

<div class="row">
    <div class="col-sm-12">
        <?= $this->formOutput ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-12"><a href="javascript:void(0)" class="btn btn-medium btn-block btn-primary" id="btn_search_translation"><i class="icon-search icon-white"></i> Search</a></div>
</div>
<hr />
<div class="row hidden" id="translation_table_container">
    <div class="col-sm-12">
        <table id="datatable_translation" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> ID </th>
                <th class="text-center"> Type </th>
                <th class="text-center"> Content </th>
                <th class="text-center"> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        changeType(<?= $this->permission ?>);
    });
</script>

<?php if ($hasCreatorRole) { ?>
<div class="page-actions container">
    <div class="row text-right">
        <a type="submit" href="/translation/add" class="btn btn-primary state col-sm-2 col-xs-12 pull-right">Add Textline</a>
    </div>
</div>
<?php } ?>
