<?php
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Document Management');

$layoutViewModel = $this->viewModel()->getRoot();
$basePath = $layoutViewModel->basePathView;
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Apartment'],
    ['Document Management'],
]);
$this->layout()->viewTitle  = 'Document Management';

$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/pages/document-search.css');

$this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/plugins/fnReloadAjax.js')
        ->appendFile($this->basePath() . '/js/module/document/search.js');
?>

<script>
    var ENTITY_TYPE_APARTMENT       = 1;
    var ENTITY_TYPE_APARTMENT_GROUP = 2;
    var GET_ENTITY_LIST_URL = '<?= $this->url( 'documents/get-entity-list') ?>';
    var SEARCH_URL      = '<?= $this->url('documents/get-json')?>';
    var SUPPLIER_SEARCH = '<?= $this->url('documents/get-supplier-list')?>';
    var AUTHOR_SEARCH = '<?= $this->url('documents/get-user-list')?>';
    var DOWNLOAD_CSV = '<?= $this->url('documents/download-csv')?>';
</script>

<?php
    $form = $this->search_form;
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('id', 'search-document');
?>

<?php
    echo $this->form()->openTag($form);
?>
<div class="row form-group">
    <div class="col-sm-3">
        <?= $this->formSelect($form->get('entity_id')) ?>
        <?= $this->formhidden($form->get('entity_type')) ?>
    </div>
    <div class="col-sm-3">
        <?= $this->formElement($form->get('document_type')); ?>
    </div>
    <div class="col-sm-3">
        <?php
        echo $this->formElement($form->get('supplier'));
        echo $this->formElement($form->get('supplier_id'));
        ?>
    </div>
    <div class="col-sm-3">
        <?php
        echo $this->formElement($form->get('legal_entity_id'));
        ?>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-3">
        <div class="input-group">
            <label class="input-group-addon" for="createdDate">
                <span class="glyphicon glyphicon-calendar"></span>
            </label>
            <?php
            echo $this->formElement($form->get('createdDate'));
            ?>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="input-group">
            <label class="input-group-addon" for="validation-range">
                <span class="glyphicon glyphicon-calendar"></span>
            </label>
            <?php
            echo $this->formElement($form->get('validation-range'));
            ?>
        </div>
    </div>
    <div class="col-sm-3">
        <?php
        echo $this->formElement($form->get('has_attachment'));
        ?>
    </div>
    <div class="col-sm-3">
        <?php
            echo $this->formElement($form->get('has_url'));
        ?>
    </div>
</div>
<div class="row form-group">
    <div class="col-sm-3">
        <?php
            echo $this->formElement($form->get('author'));
            echo $this->formElement($form->get('author_id'));
        ?>
    </div>
    <div class="col-sm-3">
        <?php
            echo $this->formElement($form->get('account_holder'));
        ?>
    </div>

    <div class="col-sm-3">
        <?php
            echo $this->formElement($form->get('account_number'));
        ?>
    </div>
    <div class="col-sm-3">
        <?php
        echo $this->formElement($form->get('signatory_id'));
        ?>
    </div>
</div>

<?php
    echo $this->form()->closeTag($form);
?>

<div class="row">
    <div class="col-sm-2" id="download-btn">
        <div class="form-group">
            <a href="javascript:void(0)" class="btn btn-block btn-info" id="btn_download_filtered_csv"><i class="glyphicon glyphicon-download"></i> Download</a>
        </div>
    </div>
    <div class="col-sm-10">
        <a href="javascript:void(0)" class="btn btn-medium btn-block btn-primary" id="btn_filter_documents">
            <i class="glyphicon glyphicon-search"></i> Search
        </a>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable_documents" class="table table-striped table-bordered table-condensed table-hover hidden">
            <thead>
            <tr>
                <th>Property</th>
                <th>Security</th>
                <th>Type</th>
                <th>Supplier</th>
                <th>Description</th>
                <th>Created</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<div class="container page-actions">
    <div class="row text-right">
        <a href="<?= $this->url('documents/edit_document')?>" class="btn btn-primary pull-right col-sm-2 col-xs-12">Add Document</a>
    </div>
</div>