<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2Graylog2\Traits\Logger'                 => __DIR__ . '/src/ZF2Graylog2/Traits/Logger.php',
    'ZF2Graylog2\Logger\Writer\Graylog2'        => __DIR__ . '/src/ZF2Graylog2/Logger/Writer/Graylog2.php',
    'ZF2Graylog2\Logger\Formatter\Gelf'         => __DIR__ . '/src/ZF2Graylog2/Logger/Formatter/Gelf.php',
    'ZF2Graylog2\Module'                        => __DIR__ . '/Module.php',
);