<?php

    use DDD\Service\Tag\Tag;

	$this->layout()->viewTitle = 'Tag Management';
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->layout()->viewTitle);
	$this->layout()->breadcrumb = $this->breadcrumb([
		['Administration'],
		[$this->layout()->viewTitle]
	]);

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath () . '/css/pages/tag.css');

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/tag.js');
?>


<script>
    DATATABLE_AJAX_SOURCE    = '/tag/ajaxtagslist';
    GLOBAL_EDIT_TAG          = '/tag/ajaxedittag';
    GLOBAL_DELETE_TAG        = '/tag/ajaxdeletetag';
    GLOBAL_DEFAULT_LABEL     = '<?= Tag::DEFAULT_LABEL?>';
</script>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable_tags" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th>Name</th>
                <th>Tasks Count</th>
                <th> &nbsp; </th>
                <th> &nbsp; </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div class="container page-actions">

    <div class="row text-right">
        <a href="#" class="btn btn-primary col-sm-2 col-xs-12 pull-right" id="open-tag-modal">Add Tag</a>

    </div>
</div>


<div id="add-edit-tag-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary text-primary">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" >
                    Add Tag
                </h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-xs-6 col-sm-6">
                            <input type="text" class="form-control" value=""  id="new-tag-name" placeholder="Text">
                        </div>
                        <div class="col-xs-6 col-sm-6">
                            <select class="form-control" id="tag-style">
                                <?php foreach(Tag::getAllLabelClasses() as $labelClass) { ?>
                                <option value="<?= $labelClass['class']?>"><?= $labelClass['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-3 add-tag-container">
                            <span class="label" id="new-tag-preview"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" id="add-tag" href="#">Add tag</a>
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
            </div>
        </div>
    </div>
</div>


<div id="delete-tag-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" >
                    Remove Tag
                </h4>
            </div>
            <div class="modal-body">
                <p>Are you sure to remove?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" id="delete-tag-button" href="#">Yes</a>
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
            </div>
        </div>
    </div>
</div>