<?php

use Library\Constants\DomainConstants;
use FileManager\Constant\DirectoryStructure;

$this->headTitle($this->apartelName . ' | Apartel')->setSeparator(' - ');

$layoutViewModel = $this->viewModel()->getRoot();

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/apartel/common.css')
    ->appendStylesheet($this->basePath() . '/css/apartel/general.css');

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.form.min.js')
    ->appendFile($this->basePath() . '/js/apartel/general.js');

$apartelId = $layoutViewModel->apartelId;
?>
<?php
    echo $this->apartelHeader($apartelId);
    echo $this->form()->openTag($form);
    echo $this->formInput($form->get('id'));
?>
<div class="row">
    <div class="col-sm-6">
        <fieldset>
            <legend>Details</legend>

            <div class="row form-group">
                <label class="col-xs-3 control-label">
                    <?= $this->info('Website Status', "When status is Active, apartel will be visible in Ginosi website and it's URL will be added to the sitemap.") ?>
                </label>
                <div class="col-xs-6">
                    <?php echo $this->formSelect($form->get('status')); ?>
                </div>
            </div>
        </fieldset>

        <?php if (count($this->fiscalList)) {?>
        <fieldset class="form-horizontal">
            <legend>Fiscal names</legend>

            <table class="table table-striped table-bordered table-condensed">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Partner</th>
                    <th>Id</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->fiscalList as $fiscal) { ?>
                    <tr>
                        <td><?= $fiscal['name']?></td>
                        <td><?= $fiscal['partner_name']?></td>
                        <td><?= $fiscal['channel_partner_id']?></td>
                        <td width="1" style="white-space: nowrap">
                            <a href="javascript:void(0)" class="btn btn-primary margin-right-5 btn-xs edit-fiscal"
                               data-id="<?=$fiscal['id']?>"
                               data-name="<?=$fiscal['name']?>"
                               data-partner-id="<?=$fiscal['partner_id']?>"
                               data-channel-partner-id="<?=$fiscal['channel_partner_id']?>"
                                >Edit</a>
                                <a href="javascript:void(0)" class="btn btn-danger btn-xs delete-item-fiscal" data-id="<?=$fiscal['id']?>">Delete</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </fieldset>
        <?php } ?>

    </div>
    <div class="col-sm-6">
        <fieldset>
            <legend>Availability</legend>

            <div class="row form-group">
                <label class="col-xs-3">
                    <?= $this->info('Take Maximized', 'If this check-box is set a maximized availability will be sent to the Channel Manager.') ?>

                </label>
                <div class="col-xs-9">
                    <?= $this->formCheckbox($form->get('default_availability')); ?>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Review Score</legend>
            <div class="row form-group">
                <label class="col-xs-3">
                    Last 2 Years
                </label>
                <div class="col-xs-9">
                    <span class="label label-warning">Review Score <?php echo $this->scoreLastTwoYears; ?></span>
                </div>
            </div>

            <div class="row form-group">
                <label class="col-xs-3">
                    Last 3 Months
                </label>
                <div class="col-xs-9">
                    <span class="label label-warning">Review Score <?php echo $this->scoreLastThreeMont; ?></span>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>The Most Frequent Review Codes</legend>
            <div class="row form-group">
                <div class="col-xs-12">
                    <?php foreach ($this->reviews as $review) {?>
                        <p><?=$review['count']. ' ' . $review['name'] . ' ' .
                            (($review['type'] == 1 ) ?
                                '<span class=" glyphicon glyphicon-thumbs-up"></span>' :
                                '<span class=" glyphicon glyphicon-thumbs-down"></span>')?>
                        </p>
                    <?php } ?>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <?= $this->formInput($form->get('save_button')) ?>
        <a href="javascript:void(0)" class="btn btn-primary col-sm-2 col-xs-12 margin-right-10 pull-right add-new-fiscal">Add Fiscal</a>
    </div>
</div>

<?php echo  $this->form()->closeTag(); ?>
<script>
    var GLOBAL_GENERAL_SAVE_PATH = '<?= $this->url('apartel/general/save', ['apartel_id' =>  $this->apartelId])?>';
    var GLOBAL_FISCAL_SAVE       = '<?= $this->url('apartel/general/save-fiscal', ['apartel_id' =>  $this->apartelId])?>';
    var GLOBAL_GENERAL_PATH      = '<?= $this->url('apartel/general', ['apartel_id' =>  $this->apartelId])?>';
</script>
<div id="fiscal-dialog" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="fiscal-dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary text-primary">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Fiscal</h4>
            </div>
            <div class="modal-body">
                <form id="fiscal-form" name="fiscal-form">
                    <div class="row margin-bottom-10">
                        <div class="col-sm-3 text-right">
                            <label class="form-control-static">Name <?php echo $this->required(); ?></label>
                        </div>
                        <div class="col-sm-8">
                            <input type="text" name="fiscal_name" class="form-control" id="fiscal_name">
                        </div>
                    </div>
                    <div class="row margin-bottom-10">
                        <div class="col-sm-3 text-right">
                            <label class="form-control-static">Partner <?php echo $this->required(); ?></label>
                        </div>
                        <div class="col-sm-8">
                            <select name="partner" id="partner" class="form-control" placeholder="Partner">
                                <?php foreach($this->partnerList as $partner){ ?>
                                    <option value="<?= $partner['id'] ?>"><?= $partner['partner_name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="row margin-bottom-10">
                        <div class="col-sm-3 text-right">
                            <label class="form-control-static">Id <?php echo $this->required(); ?></label>
                        </div>
                        <div class="col-sm-8">
                            <input type="text" name="channel_partner_id" class="form-control" id="channel_partner_id">
                        </div>
                    </div>
                    <input type="hidden" name="fiscal_id" id="fiscal_id">
                    <input type="hidden" name="apartel_id" value="<?=$this->apartelId?>">
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <a href="javascript:void(0)" class="btn btn-primary save-fiscal">Add Fiscal</a>
            </div>
        </div>
    </div>
</div>

<div id="delete-dialog" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="delete-dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-primary">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-danger">Delete Fiscal</h4>
            </div>
            <div class="modal-body">
                Are you sure ?
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <a href="javascript:void(0)" class="btn btn-danger delete-fiscal">Delete Fiscal</a>
            </div>
        </div>
    </div>
</div>
