<?php

use Library\Utility\Helper;
use Library\Constants\DomainConstants;
use \DDD\Service\Booking as BookingService;
use DDD\Service\Booking\BookingTicket as ReservationTicketService;
use Library\Finance\CreditCard\CreditCard;
use DDD\Service\ApartmentGroup;

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->groupName . ' | Concierge Dashboard');
$this->layout()->breadcrumb = $this->breadcrumb([
	['Dashboards'],
	['Concierge Dashboard', $this->url('backoffice/default', ['controller' => 'concierge-dashboard', 'action' => 'index'])],
	[$this->groupName]
]);

$dayStyles = array('Yesterday' => 'default', 'Today' => 'success', 'Tomorrow' => 'warning');

?>
<script>
    var GLOBAL_CHANGE_STATUS  = '<?= $this->url('backoffice/default', ['controller' => 'frontier', 'action' => 'ajax-change-arrival-status'])?>';
    var GLOBAL_SEND_COMMENT   = '<?= $this->url('backoffice/default', ['controller' => 'frontier', 'action' => 'ajax-send-comment'])?>';
    var GLOBAL_SAVE_EMAIL     = '<?= $this->url('backoffice/default', ['controller' => 'frontier', 'action' => 'ajax-save-email'])?>';
    var GLOBAL_GENERATE_PAGE  = '<?= $this->url('backoffice/default', ['controller' => 'cc-provide', 'action' => 'ajax-generate-page'])?>';
    var GLOBAL_GENERATE_RESET = '<?= $this->url('backoffice/default', ['controller' => 'cc-provide', 'action' => 'ajax-generate-reset'])?>';
    var GLOBAL_BAD_EMAIL_LIST = $.parseJSON('<?= $this->getBadEmail?>');
    setInterval("refresh_page();", 600000);

    function refresh_page(){
        location.reload();
    }

    var collapsed = {},
        viewType = 'all';
</script>
<?php
    $this->InlineScript()->appendFile($this->basePath() . '/js/pages/concierge.js');

    $this->headLink()->appendStylesheet($this->basePath() . '/css/pages/concierge.css', 'all');
?>
<?php if (isset($this->errorPage)) { ?>
<div class="not-data">Aweee, it looks like no dashboards are assigned to you.</div>
<?php } else { ?>
<div class="visible-print-block"><img src="<?=$this->basePath()?>/img/logo.png"></div>
<div class="row">
    <div class="col-sm-12 conciergeGroupName">
        <h3><?=$this->groupName?></h3> <small class="text-muted visible-xs-inline"><?=$this->dateInTimezone?></small>
    </div>
</div>
<div class="row hidden-print">
    <div class="form-group col-sm-12 form-inline">
        <span class="text-muted hidden-xs font-size18"><?=$this->dateInTimezone?></span>
        <div class="btn-group fn-buttons pull-right" id="switch-view">
            <button type="button" class="btn btn-sm btn-default active" data-view="all">All</button>
            <button type="button" class="btn btn-sm btn-default" data-view="today">Today</button>
        </div>

        <label class="control-label pull-right" for="filter">
            Filter:
            <input type="text" class="form-control input-sm" id="filter" style="display: inline-block">
        </label>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <?php foreach ($dayStyles as $day => $style) { ?>
        <div class="panel panel-<?php echo $style ?>">
            <div class="panel-heading collapsed" data-toggle="collapse" href="#arrivals<?php echo $day; ?>">
                <div class="panel-title pull-left">
                    Arrivals <?php echo $day; ?>
                </div>
                <div class="glyphicon my-chevron row-arrow hidden-xs pull-right"></div>
                <div class="clearfix"></div>
            </div>
            <div id="arrivals<?php echo $day; ?>" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table table-hover arrivals-dashboard">
                        <thead>
                            <tr class="cons-<?php echo $day; ?>-bg">
                                <th> Guest <span class="visible-xs-inline">(Apartment)</span> </th>
                                <th class="hidden-xs">Reservation</th>
                                <th class="hidden-xs">Apartment</th>
                                <th class="hidden-xs">Security</th>
                                <th>PAX</th>
								<th class="hidden-xs text-center">PTC</th>
                                <th class="hidden-xs text-center">PK</th>
                                <th>ST</th>
                                <th style="width: 1px;">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php /** @var \DDD\Domain\ApartmentGroup\ConciergeView $row */ ?>
                            <?php foreach ($this->{'arrivals' . $day} as $row) {
                            if ($this->userIsExternal && $row->getGuestBalance() < 0) {
                                continue;
                            }
                                    $ccNumber = 'No Card';
                                    if ($row->getFirstDigits()) {

                                        $ccNumberFirst = $row->getFirstDigits();
                                        $ccNumber = substr($ccNumberFirst, 0, 4)
                                                         .' ' .substr($ccNumberFirst, 4, 2) . '<span class="concierge-card-xxx">XX</span>';
                                    }
                                ?>

                                <tr class="filterable <?php echo $style ?><?php if ($row->getHousekeepingComment()) { ?> concierge-row-active" data-toggle="not-toggled" data-type="active" data-row-id="<?php echo 'Arrivals-'.$day.'-'.$row->getReservationNumber() ?>"<?php } else { ?>"<?php }?>>
									<td>
                                        <?php
                                        $guest = $row->getGuestLastName() . ', ' . $row->getGuestFirstName();
                                        if ($this->hasFrontierCard) { ?>
                                            <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>"><?= $guest; ?></a>
                                        <?php } else {
                                            echo $guest;
                                        } ?>
										<?php if ($row->getHousekeepingComment()) { ?>
											<span class="glyphicon glyphicon-comment text-primary pull-right" title="Show Housekeeping Comments"></span>
										<?php } ?>

                                        <span class="visible-xs-block hidden-print">
                                            (
                                                <?= $row->getApartmentName() ?>
                                                <?php if ($row->getUnitNumber()) {
                                                    echo ', ' . $row->getUnitNumber();
                                                } ?>
                                            )<br>
										<?php if ($row->getParking()) { ?>
											<span class="label label-primary pull-right" data-toggle="tooltip" title="This reservation has a parking">P</span>
										<?php } ?>
                                        <?php if ($row->getFraudScore() >= ApartmentGroup::SHOW_AS_BLACKLISTED_IN_CONCIERGE_DASHBOARD_IF_MORE_THAN_SCORE) { ?>
                                            <span class="label label-black">BL</span>
                                        <?php } elseif ($row->getOverbookingStatus() == \DDD\Service\Booking\BookingTicket::OVERBOOKING_STATUS_OVERBOOKED) { ?>
                                            <span class="label label-grey">DCL</span>
                                        <?php } else if (($row->getGuestBalance() >= 0 && $row->getCheckCharged() > 0) || $row->getModel() == ReservationTicketService::MODEL_PARTNER) { ?>
                                            <span class="label label-success">Ok</span>
                                        <?php } else { ?>
                                            <span class="label label-danger">Call</span>
                                        <?php } ?>
                                        </span>
                                    </td>
                                    <td class="hidden-xs">
                                        <?php if ($this->hasFrontierCard) { ?>
                                            <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>"><?= $row->getReservationNumber(); ?></a>
                                        <?php } else {
                                            echo $row->getReservationNumber();
                                        } ?>
                                    </td>
                                    <td class="hidden-xs"><?php echo $row->getApartmentName() . ' (' . $row->getUnitNumber() . ')'; ?></td>
                                    <td class="nowrap hidden-xs">
                                        <div class="concierge-card">
                                            <img src="<?php echo $this->basePath(); ?>/img/cc-icons/<?php echo CreditCard::getNameById($row->getCcType(), $ccNumber, true); ?>.png" class="hidden-print hidden-xs">
                                            <?php echo $ccNumber; ?>
                                        </div>
                                    </td>
                                    <td ><?php echo $row->getOccupancy(); ?></td>
                                    <td class="hidden-xs text-center">
                                        <?php if ($row->getFraudScore() >= ApartmentGroup::SHOW_AS_BLACKLISTED_IN_CONCIERGE_DASHBOARD_IF_MORE_THAN_SCORE) { ?>
                                            <span class="label label-black">BL</span>
                                        <?php } elseif ($row->getOverbookingStatus() == \DDD\Service\Booking\BookingTicket::OVERBOOKING_STATUS_OVERBOOKED) { ?>
                                            <span class="label label-grey">DCL</span>
                                        <?php } else if (($row->getGuestBalance() >= 0 && $row->getCheckCharged() > 0) || $row->getModel() == ReservationTicketService::MODEL_PARTNER) {?>
                                            <span class="label label-success">Ok</span>
                                        <?php } else { ?>
                                            <span class="label label-danger">Call</span>
                                        <?php } ?>
                                    </td>
									<td class="hidden-xs text-center">
										<?php if ($row->getParking()) { ?>
		                                    <span class="label label-primary pull-right" data-toggle="tooltip" title="This reservation has a parking">P</span>
                                        <?php } ?>
									</td>
                                    <td>
                                    <?php
                                        if ($row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_CHECKED_IN ) {
                                            echo '<span class="text-success glyphicon glyphicon-log-in" data-toggle="tooltip" title="Checked-in" data-original-title="Checked-in"></span>';
                                        } else if($row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_CHECKED_OUT) {
                                            echo '<span class="text-success glyphicon glyphicon-log-out" data-toggle="tooltip" title="Checked-out" data-original-title="Checked-out"></span>';
                                        } else if ($row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_NO_SHOW) {
                                            echo '<span class="text-danger glyphicon glyphicon glyphicon-ban-circle" data-toggle="tooltip" title="No Show" data-original-title="No Show"></span>';
                                        }
                                    ?>
                                    </td>
                                    <td style="text-align: right; font-size: 12px; color: #666">
                                        <div class="btn-group">
                                            <!-- for large displays - button with text -->
                                            <button type="button" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown">
                                                <span>Actions</span>
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" data-toggle="modal" data-target="#comment-modal"  class="add-comment-btn" data-res-id="<?php echo $row->getId(); ?>">
                                                        Add Comment
                                                    </a>
                                                </li>
                                                <?php if ($this->hasFronterCharg) { ?>
                                                <li>
                                                    <a href="/frontier/charge/<?=$row->getId() . '/' . $this->groupId . '/' . Helper::hashForFrontierCharge($row->getId())?>">Charge</a>
                                                </li>
                                                <?php } ?>
                                                <?php if (
                                                $row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_EXPECTED
                                                &&
                                                $row->getGuestBalance() >= 0
                                                ) { ?>
                                                    <li>
                                                        <a
                                                            href="javascript:void(0)"
                                                            class="change-status-button"
                                                            data-res-id="<?= $row->getId() ?>"
                                                            data-only-check-in="<?= $row->getId() ?>"
                                                            data-res-email="<?= $row->getGuestEmail() ?>"
                                                            data-status="<?php echo ReservationTicketService::BOOKING_ARRIVAL_STATUS_CHECKED_IN ?>"
                                                            >
                                                            Check-in
                                                        </a>
                                                    </li>
                                                <?php } ?>
                                                <?php
                                                if(   strtotime($this->currentDate) <= strtotime($row->getDate_to())
                                                    && $row->getKiPageStatus() == ReservationTicketService::SEND_KI_PAGE_STATUS
                                                ) {?>
                                                    <li>
                                                        <a target="_blank" href="
                                                                    <?php
                                                        echo 'https://'.DomainConstants::WS_SECURE_DOMAIN_NAME.'/key?code='
                                                            .$row->getKiPageHash()
                                                            .'&view=0'
                                                            .'&bo='.$row->getKiPageGodModeCode();
                                                        ?>">
                                                            Entry Instructions
                                                        </a>
                                                    </li>
                                                <?php } ?>
                                                <?php if ($row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_EXPECTED) { ?>
                                                    <li>
                                                        <a
                                                            href="javascript:void(0)"
                                                            class="change-status-button"
                                                            data-res-id="<?= $row->getId() ?>"
                                                            data-status="<?php echo ReservationTicketService::BOOKING_ARRIVAL_STATUS_NO_SHOW ?>"
                                                            >
                                                            No Show
                                                        </a>
                                                    </li>
                                                <?php } ?>
                                                <?php if ($this->hasFrontierCard) { ?>
                                                    <li>
                                                        <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>">View Card</a>
                                                    </li>
                                                <?php } ?>
                                                <?php if($row->getParking() && $this->hasFrontierCard) { ?>
                                                    <li>
                                                        <a target="_blank" href="/frontier/print-parking-permits/<?= $row->getReservationNumber(); ?>">Print Parking Permit</a>
                                                    </li>
                                                <?php } ?>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                                <?php if ($row->getHousekeepingComment()) { ?>
                                <tr id="<?php echo 'Arrivals-'.$day.'-'.$row->getReservationNumber()."-comment"; ?>" class="concierge-comment-row" style="display: none;">
                                    <td colspan="10">
                                        <?php
                                        if ($row->getHousekeepingComment()) {
                                            echo Helper::commentParser($row->getHousekeepingComment());
                                        }
                                        ?>
                                    </td>
                                </tr>
                                <?php } ?>

                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>
<?php if($this->hasCurrentStayView) {?>
<hr class="margin-top-2">

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-danger">
            <div class="panel-heading collapsed" data-toggle="collapse" href="#currentStays">
                <div class="panel-title pull-left">
                    Current Stays
                </div>
                <div class="glyphicon my-chevron row-arrow hidden-xs pull-right"></div>
                <div class="clearfix"></div>
            </div>
            <div id="currentStays" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table table-hover arrivals-dashboard">
                        <thead>
                        <tr class="ad-cons4-bg">
                            <th> Guest <span class="visible-xs-inline">(Apartment)</span> </th>
                            <th class="hidden-xs" style="width: 120px">Reservation</th>
                            <th class="hidden-xs">Apartment</th>
                            <th class="hidden-xs">Unit</th>
							<th class="hidden-xs text-center">PTC</th>
							<th class="hidden-xs text-center">PK</th>
							<th>ST</th>
                            <th class="w1"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        if ($this->currentStays) {
                            foreach ($this->currentStays as $row) {
                            if ($this->userIsExternal && $row->getGuestBalance() < 0) {
                                continue;
                            }
                                ?>
                                <tr class="filterable danger<?php if ($row->getHousekeepingComment()) { ?> concierge-row-active" data-toggle="not-toggled" data-type="active" data-row-id="<?php echo 'Current-'.$row->getReservationNumber() ?>"<?php } else { ?>"<?php } ?>>
                                <td>
                                    <?php
                                    $guest = $row->getGuestLastName() . ', ' . $row->getGuestFirstName();
                                    if ($this->hasFrontierCard) { ?>
                                        <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>"><?= $guest; ?></a>
                                    <?php } else {
                                        echo $guest;
                                    } ?>
									<?php if ($row->getHousekeepingComment()) { ?>
										<span class="glyphicon glyphicon-comment text-primary" title="Show Housekeeping Comments"></span>
									<?php } ?>
                                    <?php if ($row->getKeyTask()) { ?>
                                    <span class="label label-danger pull-right" data-toggle="tooltip" title="This reservation has an open Keys & Fobs task on it">K</span>
                                    <?php } ?>

                                    <span class="visible-xs-block">
                                    (
                                        <?= $row->getApartmentName() ?>
                                        <?php
                                        if ($row->getUnitNumber()) {
                                            echo ', ' . $row->getUnitNumber();
                                        }
                                        ?>
                                        )
										<?php if ($row->getParking()) { ?>
											<span class="label label-primary pull-right" data-toggle="tooltip" title="This reservation has a parking">P</span>
										<?php } ?>
                                </span>
                                </td>
                                <td class="hidden-xs">
                                <?php if ($this->hasFrontierCard) { ?>
                                    <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>"><?= $row->getReservationNumber(); ?></a>
                                <?php } else {
                                    echo $row->getReservationNumber();
                                } ?>
                                </td>
                                <td class="hidden-xs"><?= $row->getApartmentName() ?></td>
                                <td class="hidden-xs"><?= $row->getUnitNumber() ?></td>
								<td class="hidden-xs text-center">
                                    <?php if ($row->getFraudScore() >= ApartmentGroup::SHOW_AS_BLACKLISTED_IN_CONCIERGE_DASHBOARD_IF_MORE_THAN_SCORE) { ?>
                                        <span class="label label-black">BL</span>
									<?php } elseif ($row->getOverbookingStatus() == \DDD\Service\Booking\BookingTicket::OVERBOOKING_STATUS_OVERBOOKED) { ?>
										<span class="label label-grey">DCL</span>
									<?php } else if (($row->getGuestBalance() >= 0) || $row->getModel() == ReservationTicketService::MODEL_PARTNER) {?>
										<span class="label label-success">Ok</span>
									<?php } else { ?>
										<span class="label label-danger">Call</span>
									<?php } ?>
								</td>
								<td class="hidden-xs text-center">
									<?php if ($row->getParking()) { ?>
										<span class="label label-primary" data-toggle="tooltip" title="This reservation has a parking">P</span>
									<?php } ?>
								</td>
								<td>
								<?php
									if ($row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_CHECKED_IN ) {
										echo '<span class="text-success glyphicon glyphicon-log-in" data-toggle="tooltip" title="Checked-in" data-original-title="Checked-in"></span>';
									} else if($row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_CHECKED_OUT) {
										echo '<span class="text-success glyphicon glyphicon-log-out" data-toggle="tooltip" title="Checked-out" data-original-title="Checked-out"></span>';
									} else if ($row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_NO_SHOW) {
										echo '<span class="text-danger glyphicon glyphicon glyphicon-ban-circle" data-toggle="tooltip" title="No Show" data-original-title="No Show"></span>';
									}
								?>
								</td>
                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown">
                                            <span>Actions</span>
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#" data-toggle="modal" data-target="#comment-modal"  class="add-comment-btn" data-res-id="<?php echo $row->getId(); ?>" data-guest="<?php echo $row->getGuestLastName() . ', ' . $row->getGuestFirstName(); ?>">
                                                    Add Comment
                                                </a>
                                            </li>
                                            <?php if ($this->hasFronterCharg) { ?>
                                                <li>
                                                    <a href="/frontier/charge/<?=$row->getId() . '/' . $this->groupId . '/' . Helper::hashForFrontierCharge($row->getId())?>">
                                                        Charge
                                                    </a>
                                                </li>
                                            <?php } ?>
                                            <?php if ($this->hasFrontierCard) { ?>
                                                <li>
                                                    <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>">View Card</a>
                                                </li>
                                            <?php } ?>
                                            <?php if($row->getParking()  && $this->hasFrontierCard) { ?>
                                                <li>
                                                    <a target="_blank" href="/frontier/print-parking-permits/<?= $row->getReservationNumber(); ?>">Print Parking Permit</a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                </td>
                                </tr>

                                <?php if ($row->getHousekeepingComment()) { ?>
                                    <tr id="<?php echo 'Current-'.$row->getReservationNumber() . "-comment"; ?>" class="concierge-comment-row" style="display: none;">
                                        <td colspan="10">
                                            <?php
                                            if ($row->getHousekeepingComment()) {
                                                echo Helper::commentParser($row->getHousekeepingComment());
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                <?php } ?>
                            <?php
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<?php } ?>
<hr class="margin-top-2">

<div class="row departures-content">
    <div class="col-sm-12">
        <?php foreach($dayStyles as $day => $style) { ?>
        <div class="panel panel-info">
            <div class="panel-heading" data-toggle="collapse" href="#checkouts<?php echo $day ?>">
                <div class="panel-title pull-left">
                    Departures <?php echo $day ?>
                </div>
                <div class="glyphicon my-chevron row-arrow hidden-xs pull-right"></div>
                <div class="clearfix"></div>
            </div>
            <div id="checkouts<?php echo $day ?>" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table table-hover arrivals-dashboard">
                        <thead>
                            <tr class="ad-cons4-bg">
                                <th class="guest-name">Guest</th>
                                <th class="reservation hidden-xs">Reservation</th>
                                <th class="apartment">Apartment</th>
                                <th class="unit hidden-xs">Unit</th>
								<th class="hidden-xs text-center">PTC</th>
								<th class="hidden-xs text-center">PK</th>
                                <th>ST</th>
                                <th style="width: 1px;"> &nbsp; </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->{'checkouts'.$day} as $row) { ?>
                            <?php
                            if ($this->userIsExternal && $row->getGuestBalance() < 0) {
                                continue;
                            }
                            ?>
                                <tr class="filterable info<?php if ($row->getHousekeepingComment()) { ?> concierge-row-active" data-toggle="not-toggled" data-type="active" data-row-id="<?php echo 'Departures-'.$day.'-'.$row->getReservationNumber() ?>"<?php } else { ?>"<?php }?>>
                                    <td>
                                        <?php
                                        $guest = $row->getGuestLastName() . ', ' . $row->getGuestFirstName();
                                        if ($this->hasFrontierCard) { ?>
                                            <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>"><?= $guest; ?></a>
                                        <?php } else {
                                            echo $guest;
                                        } ?>
										<?php if ($row->getHousekeepingComment()) { ?>
											<span class="glyphicon glyphicon-comment text-primary" title="Show Housekeeping Comments"></span>
										<?php } ?>
                                        <?php if ($row->getKeyTask()) { ?>
                                            <span class="label label-danger pull-right" data-toggle="tooltip" title="This reservation has an open Keys & Fobs task on it">K</span>
                                        <?php } ?>
										<span class="visible-xs-block">
											<?php if ($row->getParking()) { ?>
												<span class="label label-primary pull-right" data-toggle="tooltip" title="This reservation has a parking">P</span>
											<?php } ?>
		                                </span>
                                    </td>
                                    <td class="hidden-xs">
                                    <?php if ($this->hasFrontierCard) { ?>
                                        <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>"><?= $row->getReservationNumber(); ?></a>
                                    <?php } else {
                                        echo $row->getReservationNumber();
                                    } ?>
                                    </td>
                                    <td>
                                        <?= $row->getApartmentName() ?>
                                        <span class="visible-xs-inline">

                                        <?php if($row->getUnitNumber()) {
                                            echo ', ' . $row->getUnitNumber();
                                        } ?>

                                        </span>
                                    </td>
                                    <td class="hidden-xs"><?php echo $row->getUnitNumber(); ?></td>
									<td class="hidden-xs text-center">
                                        <?php if ($row->getFraudScore() >= ApartmentGroup::SHOW_AS_BLACKLISTED_IN_CONCIERGE_DASHBOARD_IF_MORE_THAN_SCORE) { ?>
                                            <span class="label label-black">BL</span>
										<?php } elseif ($row->getOverbookingStatus() == \DDD\Service\Booking\BookingTicket::OVERBOOKING_STATUS_OVERBOOKED) { ?>
											<span class="label label-grey">DCL</span>
										<?php } else if (($row->getGuestBalance() >= 0 ) || $row->getModel() == ReservationTicketService::MODEL_PARTNER) {?>
											<span class="label label-success">Ok</span>
										<?php } else { ?>
											<span class="label label-danger">Call</span>
										<?php } ?>
									</td>
									<td class="hidden-xs text-center">
										<?php if ($row->getParking()) { ?>
											<span class="label label-primary" data-toggle="tooltip" title="This reservation has a parking">P</span>
										<?php } ?>
									</td>
                                    <td>
                                        <?php
                                        if ($row->getArrivalStatus() == ReservationTicketService::BOOKING_ARRIVAL_STATUS_CHECKED_OUT) {
                                            echo '<span class="text-success glyphicon glyphicon-log-out" data-toggle="tooltip" title="Checked-out" data-original-title="Checked-out"></span>';
                                        }
                                        ?>
                                    </td>
                                    <td class="text-right">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown">
                                                <span>Actions</span>
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#"  data-toggle="modal" data-target="#comment-modal"  class="add-comment-btn" data-res-id="<?php echo $row->getId(); ?>" data-guest="<?php echo $row->getGuestLastName() . ', ' . $row->getGuestFirstName(); ?>">
                                                        Add Comment
                                                    </a>
                                                </li>
                                                <?php if ($this->hasFronterCharg) { ?>
                                                <li>
                                                    <a href="/frontier/charge/<?=$row->getId() . '/' . $this->groupId . '/' . Helper::hashForFrontierCharge($row->getId())?>">Charge</a>
                                                </li>
                                                <?php } ?>
                                                <?php if ($row->getArrivalStatus() != ReservationTicketService::BOOKING_ARRIVAL_STATUS_CHECKED_OUT) { ?>
                                                    <li>
                                                        <a
                                                            href="javascript:void(0)"
                                                            class="change-status-button"
                                                            data-res-id="<?= $row->getId() ?>"
                                                            data-status="<?php echo ReservationTicketService::BOOKING_ARRIVAL_STATUS_CHECKED_OUT ?>"
                                                            >
                                                            Check-out
                                                        </a>
                                                    </li>
                                                <?php } ?>
                                                <?php if ($this->hasFrontierCard) { ?>
                                                    <li>
                                                        <a target="_blank" href="/frontier?id=1_<?= $row->getId(); ?>">View Card</a>
                                                    </li>
                                                <?php } ?>
                                                <?php if($row->getParking()  && $this->hasFrontierCard) { ?>
                                                    <li>
                                                        <a target="_blank" href="/frontier/print-parking-permits/<?= $row->getReservationNumber(); ?>">Print Parking Permit</a>
                                                    </li>
                                                <?php } ?>

                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                                <?php if ($row->getHousekeepingComment()) { ?>
                                    <tr id="<?php echo 'Departures-'.$day.'-'.$row->getReservationNumber()."-comment"; ?>" class="concierge-comment-row" style="display: none;">
                                        <td colspan="6">
                                            <?php
                                                if ($row->getHousekeepingComment()) {
                                                    echo $row->getHousekeepingComment();
                                                }
                                            ?>
                                        </td>
                                    </tr>
                                <?php } ?>

                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>

<div class="modal fade" id="comment-modal" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary text-primary">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Add Comment</h4>
            </div>
            <div class="modal-body">
                <textarea type="text" name="comment_field" id="comment-field" class="form-control" placeholder="Your comment here..."></textarea>
                <input type="hidden" id="res-id" name="res_id" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="submit-comment">Submit Comment</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="email-modal" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary text-primary">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Add Email</h4>
            </div>
            <div class="modal-body">
                <input type="text" name="guest-email" id="guest-email" class="form-control" placeholder="Guest Email">
                <input type="hidden" id="reservation-id" name="reservation-id" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="submit-email">Add Email & Check-in</button>
            </div>
        </div>
    </div>
</div>


<?php } ?>
