<div class="row">
    <div class="col-sm-12">
        <table id="datatable-assets-consumable" class="table table-striped table-bordered table-condensed table-hover hidden">
            <thead>
            <tr>
                <th>Category</th>
                <th>Location</th>
                <th>Quantity</th>
                <th>Running-out</th>
                <th>Threshold</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


