<div class="row">
    <div class="col-sm-12">
        <table id="datatable-assets-valuable" class="table table-striped table-bordered table-condensed table-hover hidden">
            <thead>
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Location</th>
                <th>Status</th>
                <th>Assignee</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


