<?php

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->apartmentName . ' - Apartment History');
$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/apartment/common.css');
$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/pages/apartment.history.js');
?>

<script>
    var aaData = <?= $aaData ?>;
</script>

<div class="row">
    <div class="col-sm-12">
        <hr>
        <?php echo $this->apartmentNavigation($this->apartmentId, $this->apartmentStatus, 'apartment/history'); ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <table id="history" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> Date </th>
                <th> Employee </th>
                <th> Category </th>
                <th> Action </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>