<?php

$this->layout()->viewTitle = $this->partnerName ;
$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->partnerName);

$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    ['Partner Management', $this->url('backoffice/default', ['controller' => 'partners'])],
    [$this->layout()->viewTitle],
]);

$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.responsive.css')
        ->appendStylesheet($this->basePath() . '/css/pages/partners.css');
$this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/plugins/fnReloadAjax.js')
        ->appendFile($this->basePath() . '/js/plugins/jquery.form.min.js')
        ->appendFile($this->basePath() . '/js/pages/partner.edit.js')
        ->appendFile($this->basePath() . '/js/validation/partners.js');
?>

<script type="text/javascript">
    var aaData = <?= json_encode($logs) ?>;
    var GENERAL_PARTNER_ID                      = '<?= $this->partnerId ?>';
    var GENERAL_EXTERNAL_ACCOUNT_EDIT           = '<?= $this->url('backoffice/default', ['controller' => 'partners', 'action' => 'ajax-partner-account-edit']) ?>';
    var GLOBAL_PARTNER_CITY_COMMISSION          = '<?= $this->url('backoffice/default', ['controller' => 'partners', 'action' => 'ajax-add-partner-city-commission'])?>';
    var DATATABLE_PARTNER_ACCOUNTS_AJAX_SOURCE = '<?= $this->url('backoffice/default', ['controller' => 'partners', 'action' => 'ajax-get-partner-account-list', 'id' => $this->partnerId]) ?>';
    var DATATABLE_PARTNER_ACCOUNTS_ARCHIVE     = '<?= $this->url('backoffice/default', ['controller' => 'partners', 'action' => 'ajax-set-partner-account-archive']) ?>';

    $(function() {
    	$( "#cubilis_id" ).selectize({
            delimiter: ',',
            persist: false,
            create: function(input) {
                return {
                    value: input,
                    text: input
                }
            }
        });
  	});
</script>

<ul id="groupTabs" class="nav nav-tabs tabs-general" role="tablist">
    <li class="active">
        <a href="#administration" data-toggle="tab" role="tab" id="administration-tab">Administration</a>
    </li>
    <li>
        <a href="#commission-part" data-toggle="tab" role="tab" id="commission-tab">Commission</a>
    </li>
    <?php if ($hasGCMSpecificRole) : ?>
    <li>
        <a href="<?= $this->url('backoffice/default', ['controller' => 'partners', 'action' => 'gcm-specific', 'id' => $this->partnerId]) ?>" id="gcm-specific-tab">GCM Specific</a>
    </li>
    <?php endif; ?>
    <?php if ($this->transactionAccountId) : ?>
    <li style="display: none" class="tab-highlights">
        <a href="#edit-account" data-toggle="tab" id="edit-account-tab" data-tab-name="edit-account">
            Edit Account
        </a>
    </li>
    <?php endif; ?>
    <li class="pull-right">
        <a href="#history" data-toggle="tab" role="tab" id="history-tab"><span class="glyphicon glyphicon-list-alt"></span> History</a>
    </li>
</ul>

<!-- Form opening tag -->
<?= $this->form()->openTag($this->form) ?>
<div id="groupTabsContent" class="tab-content">

    <div class="tab-pane fade active in" id="administration">
        <?= $this->formOutput ?>
    </div>
    <div class="tab-pane fade" id="commission-part">
        <div class="row">
            <div class="col-sm-6">
                <fieldset>
                    <legend>
                        General
                    </legend>
                    <div class="row form-group">
                        <label for="<?= $form->get('commission')->getAttribute('id'); ?>" class="control-label col-sm-4">
                            <?= $this->info($form->get('commission')->getLabel(), 'The commission that will be used for all locations which are not specified otherwise.'); ?>
                        </label>
                        <div class="col-sm-3">
                            <?= $this->formSelect($form->get('commission')); ?>
                        </div>
                    </div>
                    <div class="row form-group">
                        <label for="<?php echo $form->get('additional_tax_commission')->getAttribute('id'); ?>" class="control-label col-sm-4">
                            <?= $this->info('Delta', 'We pay commission to this partner for tax additional amount.'); ?>
                        </label>
                        <div class="col-sm-3 checkbox">
                            <?php echo $this->formCheckbox($form->get('additional_tax_commission')); ?>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="col-sm-6">
                <fieldset>
                    <legend>
                        City Commission
                    </legend>
                    <?= $this->partial(
                            'backoffice/partial/partner-commission',
                            [
                                'partnerId' => $this->partnerId,
                                'partnerCityCommissionList' => $this->partnerCityCommissionList,
                                'cityList' => $this->cityList,
                            ]
                        );
                    ?>
                </fieldset>
            </div>
            <!-- Start: External Accounts -->
            <div class="col-sm-12">
                <fieldset>
                    <legend>
                        Accounts
                    </legend>
                    <?php if ($this->transactionAccountId) : ?>
                        <div id="status-switch-account">
                            <div class="btn-group fn-buttons pull-right">
                                <a href="#" class="btn btn-sm btn-default active" data-status="all">All</a>
                                <a href="#" class="btn btn-sm btn-default" data-status="archived">Archived</a>
                            </div>
                            <input type="hidden" name="show_status_account" id="show_status_account" value="1" />
                        </div>
                        <div class="row hidden" id="datatable_partner_account_container">
                            <div class="col-sm-12">
                                <table id="datatable_partner_account_info" class="table table-striped table-bordered table-condensed table-hover">
                                    <thead>
                                        <tr>
                                            <th> Default </th>
                                            <th> Name </th>
                                            <th> Type </th>
                                            <th> Full Legal Name </th>
                                            <th> Addresses </th>
                                            <th> Country </th>
                                            <th> Account Number </th>
                                            <th> Routing Number </th>
                                            <th> Actions </th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    <?php else : ?>
                        <div class="col-sm-12 alert alert-danger partner-havent-transaction">
                            This partner doesn't have transaction account.
                        </div>
                    <?php endif; ?>
                </fieldset>
            </div>
            <!-- End: External Accounts -->
        </div>
    </div>
    <div class="tab-pane" id="edit-account">
        <div class="col-sm-12">
            <fieldset name="Edit Account">
                <legend>Edit Account</legend>
            </fieldset>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>

    <div class="tab-pane fade" id="history">
        <table id="historyDatatable" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> Date </th>
                <th> Employee </th>
                <th> Action </th>
                <th> Message </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="container page-actions">
        <div class="row text-right">
            <?php if($this->action == 'edit') : ?>
                <button class="col-sm-2 col-xs-12 btn btn-info margin-left-10 pull-left administration-tab-btn commission-tab-btn" id="<?php echo $form->get('open')->getAttribute('id')?>" value="<?php echo $form->get('open')->getValue()?>">
                    <?php echo $form->get('open')->getLabel() ?>
                </button>
            <?php endif ?>

            <?php if ($this->partnerId && $this->transactionAccountId) : ?>
                <a href="#add-account" data-toggle="tab" class="btn btn-success col-sm-2 col-xs-12 pull-left administration-tab-btn commission-tab-btn" id="add-account" data-partner-id="<?= $this->partnerId ?>">
                    Add New Account
                </a>
            <?php endif; ?>

            <?= $this->formSubmit($form->get('submit')); ?>
            <?php if($this->action == 'edit') { ?>
                <?php
                $modal = $this->status ? 'deactivateModal' : 'activateModal';
                $buttonClass = 'btn-success';
                $buttonName = 'Activate';
                if($this->status) {
                    $buttonClass = 'btn-danger';
                    $buttonName = 'Deactivate';
                }?>
                <a data-toggle="modal" href="#<?= $modal ?>" class="btn administration-tab-btn commission-tab-btn col-sm-2 col-xs-12 margin-left-10 pull-right <?=$buttonClass?>"><?=$buttonName?></a>
            <?php } ?>
        </div>
    </div>
</div>
<!-- Form close tag -->
<?= $this->form()->closeTag() ?>
<?php if ($this->status) { ?>
<div class="modal fade" id="deactivateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">
                    Deactivate Partner <span id="deactivate_group"></span>
                </h4>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
                <button class="btn btn-danger" id="partner_deactivate_button">Deactivate</button>
            </div>
        </div>
    </div>
</div>
<?php } else { ?>
<div id="activateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-success text-success">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel2">Activate Partner</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button class="btn btn-success" id="partner_activate_button">Activate</button>
            </div>
        </div>
    </div>
</div>
<?php } ?>
