<?php
	$this->layout()->viewTitle = 'Partner Management';
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->layout()->viewTitle);
	$this->layout()->breadcrumb = $this->breadcrumb([
		['Administration'],
		[$this->layout()->viewTitle]
	]);

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/partners.js');
?>

<div id="status-switch">
    <div class="btn-group fn-buttons pull-right">
        <a href="#all" class="btn btn-sm btn-default" data-status="all">All</a>
        <a href="#active" class="btn btn-sm btn-default active" data-status="active">Active</a>
        <a href="#inactive" class="btn btn-sm btn-default" data-status="inactive">Inactive</a>
    </div>
    <input type="hidden" name="show_status" id="show-status" value="1" />
</div>

<script>
    DATATABLE_AJAX_SOURCE = '/partners/ajaxpartnerslist';
</script>
<div class="row">
    <div class="col-sm-12">
        <table id="datatable_partners" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th>ST</th>
                <th>GID</th>
                <th>Partner Name</th>
                <th>Contact Name</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Phone</th>
                <th>WEB</th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div class="container page-actions">
    <div class="row text-right">
        <a href="<?= $this->url('backoffice/default', ['controller' => 'partners', 'action' => 'add'])?>" class="btn btn-primary pull-right col-sm-2 col-xs-12">Add Partner</a>
    </div>
</div>
