<?php
use \DDD\Service\Contacts\Contact;
$pageTitle = ($this->contactId) ? 'Edit Contact' : 'Add New Contact';

$this->headTitle($pageTitle)->setSeparator(' - ');

$this->layout()->breadcrumb =
    '<li>Administration</span></li>
    <li>
        <a href="' . $this->url('contacts') . '">
            Contacts
        </a>
    </li>
    <li class="active">' . $pageTitle . '</li>';

$this->layout()->viewTitle  = ($this->contactId) ? $contactData->getName() : $pageTitle;

$this->headLink()->appendStylesheet($this->basePath() . '/css/contacts/main.css');

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/module/contacts/edit-contact.js');
?>

<script>
    var GLOBAL_EDIT_CONTACT_URL = '<?php echo $this->url('contacts/edit'); ?>';
    var GLOBAL_CONTACT_URL          = '<?php echo $this->url('contacts'); ?>';
    var GLOBAL_DELETE_CONTACT_URL   = '<?php echo $this->url('contacts/ajax-delete-contact'); ?>';
    var GLOBAL_GET_BUILDING_URL     = '<?php echo $this->url('contacts/ajax-get-apartment-building'); ?>';
    var GLOBAL_GET_PHONE_CODES      = '<?php echo $this->url('contacts/ajax-get-phone-codes'); ?>';
    var SCOPE_TEAM                  = <?= Contact::SCOPE_TEAM; ?>;

    <?php if ($this->contactId) { ?>
    // current country codes for phones
    var FORM_CURRENT_PHONE_MOBILE_PH = (<?=$this->contactData->getPhoneMobileCountryId()?> > 0)
        ? <?=$this->contactData->getPhoneMobileCountryId()?>
        : false;
    var FORM_CURRENT_PHONE_COMPANY_PH = (<?=$this->contactData->getPhoneCompanyCountryId()?> > 0)
        ? <?=$this->contactData->getPhoneCompanyCountryId()?>
        : false;
    var FORM_CURRENT_PHONE_OTHER_PH = (<?=$this->contactData->getPhoneOtherCountryId()?> > 0)
        ? <?=$this->contactData->getPhoneOtherCountryId()?>
        : false;
    var FORM_CURRENT_PHONE_FAX_PH = (<?=$this->contactData->getPhoneFaxCountryId()?> > 0)
        ? <?=$this->contactData->getPhoneFaxCountryId()?>
        : false;
    <?php } ?>
</script>

<?php
$formUrl = ($this->contactId) ? 'contacts/ajax-update-contact' : 'contacts/ajax-create-contact';
$form->setAttribute('action', $this->url($formUrl))
    ->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form);
?>

<input type="hidden" name="contact_id" id="contact_id" value="<?php echo $this->contactId; ?>">

<div class="row">

    <div class="col-sm-12">

        <div class="col-sm-6">
            <fieldset name="general">
                <legend>General</legend>

                <div class="form-group">

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="name">
                            <?php echo $form->get('name')->getLabel() . ' ' . $this->required(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formInput($form->get('name')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="company">
                            <?php echo $form->get('company')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formInput($form->get('company')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="position">
                            <?php echo $form->get('position')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formInput($form->get('position')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="city">
                            <?php echo $form->get('city')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formInput($form->get('city')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="address">
                            <?php echo $form->get('address')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formInput($form->get('address')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>


                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="url">
                            <?php echo $form->get('url')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formInput($form->get('url')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                </div>
            </fieldset>
        </div>

        <div class="col-sm-6">
            <fieldset name="communication">
                <legend>Communication</legend>

                <div class="form-group">

                    <div class="col-sm-12 phone-row">
                        <label class="col-sm-3 control-label" for="phone_mobile">
                            <?php echo $form->get('phone_mobile')->getLabel(); ?>
                        </label>
                        <div class="col-sm-3 controls">
                            <?php echo $this->formSelect($form->get('phone_mobile_country_id')); ?>
                        </div>
                        <div class="col-sm-6 controls phone-number">
                            <?php echo $this->formInput($form->get('phone_mobile')); ?>
                        </div>
                        <div class="help-block"></div>
                    </div>

                    <div class="col-sm-12 phone-row">
                        <label class="col-sm-3 control-label" for="phone_company">
                            <?php echo $form->get('phone_company')->getLabel(); ?>
                        </label>
                        <div class="col-sm-3 controls">
                            <?php echo $this->formSelect($form->get('phone_company_country_id')); ?>
                        </div>
                        <div class="col-sm-6 controls phone-number">
                            <?php echo $this->formInput($form->get('phone_company')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12 phone-row">
                        <label class="col-sm-3 control-label" for="phone_other">
                            <?php echo $form->get('phone_other')->getLabel(); ?>
                        </label>
                        <div class="col-sm-3 controls">
                            <?php echo $this->formSelect($form->get('phone_other_country_id')); ?>
                        </div>
                        <div class="col-sm-6 controls phone-number">
                            <?php echo $this->formInput($form->get('phone_other')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12 phone-row">
                        <label class="col-sm-3 control-label" for="phone_fax">
                            <?php echo $form->get('phone_fax')->getLabel(); ?>
                        </label>
                        <div class="col-sm-3 controls">
                            <?php echo $this->formSelect($form->get('phone_fax_country_id')); ?>
                        </div>
                        <div class="col-sm-6 controls phone-number">
                            <?php echo $this->formInput($form->get('phone_fax')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="email">
                            <?php echo $form->get('email')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formInput($form->get('email')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>


                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="skype">
                            <?php echo $form->get('skype')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formInput($form->get('skype')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                </div>
            </fieldset>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-sm-12">
        <fieldset name="affiliations">
            <legend>Affiliations</legend>

            <div class="col-sm-6">
                <div class="form-group">
                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="scope">
                            <?php echo $form->get('scope')->getLabel() ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formSelect($form->get('scope')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12" id="team-block">
                        <label class="col-sm-3 control-label" for="team_id">
                            <?php echo $form->get('team_id')->getLabel() . ' ' . $this->required(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formSelect($form->get('team_id')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="partner_id">
                            <?php echo $form->get('partner_id')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formSelect($form->get('partner_id')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-sm-6">
                <div class="form-group">

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="apartment_id">
                            <?php echo $form->get('apartment_id')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formSelect($form->get('apartment_id')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-3 control-label" for="building_id">
                            <?php echo $form->get('building_id')->getLabel(); ?>
                        </label>
                        <div class="col-sm-9 controls">
                            <?php echo $this->formSelect($form->get('building_id')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                </div>
            </div>

        </fieldset>
    </div>

</div>

<div class="row">
    <div class="col-sm-12">
        <fieldset name="general">
            <legend>Others</legend>
            <div class="col-sm-12">
                <div class="form-group">

                    <div class="col-sm-12">
                        <div class="col-sm-12 controls">
                            <?php echo $this->formRow($form->get('notes')); ?>
                            <div class="help-block"></div>
                        </div>
                    </div>

                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <?php echo $this->formButton($form->get('save_button')); ?>
        <?php if ($this->contactId > 0) { ?>
        <button type="button" name="delete_button" id="delete_button" data-loading-text="Deleting..." class="btn btn-danger pull-right col-xs-12 col-sm-2 margin-left-10" value="Delete">Delete Contact</button>
        <?php } ?>
    </div>
</div>

<?php echo $this->form()->closeTag(); ?>

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                </button>
                <h4 id="myModalLabel">Delete Contact</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this contact?</p>
                <p>* Deleted contacts can not be restored!</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button class="btn btn-danger" id="go_delete_button">Delete Contact</button>
            </div>
        </div>
    </div>
</div>
