<?php
$environment = getenv('APPLICATION_ENV') ?: 'production';


echo "<script src='{$this->basePath()}/js/vendor/tinymce/tinymce.min.js' type='text/javascript'></script>";

?>
<script>
    var GLOBAL_UPLOAD_IMG = '<?= $this->url('backoffice/default', array('controller' => 'blog', 'action' => 'ajax-upload-image'))?>';
    var GLOBAL_SAVE       = '<?= $this->url('backoffice/default', array('controller' => 'blog', 'action' => 'ajaxsave'))?>';
    var GLOBAL_DELETE_IMG = '<?= $this->url('backoffice/default', array('controller' => 'blog', 'action' => 'ajaxremove'))?>';
    var GLOBAL_DELETE     = '<?= $this->url('backoffice/default', array('controller' => 'blog', 'action' => 'ajaxdelete'))?>';
</script>
<?php
	$blogPostName = $this->blogForm->get('title')->getvalue();
    if (is_null($blogPostName)) {
        $blogPostName = 'Add Page';
    }

    $this->headTitle()->setSeparator(' - ');
    $this->headTitle($blogPostName);
    $this->layout()->breadcrumb = '<li>Content</span></li>
                                   <li><a href="'.$this->url('backoffice/default', array('controller' => 'blog', 'action' => 'index')).'">Blog</a></li>
                                   <li>' . $blogPostName . '</li>';
    $this->layout()->viewTitle  = $blogPostName;
    $this->InlineScript()
		->appendFile($this->basePath() . '/js/plugins/jquery.form.min.js')
		->appendFile($this->basePath() . '/js/pages/blog.js');

    $form = $this->blogForm;
    if(is_object($form)):
    $form->prepare();
    $form->setAttribute('action', $this->url('backoffice/default', array('controller' => 'blog', 'action' => 'edit')));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('id', 'blog_form');?>

<?php
    echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-md-12">
     <fieldset name="general">
        <legend>General</legend>
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label class="col-md-3 control-label" for="title">Title  <?php echo $this->required(); ?></label>
                    <div class="col-md-9 controls">
                        <?php
                            echo $this->formInput($form->get('title'));
                        ?>
                        <div class="help-block"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="col-sm-6 control-label" for="date">Date <?php echo $this->required(); ?></label>
                    <div class="col-sm-6">
                        <?=$this->formInput($form->get('date'))?>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="body">Body  <?php echo $this->required(); ?></label>
            <div class="col-md-10 controls">
                <?php echo $this->formElement($form->get('body')); ?>
                <div class="help-block"></div>
            </div>
        </div>
    </fieldset>
    </div>
    <div class="col-md-12">
         <fieldset name="Image">
            <legend>Image</legend>
            <div class="form-group">
                <label class="col-md-2 control-label" for="img">Image</label>
                <div class="col-md-10 controls">
                    <?php
                        echo $this->formElement($form->get('img'));
                    ?>
                </div>
                <div class="col-md-2"></div>
                <div class="clearfix visible-xs-block"></div>
                <div class="col-md-10 help-block" id="img_preview">
                    <?php if($form->get('img_post')->getValue() != ''):?>
                        <div id="img_attachment-container" class="clear left mt10">
                            <img style="width: 100px;" src="//<?=$this->imgDomain.$form->get('img_post')->getValue()?>">
                        </div>
                    <?php endif;?>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="page-actions container">
    <div class="row text-right">

        <?php if ($this->edit > 0):?>
            <a href="<?=$this->urlSie?>" target="_blank" data-toggle="modal"
            class="btn btn-info pull-left col-xs-12 col-sm-2">View on Website</a>
        <?php endif; ?>
        <?php
            echo $this->formInput($form->get('edit_id'));
            echo $this->formInput($form->get('img_post'));
            echo $this->formInput($form->get('edit_title'));
            echo $this->formButton($form->get('save_button'));
        ?>
        <?php if ($this->edit > 0): ?>
            <div class="visible-xs-block clearfix"></div>
            <a href="#deleteModal" data-toggle="modal" class="btn btn-danger pull-right col-xs-12 col-sm-2">Delete Blog Post</a>
        <?php endif;?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                </button>
                <h4 id="myModalLabel">Delete Blog Post</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button class="btn btn-danger" id="delete_button">Delete Blog Post</button>
            </div>
        </div>
    </div>
</div>

<div id="changeUrlModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-warning text-warning">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                </button>
                <h4 id="myModalLabel">Warning</h4>
            </div>
            <div class="modal-body">
                <p>If you change this field the permanent URL will change too. Think about SEO and make sure you really want to make this change.</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button class="btn btn-warning" id="save_modal_button">Save</button>
            </div>
        </div>
    </div>
</div>
<?php else: ?>
<div style="font-size: 20px;text-align: center;height: 600px;">Aweee, </div>
<?php endif;?>
