<script>
    var GLOBAL_DELETE     = '<?= $this->url('backoffice/default', array('controller' => 'blog', 'action' => 'ajaxdelete'))?>';
    var aaData = <?= $aaData; ?>;
</script>
<?php
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('Blog');
    $this->layout()->breadcrumb = '<li>Content</li>
                                   <li class="active">Blog</li>';
    $this->layout()->viewTitle  = 'Blog';
    $this->InlineScript()->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/blog.js');

    $this->headLink()->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

?>
<div class="row">
    <div class="col-md-12">
        <table id="datatable_blog" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> Date </th>
                <th> Title </th>
                <th> Web </th>
                <th> Edit </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<div class="container page-actions">
    <div class="row text-right">
        <a href="<?= $this->url('backoffice/default', array('controller' => 'blog',
        'action' => 'edit'))?>" class="btn btn-primary col-sm-2 col-xs-12 margin-left-10 pull-right">Add Travel Blog Post</a>
    </div>
</div>
<input type="hidden" name="edit_id" id="edit_id" value="0" />
