<?php
    $layoutViewModel = $this->viewModel()->getRoot();
    $apartelId = $layoutViewModel->apartelId;
?>
<?php echo $this->apartelHeader($apartelId); ?>
<?php
    $this->headTitle('Room Type / Rate')->setSeparator(' - ');
    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/apartel/common.css');
    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/apartel/rate.js')
        ->appendFile($this->basePath() . '/js/apartel/validation/rate.js');
    $form = $this->form;

    $isWeekMinus = isset($this->viewPriceData['is_week_minus']) && $this->viewPriceData['is_week_minus'] ? true : false;
    $isWeekendMinus = isset($this->viewPriceData['is_weekend_minus']) && $this->viewPriceData['is_weekend_minus'] ? true : false;
?>
<div class="row">
    <?php echo $this->form()->openTag($form)?>
    <div class="col-sm-3">
        <?php echo $this->typeRateNavigation($this->typeRates, $apartelId);?>
    </div>
    <div class="col-sm-9">
        <div class="row">
            <div class="col-sm-12">
                <fieldset>
                    <legend>General</legend>
                    <?= $this->formInput($form->get('type_id')) ?>
                    <?= $this->formInput($form->get('rate_id')) ?>
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('rate_name')->getAttribute('id') ?>">
                            <?= $form->get('rate_name')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>
                        <div class="col-sm-4">
                            <?= $this->formInput($form->get('rate_name')) ?>
                        </div>
                    </div>

                    <div class="form-group <?=  ($this->isParent) ? 'soft-hide' : ''?>">
                        <label class="control-label col-sm-3" for="<?= $form->get('active')->getAttribute('id') ?>">
                            <?= $form->get('active')->getLabel() ?>
                        </label>
                        <div class="col-sm-2">
                            <?= $this->formSelect($form->get('active')) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('type')->getAttribute('id') ?>">
                            <?= $form->get('type')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>
                        <div class="col-sm-3">
                            <?= $this->formSelect($form->get('type')) ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('capacity')->getAttribute('id') ?>">
                            <?= $form->get('capacity')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>
                        <div class="col-sm-4 col-md-2">
                            <?= $this->formInput($form->get('capacity')) ?>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="col-sm-12">
                <fieldset>
                    <legend>Price</legend>
                    <div class="form-group">

                        <label class="control-label col-sm-3" for="<?= $form->get('week_price')->getAttribute('id') ?>">
                            <?= $form->get('week_price')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>

                        <div class="col-sm-3">
                            <div class="input-group form-inline">

                                <?php if ($this->isParent) {?>
                                    <span class="input-group-addon"><?= $this->currency?></span>
                                <?php } else { ?>
                                    <span class="input-group-btn">
                                        <a href="javascript:void(0)" class="btn <?=$isWeekMinus ? 'btn-danger' : 'btn-success'?> btn-number plus-minus-switcher">
                                            <span class="glyphicon glyphicon-<?=$isWeekMinus ? 'minus' : 'plus'?>"></span>
                                        </a>
                                        <input type="hidden" name="week_day_plus_minus" id="week_day_plus_minus" class="plus-minus-symbol" value="<?=$isWeekMinus ? -1 : 1?>">
                                    </span>
                                <?php } ?>

                                <?= $this->formInput($form->get('week_price')) ?>
                                <?php if (!$this->isParent) {?>
                                    <span class="input-group-addon">%</span>
                                <?php } ?>
                            </div>
                        </div>
                        <?php if (!$this->isParent) {?>
                            <div class="col-md-5 col-sm-2">
                                 <span class="checkbox">
                                    <span class="current-rate-price-view">
                                        <?=isset($this->viewPriceData['week_price']) ? $this->viewPriceData['week_price'] : '' ?></span> <?= $this->currency?>
                                    </span>
                                </span>
                            </div>
                        <?php } ?>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('weekend_price')->getAttribute('id') ?>">
                            <?= $form->get('weekend_price')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>

                        <div class="col-sm-3">
                            <div class="input-group">
                                <?php if ($this->isParent) {?>
                                    <span class="input-group-addon"><?= $this->currency?></span>
                                <?php } else { ?>
                                    <span class="input-group-btn">
                                        <a href="javascript:void(0)" class="btn <?=$isWeekendMinus ? 'btn-danger' : 'btn-success'?> btn-number plus-minus-switcher">
                                            <span class="glyphicon glyphicon-<?=$isWeekendMinus ? 'minus' : 'plus'?>"></span>
                                        </a>
                                        <input type="hidden" name="weekend_plus_minus" id="weekend_plus_minus" class="plus-minus-symbol" value="<?=$isWeekendMinus ? -1: 1?>">
                                    </span>
                                <?php } ?>
                                <?= $this->formInput($form->get('weekend_price')) ?>
                                <?php if (!$this->isParent) {?>
                                    <span class="input-group-addon">%</span>
                                <?php } ?>
                            </div>
                        </div>
                        <?php if (!$this->isParent) {?>
                            <div class="col-md-5 col-sm-2">
                                 <span class="checkbox">
                                    <span class="current-rate-price-view">
                                        <?=isset($this->viewPriceData['weekend_price']) ? $this->viewPriceData['weekend_price'] : '' ?>
                                    </span>
                                     <?= $this->currency?>
                                 </span>
                            </div>
                        <?php } ?>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <fieldset>
                    <legend>Stay</legend>
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('min_stay')->getAttribute('id') ?>">
                            <?= $form->get('min_stay')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>
                        <div class="col-sm-3">
                            <div class="input-group">
                                <?= $this->formInput($form->get('min_stay')) ?>
                                <span class="input-group-addon">Nights</span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('max_stay')->getAttribute('id') ?>">
                            <?= $form->get('max_stay')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>
                        <div class="col-sm-3">
                            <div class="input-group">
                                <?= $this->formInput($form->get('max_stay')) ?>
                                <span class="input-group-addon">Nights</span>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="col-sm-12">
                <fieldset>
                    <legend>Release Window</legend>
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('release_window_start')->getAttribute('id') ?>">
                            <?= $form->get('release_window_start')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>
                        <div class="col-sm-3">
                            <div class="input-group">
                                <?= $this->formInput($form->get('release_window_start')) ?>
                                <span class="input-group-addon">Days</span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('release_window_end')->getAttribute('id') ?>">
                            <?= $form->get('release_window_end')->getLabel() ?>
                            <?= $this->required() ?>
                        </label>
                        <div class="col-sm-3">
                            <div class="input-group">
                                <?= $this->formInput($form->get('release_window_end')) ?>
                                <span class="input-group-addon">Days</span>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <fieldset>
                    <legend>Cancelation</legend>
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="<?= $form->get('is_refundable')->getAttribute('id') ?>">
                            <?= $form->get('is_refundable')->getLabel() ?>
                        </label>
                        <div class="col-sm-4 col-md-2">
                            <?= $this->formRadio($form->get('is_refundable')) ?>
                        </div>
                    </div>

                    <div id="refundable_options">
                        <div class="form-group">
                            <label class="control-label col-sm-3" for="<?= $form->get('refundable_before_hours')->getAttribute('id') ?>">
                                <?= $form->get('refundable_before_hours')->getLabel() ?>
                            </label>
                            <div class="col-sm-4 col-md-2">
                                <?= $this->formSelect($form->get('refundable_before_hours')) ?>
                            </div>
                            <div class="col-sm-5 col-md-3">
                                <?= $this->formRadio($form->get('penalty_type')) ?>
                            </div>
                            <div class="col-sm-3">
                                <div class="row">
                                    <div class="col-sm-12 col-md-8" id="penalty_percent_row">
                                        <div class="input-group">
                                            <?= $this->formInput($form->get('penalty_percent')) ?>
                                            <label class="input-group-addon"> % </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12" id="penalty_amount_row">
                                        <?= $this->formInput($form->get('penalty_fixed_amount')) ?>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12" id="penalty_night_row">
                                        <?= $this->formInput($form->get('penalty_nights')) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <?php echo $this->formElement($form->get('save_button'));?>
        <?php  if (!$this->isParent && $this->rateId) { ?>
            <a href="javascript:void(0)" data-toggle="modal" data-target="#delete-modal" class="btn col-sm-2 col-xs-12 margin-left-10 pull-right btn-danger">Delete</a>
        <?php } ?>
    </div>
</div>

<!-- Delete rate modal -->
<div id="delete-modal" class="modal fade" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true"><span class="sr-only">Close</span>&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Delete Rate <span id="delete_group"></span></h4>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger" id="rates_delete_button" href="<?php echo $this->url('apartel/type-rate/type/rate-delete', ['rate_id' => $this->rateId, 'type_id' => $this->typeId, 'apartel_id' => $apartelId])?>">Delete Rate</a>
            </div>
        </div>
    </div>
</div>
<script>
    var GLOBAL_IS_PARENT = <?= $this->isParent ? 1 : 0 ?>;
    var GLOBAL_PARENT_WEEK_PRICE = <?= $this->parentPrices['week_price'] ?>;
    var GLOBAL_PARENT_WEEKEND_PRICE = <?= $this->parentPrices['weekend_price'] ?>;
</script>
