<?php
$current = 'Review Management';
$this->layout()->viewTitle = $current;
$this->layout()->breadcrumb = $this->breadcrumb([
	['Apartments'],
	[$current]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);


$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/module/reviews/general.js')
    ->prependFile('//code.highcharts.com/highcharts.js');
$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/pages/reviews.css');
?>
<script>
    var DATATABLE_AJAX_SOURCE = '/reviews/get-datatable-data';
    var CATEGORIES_INFO_URL = '/reviews/get-categories-info';
    var CHART_INFO_URL = '/reviews/get-chart-info';
    var CHANGE_REVIEW_CATEGORIES = '/reviews/change-review-categories';
    var CHANGE_STATUS = '/reviews/change-status';
    var DELETE_REVIEW = '/reviews/delete';
</script>
<div class="row">
    <div class="col-sm-12">
        <div class="row">
            <?= $this->form()->openTag($form); ?>
            <div class="col-sm-4">
                <?= $this->formSelect($form->get('apartment_groups')) ?>
            </div>
            <div class="col-sm-4">
                <?= $this->formSelect($form->get('tags')) ?>
            </div>
            <div class="col-sm-4">
                <div class="explanation-div-container">
                    <span class="text-muted explanation-span">Score Filter</span>
                    <a href="#" class="review-score-chooser">1</a>
                    <a href="#" class="review-score-chooser">2</a>
                    <a href="#" class="review-score-chooser">3</a>
                    <a href="#" class="review-score-chooser">4</a>
                    <a href="#" class="review-score-chooser">5</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <?= $this->formInput($form->get('arrival_date_range')) ?>
            </div>
            <div class="col-sm-4">
                <?= $this->formInput($form->get('departure_date_range')) ?>
            </div>
            <div class="col-sm-4">
                <div class="explanation-div-container explanation-div-container-small-padding">
                    <span class="text-muted explanation-span">Stay Length</span>
                    <?= $this->formInput($form->get('stay_length_from')) ?>
                    <span class="text-muted">&nbsp;-&nbsp;</span>
                    <?= $this->formInput($form->get('stay_length_to')) ?>
                </div>
            </div>
        </div>
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="col-sm-9">
                <a href="javascript:void(0)" class="btn btn-medium btn-block btn-primary" id="btn_search_review"><i class="icon-search icon-white"></i> Search</a>
            </div>
            <div class="col-sm-3">
                <a href="javascript:void(0)" class="btn btn-medium btn-block btn-default" id="clear-reviews-filters"><i class="icon-search icon-white"></i>Clear Filter</a>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>


<div class="chart-and-review-categories-counter-part hidden">
    <div class="row">
        <div class="col-sm-8 chart-part">
            <div id="chart-container" style="min-width: 310px; height: 400px;"></div>
        </div>
        <div class="col-sm-4 review-categories-counter-part">
            <table class="table">

            </table>
        </div>
    </div>

</div>

<hr class="hide-on-success">

<div class="row">
    <div class="col-sm-12">
        <table id="datatable-reviews" class="table table-striped table-bordered table-condensed table-hover hidden">
            <thead>
            <tr>
                <th> R# </th>
                <th> <span class="glyphicon glyphicon-star-empty"></span> </th>
                <th> Review Date </th>
                <th> S </th>
                <th> Review </th>
                <th> Comment </th>
                <th> Codification </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 id="myModalLabel" class="modal-title">Delete Review<span id="delete_group"></span></h4>
            </div>
            <div class="modal-body">
                <p>Are you sure to delete the review ?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <a class="btn btn-danger" href="" id="delete_review_submit">Delete Review</a>
            </div>
        </div>
    </div>
</div>