<?php
use DDD\Service\Asana\Feedback;
?>

<div class="form-group">
    <select class="form-control" id="feedback-account-management-type" name="feedback-account-management-types">
        <?php
        $subTypes = Feedback::getFeedbackAccountManagementSubTypesForSelect();
        foreach ($subTypes as $value => $text) {
        ?>
            <option value="<?= $value ?>" ><?= $text ?></option>
        <?php } ?>
    </select>
</div>