<?php
	$this->layout()->viewTitle = 'Booking Management';
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->layout()->viewTitle);
	$this->layout()->breadcrumb = $this->breadcrumb([
		['Administration'],
		[$this->layout()->viewTitle]
	]);
?>

<script>
    var FIND_PRODUCT_BY_ADDRESS_AUTOCOMPLETE_URL = '<?= $this->url('apartments', array('controller' => 'apartment', 'action' => 'search-by-address-components'))?>';
    var FIND_COUNTRY_AUTOCOMPLETE_URL            = '<?= $this->url('apartments', array('controller' => 'apartment', 'action' => 'search-country'))?>';
    var FIND_COUNTRY_CITY_AUTOCOMPLETE_URL       = '<?= $this->url('apartments', array('controller' => 'apartment', 'action' => 'search-country-city'))?>';
    var BUILDING_SEARCH                          = '<?= $this->url('apartments', ['controller' => 'apartment', 'action' => 'get-buildings'])?>';
	var GLOBAL_AJAX_DOWNLOAD_CSV 			     = '<?= $this->url('backoffice/default', ['controller' => 'booking', 'action' => 'ajax-validate-download-csv'])?>';

    var tableElement = '#datatable_reservations';

    $(document).click(function(event) {
        var target = $(event.target);

        if (!target.hasClass("daterangepicker") && !target.hasClass("form-control") && target.parents(".daterangepicker").length == 0 && target.parents(".calendar-date").length == 0) {
          $(".daterangepicker").hide();
        }
    });
</script>

<?php
    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    	->appendFile($this->basePath() . '/js/pages/booking.js');

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/pages/booking.css');

    $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
?>

<?= $this->formOutput ?>

<div class="row">
    <div class="col-sm-2" id="download-btn">
        <div class="form-group">
            <a href="javascript:void(0)" class="btn btn-block btn-info" id="btn_download_filtered_csv"><i class="glyphicon glyphicon-download"></i> Download</a>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="form-group">
            <a href="javascript:void(0)" class="btn btn-block btn-primary" id="btn_search_booking"><span class="glyphicon glyphicon-search"></span> Search</a>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">
            <a href="#reset" class="btn btn-default btn-block filter-reset">Clear Filter</a>
        </div>
    </div>
</div>

<hr>

<div class="row hidden" id="booking_table_container" data-search-onload="<?php print($this->doSearchOnLoad ? 1 : 0); ?>">
    <div class="col-sm-12">
        <table id="datatable_reservations" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
                <tr>
                    <th>R#</th>
                    <th>ST</th>
                    <th>Date</th>
                    <th>Apartment</th>
                    <th>Guest (Occ)</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Rate</th>
                    <th>Charge</th>
                    <th>Balance</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<script>
	batchAutocomplete('guest_country', 'guest_country_id', FIND_COUNTRY_AUTOCOMPLETE_URL);
	batchCatcomplete('apt_location', 'apt_location_id', FIND_COUNTRY_CITY_AUTOCOMPLETE_URL);
</script>
