<?php

use Library\Constants\Objects;
use Library\Constants\DomainConstants;
use Library\Constants\Constants;
use Library\Constants\TextConstants;
use Library\Utility\Helper;

$this->headTitle()->setSeparator(' - ');
$this->headTitle('Profile');

?>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2>
            This user is no longer working at Ginosi and was deactivated.<br>
            To see profile of this user you need to have appropriate permissions.
        </h2>
    </div>
</div>