<?php

// Form object
$form = $this->form;

/**
 * @var \ArrayObject|array[] $furnitureList
 * @var \ArrayObject|array[] $furnitureTypes
 */
$furnitureList = $this->furnitureList;
$furnitureTypes = $this->furnitureTypes;

$form->prepare ();

?>

<!-- Form opening tag -->
<?= $this->form()->openTag($form) ?>


<div class="row">
	<div class="col-sm-6">
		<fieldset>
			<legend>Financial Details</legend>
		</fieldset>
		<div class="form-group">
			<label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('monthly_cost')->getAttribute('id') ?>">
				<?= $this->info($form->get('monthly_cost')->getLabel(), 'The max amount which should be spent for this apartment per month.'); ?>
			</label>
            <div class="col-xs-6">
                <div class="input-group">
                    <?= $this->formInput($form->get('monthly_cost'))?>
                    <div class="input-group-addon">
                        <?= $this->accCurrency ?>
                    </div>
                </div>
            </div>
		</div>
		<div class="form-group">
			<label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('startup_cost')->getAttribute('id') ?>">
				<?= $this->info($form->get('startup_cost')->getLabel(), 'The max amount which should be spent for this apartment startup.') ?>
			</label>
            <div class="col-xs-6">
                <div class="input-group">
                    <?= $this->formInput($form->get('startup_cost'))?>
                    <div class="input-group-addon">
                        <?= $this->accCurrency ?>
                    </div>
                </div>
            </div>
		</div>
		<div class="form-group">
			<label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('cleaning_fee')->getAttribute('id') ?>">
				<?= $this->info($form->get('cleaning_fee')->getLabel(), 'The amount cost for cleaning this apartment.') ?>
			</label>
			<div class="col-xs-6">
                <div class="input-group">
				    <?= $this->formInput($form->get('cleaning_fee'))?>
                    <div class="input-group-addon">
                        <?= $this->accCurrency ?>
                    </div>
                </div>
			</div>
		</div>

        <div class="form-group">
			<label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('extra_person_fee')->getAttribute('id') ?>">
				<?= $this->info($form->get('extra_person_fee')->getLabel(), 'Extra person fee pear night') ?>
			</label>
			<div class="col-xs-6">
                <div class="input-group">
				    <?= $this->formInput($form->get('extra_person_fee'))?>
                    <div class="input-group-addon">
                        <?= $this->accCurrency ?>
                    </div>
                </div>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('notify_negative_profit')->getAttribute('id') ?>">
				<?= $this->info($form->get('notify_negative_profit')->getLabel(), 'Show notification about negative profit on UD.') ?>
			</label>
			<div class="col-xs-6 checkbox">
				<?= $this->formCheckbox($form->get('notify_negative_profit')) ?>
			</div>
		</div>
	</div>

	<div class="col-sm-6">
        <fieldset>
            <legend>
                Parking
            </legend>
            <div class="form-group">
                <label class="col-xs-4 col-sm-3 control-label" for="<?= $form->get('parking_spot_ids')->getAttribute('id') ?>">
                    <?= $this->info($form->get('parking_spot_ids')->getLabel(), 'Please add the most priority spots for this apartment, in the order they should be selected. The first spot - is most preferable and so on.'); ?>
                </label>
                <div class="col-xs-8">
                    <?= $this->formSelect($form->get('parking_spot_ids')) ?>
                </div>
            </div>
        </fieldset>

		<fieldset>
			<legend>WiFi Internet Details</legend>
		</fieldset>
		<div class="form-group">
			<label class="col-xs-6 col-sm-5 control-label" for="<?= $form->get('primary_wifi_network')->getAttribute('id') ?>">
				<?= $this->info($form->get('primary_wifi_network')->getLabel(), 'This one will be sent to guest.') ?>
			</label>
			<div class="col-xs-6">
				<?= $this->formInput($form->get('primary_wifi_network')) ?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-6 col-sm-5 control-label" for="<?= $form->get('primary_wifi_pass')->getAttribute('id') ?>">
				<?= $form->get('primary_wifi_pass')->getLabel() ?>
			</label>
			<div class="col-xs-6">
				<?= $this->formInput($form->get('primary_wifi_pass')) ?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-6 col-sm-5 control-label" for="<?= $form->get('secondary_wifi_network')->getAttribute('id') ?>">
				<?= $form->get('secondary_wifi_network')->getLabel() ?>
			</label>
			<div class="col-xs-6">
				<?= $this->formInput($form->get('secondary_wifi_network')) ?>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-6 col-sm-5 control-label" for="<?= $form->get('secondary_wifi_pass')->getAttribute('id') ?>">
				<?= $form->get('secondary_wifi_pass')->getLabel() ?>
			</label>
			<div class="col-xs-6">
				<?= $this->formInput($form->get('secondary_wifi_pass')) ?>
			</div>
		</div>
	</div>
</div>
	<!-- PIN Prefix -->
<div class="row">
	<div class="col-sm-12">
		<fieldset><legend>Guest Entry and Communication</legend></fieldset>
		<div class="row">
			<div class="col-sm-6">
				<div class="form-group">
					<label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('lock_id')->getAttribute('id') ?>">
						<?= $form->get('lock_id')->getLabel(); ?>
					</label>
					<div class="col-xs-6">
						<?= $this->formSelect($form->get('lock_id')) ?>
					</div>
				</div>

				<div class="form-group">
					<label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('show_apartment_entry_code')->getAttribute('id') ?>">
						<?= $this->info($form->get('show_apartment_entry_code')->getLabel(), 'Identifies whether to show apartment entry code in key instructions page or not.') ?>
					</label>
					<div class="col-xs-6 checkbox">
						<?= $this->formCheckbox($form->get('show_apartment_entry_code')) ?>
					</div>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="row">
					<label class="col-xs-6 col-sm-5 control-label">Key Instructions</label>
					<div class="col-xs-6 help-block">
						<a href="<?= $this->editKiDirectEntryTypeLink ?>" target="_blank" id="apartment">KI - Apartment Entry</a>
					</div>
					<?php if ($buildingDirectEntryTextline) { ?>
					<label class="col-xs-6 col-sm-5 control-label">Key Instructions</label>
					<div class="col-xs-6 help-block">
						<a href="/translation/view/p-<?= $buildingDirectEntryTextline->getId() ?>-en" target="_blank" id="apartment">KI - Apartment Entry (Building Section)</a>
					</div>
					<?php } ?>
					<div class="row">
						<label class="col-xs-6 col-sm-5 control-label">Apartment Rules</label>
						<div class="col-xs-6 help-block">
							<a href="/translation/view/p-<?= $this->apartmentUsage['id'] ?>-en" target="_blank" id="apartment_usage">Welcome note</a>
						</div>
					</div>
					<div class="row">
						<label class="col-xs-6 col-sm-5 control-label">Building Rules</label>
						<div class="col-xs-6 help-block">
							<a href="/translation/view/p-<?= $this->apartmentBuildingUsage['id'] ?>-en" target="_blank" id="apartment_group_usage">Welcome note</a>
						</div>
					</div>
					<div class="row">
						<label class="col-xs-6 col-sm-5 control-label">Facilities (Building)</label>
						<div class="col-xs-6 help-block">
							<a href="/translation/view/p-<?= $this->apartmentBuildingFacility['id'] ?>-en" target="_blank" id="apartment_group_facility">Welcome note</a>
						</div>
					</div>
					<div class="row">
						<label class="col-xs-6 col-sm-5 control-label">Building policy</label>
						<div class="col-xs-6 help-block">
							<a href="/translation/view/p-<?= $this->apartmentBuildingPolicy['id'] ?>-en" target="_blank" id="apartment_group_policy">Welcome note</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12 checkbox_container">
		<fieldset>
			<legend>Apartment Amenities</legend>
			<div class="form-group">
			<?php if($this->amenitiesList->count()) { ?>
				<?php foreach($this->amenitiesList as $amenity) { ?>
				<label class="col-sm-2 col-xs-5 control-label" for="amenity_<?= $amenity->getId(); ?>">
					<?= $amenity->getName() ?>
				</label>
				<label class="checkbox col-xs-1">
					<input type="hidden" name="amenities[<?= $amenity->getId(); ?>]" value="0">
					<input type="checkbox" name="amenities[<?= $amenity->getId(); ?>]" id="amenity_<?= $amenity->getId(); ?>"<?php if(in_array($amenity->getId(), $this->apartmentAmenities)) {?> checked="checked"<?php } ?> value="1">
				</label>
				<?php } ?>
			<?php } ?>
			</div>
		</fieldset>
	</div>
</div>

<br>

<?php if ($this->facilities) { ?>
<div class="row">
	<div class="col-sm-12 checkbox_container">
		<fieldset>
			<legend>Building Facilities</legend>
			<?php $iterator = 0; ?>
			<div class="form-group">
				<div class="col-sm-2 col-xs-6">
			<?php foreach($this->facilities as $facility) { ?>
				<?php if (!($iterator % 6) && $iterator != 0) { ?>
					</div><div class="col-sm-2 col-xs-6">
				<?php } ?>
				<?= $facility['name'] ?><br>
				<?php $iterator++; ?>
			<?php } ?>
				</div>
			</div>
		</fieldset>
	</div>
</div>
<?php } ?>

<br>


<div class="row">
	<div class="col-sm-12">
		<fieldset name="furniture">
			<legend>Furniture</legend>
		</fieldset>

		<div class="row">
			<div class="col-sm-6">
				<table class="table table-striped table-bordered table-condensed add-furniture-table">
					<thead>
						<tr>
							<th>Type</th>
							<th style="width: 65px">Count</th>
							<th style="width: 1px">Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php if ($furnitureList->count()) { ?>
							<?php foreach ($furnitureList as $furniture) { ?>
						<tr data-id="<?php echo $furniture['id']; ?>">
							<td><?php echo $furniture['title']; ?></td>
							<td class="text-center"><?php echo $furniture['count']; ?></td>
							<td><a href="#deleteFurnitureModalEx" data-url="<?php echo $this->url('apartment/details/delete-furniture', ['apartment_id' => $this->apartmentId, 'id' => $furniture['id']]); ?>" data-loading-text="Deleting..." class="btn btn-sm btn-danger delete-furniture" data-toggle="modal">Delete</a></td>
						</tr>
							<?php } ?>
						<?php } else { ?>
							<tr>
								<td colspan="3">No furniture</td>
							</tr>
						<?php } ?>
						<tr>
							<td>
								<select class="form-control input-sm furniture-type">
								<?php if ($furnitureTypes->count()) { ?>
									<option value="0">-- Please Select --</option>
									<?php foreach ($furnitureTypes as $furnitureType) { ?>
									<option value="<?php echo $furnitureType['id']; ?>"><?php echo $furnitureType['title']; ?></option>
									<?php } ?>
								<?php } ?>
								</select>
							</td>
							<td><input type="number" min="1" value="1" class="form-control input-sm furniture-count"></td>
							<td><a href="<?php echo $this->url('apartment/details/add-furniture', ['apartment_id' => $this->apartmentId]); ?>" class="btn btn-primary btn-block btn-sm add-furniture" data-loading-text="Adding..." data-apartment-id="<?php echo $this->apartmentId; ?>">Add</a></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div id="deleteFurnitureModal" class="modal fade" data-url="" data-id="">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header bg-danger text-danger">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
				</button>
				<h4 id="myModalLabel" class="modal-title">Remove Furniture<span id="delete_group"></span></h4>
			</div>
			<div class="modal-body">
				<p>Are you sure to remove furniture?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
				<a class="btn btn-danger" href="" id="deleteFurnitureButton">Remove</a>
			</div>
		</div>
	</div>
</div>

<div class="page-actions container">
	<div class="row text-right">
		<?= $this->formInput($form->get('save_button')) ?>
	</div>
</div>

<!-- Form close tag -->
<?= $this->form()->closeTag() ?>
