<?php
use Library\Constants\Objects;
use Library\Constants\Constants;

// Form object
$form = $this->form;

if($this->apartmentStatus == Objects::PRODUCT_STATUS_DISABLED) {
    $form->get('status')->setAttribute('disabled', 'disabled');
}

$form->prepare ();

?>
<!-- Controlled form display -->

<!-- Form opening tag -->
<?= $this->form()->openTag($form) ?>

<div class="row">
	<div class="col-sm-6">
		<fieldset>
			<legend>General</legend>
            <?= $this->formInput($form->get('id'))?>

            <div class="form-group">
                <label class="col-xs-5 col-sm-4 control-label" for="<?= $form->get('apartment_name')->getAttribute('id') ?>">
                    <?= $form->get('apartment_name')->getLabel() ?>
                    <?= $this->required() ?>
                </label>
                <div class="col-xs-6">
                    <?= $this->formInput($form->get('apartment_name')) ?>
                </div>
            </div>

            <?php if ($form->get('id')->getValue() == 0) { ?>
            <div class="form-group">
                <label class="col-xs-5 col-sm-4 control-label" for="<?= $form->get('building_id')->getAttribute('id') ?>">
                    <?= $form->get('building_id')->getLabel() ?>
                    <?= $this->required() ?>
                </label>
                <div class="col-xs-6">
                    <?= $this->formSelect($form->get('building_id')) ?>
                </div>
            </div>
            <div class="form-group soft-hide">
                <label class="col-xs-5 col-sm-4 control-label" for="<?= $form->get('building_section')->getAttribute('id') ?>">
                    <?= $form->get('building_section')->getLabel() ?>
                    <?= $this->required() ?>
                </label>
                <div class="col-xs-6">
                    <?= $this->formSelect($form->get('building_section')) ?>
                </div>
            </div>

            <?php } ?>

            <?php if ($form->get('id')->getValue() > 0) { ?>
            <div class="form-group">
                <label class="col-xs-5 col-sm-4 control-label" for="<?= $form->get('status')->getAttribute('id') ?>">
                    <?= $form->get('status')->getLabel() ?>
                    <?= $this->required() ?>
                </label>
                <div class="col-xs-6">
                    <?= $this->formSelect($form->get('status')) ?>
                </div>
            </div>
            <?php } ?>

            <?php if ($this->date_created) { ?>
            <div class="form-group">
                <label class="control-label col-xs-5 col-sm-4">Creation Date</label>
                <div class="help-block col-xs-6"><?= date(Constants::GLOBAL_DATE_FORMAT, strtotime($this->date_created)) ?></div>
            </div>
            <?php } ?>
        </fieldset>
        <fieldset>
            <legend>Policy</legend>
            <div class="form-group">
                <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('chekin_time')->getAttribute('id') ?>">
                    <?= $form->get('chekin_time')->getLabel() ?>
                    <?= $this->required() ?>
                </label>
                <div class="col-xs-6 col-sm-5 col-md-4">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <label class="glyphicon glyphicon-time" for="<?= $form->get('chekin_time')->getAttribute('id') ?>"></label>
                        </div>
                        <?= $this->formElement($form->get('chekin_time')) ?>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('chekout_time')->getAttribute('id') ?>">
                    <?= $form->get('chekout_time')->getLabel() ?>
                    <?= $this->required() ?>
                </label>
                <div class="col-xs-6 col-sm-5 col-md-4">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <label class="glyphicon glyphicon-time" for="<?= $form->get('chekout_time')->getAttribute('id') ?>"></label>
                        </div>
                        <?= $this->formElement($form->get('chekout_time')) ?>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Metrics</legend>
            <div class="form-group">
                <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('room_count')->getAttribute('id') ?>">
                    <?= $form->get('room_count')->getLabel() ?>
                    <?= $this->required(); ?>
                </label>
                <div class="col-xs-3 col-sm-2">
                    <?= $this->formInput($form->get('room_count')) ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('square_meters')->getAttribute('id') ?>">
                    <?= $form->get('square_meters')->getLabel() ?>
                </label>
                <div class="col-xs-3 col-sm-2">
                    <?= $this->formInput($form->get('square_meters')) ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('max_capacity')->getAttribute('id') ?>">
                    <?= $form->get('max_capacity')->getLabel() ?>
                    <?= $this->required() ?>
                </label>
                <div class="col-xs-3 col-sm-2">
                    <?= $this->formInput($form->get('max_capacity')) ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('bedrooms')->getAttribute('id') ?>">
                    <?= $form->get('bedrooms')->getLabel() ?>
                    <?= $this->required(); ?>
                </label>
                <div class="col-xs-3 col-sm-2">
                    <?= $this->formInput($form->get('bedrooms')) ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('bathrooms')->getAttribute('id') ?>">
                    <?= $form->get('bathrooms')->getLabel() ?>
                </label>
                <div class="col-xs-3 col-sm-2">
                    <?= $this->formInput($form->get('bathrooms')) ?>
                </div>
            </div>
        </fieldset>
    </div>
    <div class="col-sm-6">
        <fieldset>
			<legend>
                Description
                <?= $this->required() ?>
            </legend>
		</fieldset>

		<?= $this->formHidden($form->get('general_description_textline')) ?>

		<div class="form-group">
			<div class="col-xs-12">
				<?= $this->formTextarea($form->get('general_description')) ?>
			</div>
		</div>
    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
		<?= $this->formInput($form->get('save_button')) ?>
	</div>
</div>

<!-- Form close tag -->
<?= $this->form()->closeTag() ?>
