<?php
    use \DDD\Service\Document\Document as DocumentService;

	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->layout()->apartmentName . ' - Apartment Documents');

	$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/apartment/common.css');

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/apartment.document.js');

?>
<script>
    var aaData = <?= json_encode($this->aaData) ?>;
    var contactsData = <?= json_encode($this->contactsData) ?>;
</script>
<div class="row">
    <div class="col-sm-12">
        <hr>
        <?= $this->apartmentNavigation($this->apartmentId, $this->apartmentStatus, 'apartment/document')?>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <fieldset>
            <legend>Apartment Documents</legend>
            <?php if (count($this->aaData)) { ?>
            <table id="documents" class="table table-striped table-bordered table-condensed table-hover">
                <thead>
                <tr>
                    <th> Type </th>
                    <th class="hidden-xs"> Date </th>
                    <th class="hidden-xs"> Security </th>
                    <th class="hidden-xs"> Description </th>
                    <th> &nbsp; </th>
                    <th> &nbsp; </th>
                    <th> &nbsp; </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td><td class="hidden-xs"></td><td class="hidden-xs"></td><td class="hidden-xs"></td><td></td><td></td>
                </tr>
                </tbody>
            </table>
            <?php } else { ?>
                <div class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign"></span>
                    There are no documents linked to this apartment.
                </div>
            <?php } ?>
        </fieldset>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <fieldset>
            <legend>Contacts</legend>
            <?php if (count($this->contactsData)) { ?>
            <table id="datatable-contacts" class="table table-striped table-bordered table-condensed table-hover">
                <thead>
                <tr>
                    <th> Contact Name </th>
                    <th> Company </th>
                    <th> Mobile </th>
                    <th> Email </th>
                    <th> &nbsp; </th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <?php } else { ?>
            <div class="alert alert-info">
                <span class="glyphicon glyphicon-info-sign"></span>
                There are no contacts linked to this apartment.
            </div>
            <?php } ?>
        </fieldset>
    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <?php $addUrl = $this->url(
            'documents/edit_document',
            [],
            [
                'query' => [
                    'entity_id' => $this->apartmentId,
                    'entity_type' => DocumentService::ENTITY_TYPE_APARTMENT,
                    'entity_name' => $this->layout()->apartmentName
                ]
            ]
        ); ?>
        <a class="btn btn-primary pull-right" href="<?= $addUrl ?>" target="_blank">Add New Document</a>
    </div>
</div>
