<?php

$pageTitle = 'Order Management';
$this->headTitle($pageTitle)->setSeparator(' - ');
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    ['Order Management']
]);

$this->layout()->viewTitle = $pageTitle;

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/module/wh-orders/orders-main.js');

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/pages/wh-orders.css');
?>
<script>
    var byDefaultStatuses = [<?= implode(', ', $defaultStatuses) ?>];
</script>

<form id="order_search_filter" name="order_search_filter" method="post">
    <div class="row">
        <div class="col-sm-12 form-group">
            <input type="text" id="status_shipping" name="status_shipping" class="form-control" value="" placeholder="Status" multiple="" />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 form-group">
            <input type="text" id="name" name="name" class="form-control" value="" placeholder="Order Name">
        </div>
        <div class="col-sm-3 form-group">
            <select name="status" id="status" placeholder="Approval Status"  class="form-control">
                <?php foreach ($this->statuses as $key => $status) {?>
                    <option value="<?= $key ?>"><?= $status[0] ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="col-sm-3 form-group">
            <select name="users" placeholder="Created By" id="users"  class="form-control"<?= !$hasGlobalRole ? ' disabled' : ''; ?>>
                <?php foreach ($this->users as $user) { ?>
                    <option value="<?= $user->getId() ?>"<?= !$hasGlobalRole ? ' selected' : ''; ?>><?= $user->getFirstName() . ' ' . $user->getLastName() ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="col-sm-3 form-group">
            <input type="text" id="received-quantity" name="received_quantity" class="form-control" value="" placeholder="Received Quantity">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 form-group">
            <div class="input-group">
                <label class="input-group-addon" for="estimated_date_start">
                    <span class="glyphicon glyphicon-calendar"></span>
                </label>
                <input type="text" id="estimated_date_start" name="estimated_date_start" class="form-control" value="" placeholder="Delivery From">
            </div>
        </div>
        <div class="col-sm-3 form-group">
            <div class="input-group">
                <label class="input-group-addon" for="estimated_date_end">
                    <span class="glyphicon glyphicon-calendar"></span>
                </label>
                <input type="text" id="estimated_date_end" name="estimated_date_end" class="form-control" value="" placeholder="Delivery To">
            </div>
        </div>
        <div class="col-sm-3 form-group">
            <div class="input-group">
                <label class="input-group-addon" for="received-date">
                    <span class="glyphicon glyphicon-calendar"></span>
                </label>
                <input type="text" id="received-date" name="received_date" class="form-control" value="" placeholder="Received Date">
            </div>
        </div>
        <div class="col-sm-3 form-group">
            <div class="input-group">
                <label class="input-group-addon" for="order_date">
                    <span class="glyphicon glyphicon-calendar"></span>
                </label>
                <input type="text" id="order_date" name="order_date" class="form-control" value="" placeholder="Order Date">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 form-group">
            <input type="text" id="category" name="category" class="form-control" value="" placeholder="Category">
        </div>
        <div class="col-sm-3 form-group">
            <input type="text" id="location" name="location" class="form-control" value="" placeholder="Location">
        </div>
        <div class="col-sm-3 form-group">
            <input type="text" id="supplier" name="supplier" class="form-control" value="" placeholder="Supplier">
        </div>
        <div class="col-sm-3 form-group">
            <input type="text" id="stn" name="stn" class="form-control" value="" placeholder="Supplier Tracking Number">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10 form-group">
            <a href="javascript:void(0)" class="btn btn-block btn-primary" id="btn_search"><span class="glyphicon glyphicon-search"></span> Search</a>
        </div>
        <div class="col-sm-2 form-group">
            <a href="javascript:void(0)" class="btn btn-default btn-block filter-reset" id="btn_clear_form">Clear Filter</a>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable_orders" class="table table-striped table-bordered table-condensed table-hover hidden">
            <thead>
            <tr>
                <th>Status</th>
                <th>Shipping</th>
                <th>Name</th>
                <th>Category</th>
                <th>Location</th>
                <th>
                    <span data-content="Estimated Delivery Date From" data-container="body" data-toggle="popover" data-placement="top" class="commented-text" data-animation="true">EDDF</span>
                </th>
                <th>
                    <span data-content="Estimated Delivery Date To" data-container="body" data-toggle="popover" data-placement="top" class="commented-text" data-animation="true">EDDT</span>
                </th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <a href="<?php echo $this->url('orders/edit'); ?>" class="btn btn-primary state col-sm-2 col-xs-12 pull-right">Add New Order</a>
    </div>
</div>

<script>
    var GLOBAL_ORDERS_SEARCH_URL    = '<?php echo $this->url('orders/ajax-search-orders'); ?>';
    var GLOBAL_GET_LOCATIONS_URL    = '<?php echo $this->url('orders/ajax-get-order-locations'); ?>';
    var GLOBAL_GET_STATUSES_URL     = '<?php echo $this->url('orders/ajax-get-order-statuses'); ?>';
    var GLOBAL_GET_CATEGORIES_URL   = '<?php echo $this->url('orders/ajax-get-order-categories'); ?>';
    var GLOBAL_GET_SUPPLIERS_URL    = '<?php echo $this->url('orders/ajax-get-order-suppliers'); ?>';
    var GLOBAL_STATUS_SHIPPING_ORDER = JSON.parse('<?= $this->statusShipping?>');

</script>