<?php

$this->layout()->viewTitle = 'Payment System Providers';
$this->layout()->breadcrumb = $this->breadcrumb([
	['Finance'],
	[$this->layout()->viewTitle]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->InlineScript()
	->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
	->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/pages/psp.js');

$this->headLink()
	->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

$data = $this->data;

?>

<div id="status-switch">
    <div class="btn-group fn-buttons pull-right">
        <a href="#all" class="btn btn-sm btn-default" data-status="all">All</a>
        <a href="#active" class="btn btn-sm btn-default active" data-status="active">Active</a>
        <a href="#inactive" class="btn btn-sm btn-default" data-status="inactive">Inactive</a>
    </div>
    <input type="hidden" name="show_status" id="show-status" value="1" />
</div>

<div class="datatables-container">
    <table id="bank-accounts-table" class="table table-striped table-bordered table-condensed table-hover">
        <thead>
            <tr>
                <th>Status</th>
                <th>Short Name</th>
                <th>Name</th>
                <th>Money Account</th>
                <th>Batch</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<div class="page-actions container">
	<div class="row text-right">
		<a href="<?php echo $this->url('finance/default', ['controller' => 'psp', 'action' => 'edit']); ?>" class="btn btn-primary state pull-right col-sm-2 col-xs-12">Add PSP</a>
	</div>
</div>
