<?php

$form        = $this->officeForm;
$actionTitle = ($this->id ? $form->get('name')->getValue() : 'Add Office');

$this->headTitle()->setSeparator(' - ');
$this->headTitle($actionTitle . ' | Office');
$this->layout()->viewTitle = $actionTitle;
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    ['Our Offices', $this->url('backoffice/default', ['controller' => 'office', 'action' => 'index'])],
    [$actionTitle]
]);

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/validation/office.js')
    ->appendFile($this->basePath() . '/js/module/backoffice/office/edit.js');

if ($this->id && $this->roleCosts) {
    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/pages/office.edit.css');

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/module/backoffice/office/costs.js')
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js');
}

$form->prepare();
$form->setAttribute('action', $this->url('backoffice/default', ['controller' => 'office', 'action' => 'edit']));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'office_manage_table');
?>

<script>
    var GLOBAL_SAVE_DATA         = '<?= $this->url('backoffice/default', ['controller' => 'office', 'action' => 'ajaxsave'])?>';
    var GLOBAL_DELETE_OFFICE     = '<?= $this->url('backoffice/default', ['controller' => 'office', 'action' => 'ajaxdeleteoffice'])?>';
    var GLOBAL_DEACTIVATE_OFFICE = '<?= $this->url('backoffice/default', ['controller' => 'office', 'action' => 'ajaxdeactiveoffice'])?>';
    var GLOBAL_ACTIVATE_OFFICE   = '<?= $this->url('backoffice/default', ['controller' => 'office', 'action' => 'ajaxactiveoffice'])?>';
    var GLOBAL_CHECK_OFFICE_NAME = '<?= $this->url('backoffice/default', ['controller' => 'office', 'action' => 'ajaxcheckname'])?>';
    var GET_PROVINCE_LIST        = '<?= $this->url('backoffice/default', ['controller' => 'office', 'action' => 'getProvinceOptions'])?>';
    var GET_CITY_LIST            = '<?= $this->url('backoffice/default', ['controller' => 'office', 'action' => 'getCityOptions'])?>';
    var CHANGE_SECTION_STATUS    = '<?= $this->url('backoffice/default', ['controller' => 'office', 'action' => 'change-section-status']) ?>';

    <?php if ($this->id && $this->roleCosts) { ?>
    var GLOBAL_GET_OFFICE_COSTS_URL = '<?=
        $this->url('backoffice/default', ['controller' => 'office', 'action' => 'ajax-get-office-costs', 'id' => $this->id]) ?>';
    var GLOBAL_DOWNLOAD_OFFICE_COSTS_CSV_URL = '<?=
        $this->url('backoffice/default', ['controller' => 'office', 'action' => 'ajax-download-office-costs-csv', 'id' => $this->id]) ?>';
    <?php } ?>

</script>

<!-- TABS: START -->
<ul id="groupTabs" class="nav nav-tabs tabs-general" role="tablist">
    <li class="active">
        <a href="#administration" data-toggle="tab" role="tab" id="administration-tab">Administration</a>
    </li>
    <?php if ($this->id && $this->roleCosts) { ?>
    <li>
        <a href="#costs" data-toggle="tab" role="tab" id="costs-tab">Costs</a>
    </li>
    <?php } ?>
</ul>
<!-- TABS: END -->

<div class="tab-content">

<!-- ADMINISTRATION TAB: START -->
<div class="tab-pane fade active in" id="administration">
    <?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-sm-6">
            <fieldset name="general">
                <legend>Details</legend>

                <div class="form-group">
                    <label class="col-sm-4 control-label" for="name">Name <?= $this->required() ?></label>
                    <div class="col-sm-8">
                        <input type="hidden" name="userId" value="<?= $this->userId ?>">
                        <input type="hidden" id="office_id" name="office_id" value="<?= $this->id ?>">
                        <?php echo $this->formInput($form->get('disable')); ?>
                        <?php echo $this->formInput($form->get('name')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label" for="description">Description <?php echo $this->required(); ?></label>
                    <div class="col-sm-8">
                        <?php echo $this->formInput($form->get('description')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label" for="country_id">Country <?php echo $this->required(); ?></label>
                    <div class="col-sm-8">
                        <?php echo $this->formSelect($form->get('country_id')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label" for="province_id">Province <?php echo $this->required(); ?></label>
                    <div class="col-sm-8">
                        <?php echo $this->formSelect($form->get('province_id')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label" for="city_id">City <?php echo $this->required(); ?></label>
                    <div class="col-sm-8">
                        <?php echo $this->formSelect($form->get('city_id')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label" for="address">Address <?php echo $this->required(); ?></label>
                    <div class="col-sm-8">
                        <?php echo $this->formInput($form->get('address')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-4 control-label" for="phone">Phone</label>
                    <div class="col-sm-8">
                        <?php echo $this->formInput($form->get('phone')); ?>
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="col-sm-6">
            <fieldset name="general">
                <legend>Managers</legend>
                <div class="form-group">
                    <label class="col-sm-4 control-label" for="office_manager_id">Office Manager</label>
                    <div class="col-sm-8">
                        <?php echo $this->formSelect($form->get('office_manager_id')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label" for="it_manager_id">IT Manager</label>
                    <div class="col-sm-8">
                        <?php echo $this->formSelect($form->get('it_manager_id')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label" for="finance_manager_id">Finance Manager</label>
                    <div class="col-sm-8">
                        <?php echo $this->formSelect($form->get('finance_manager_id')); ?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <fieldset name="general">
                <legend>Staff</legend>
                <div class="form-group">
                    <div class="col-sm-12">
                        <?php echo $this->formSelect($form->get('staff')); ?>
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="col-sm-6">
            <fieldset name="general">
                <legend>Cost Sections</legend>
                    <form id="cost-form" name="cost-form">
                        <table class="table table-striped table-borderedctable-condensed" id="cost_section_table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th width="83px">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="section_tr">
                                <?php
                                if (!is_null($this->sections) && $this->sections->count()) {
                                    foreach ($this->sections as $i => $section) {

                                    if (!$section->getDisable()) {
                                ?>
                                    <td>
                                        <div class="input-prepend input-append form-group margin-0">
                                            <div class="col-sm-12">
                                                <input name="section[<?php echo $section->getId(); ?>]" type="text" class="form-control" id="sec_<?=$section->getId()?>" maxlength="50" value="<?=$section->getName() ?>">
                                            </div>
                                        </div>
                                    </td>
                                <?php } else { ?>
                                    <td>
                                        <div class="input-prepend input-append form-group margin-0">
                                            <div class="col-sm-12">
                                                <input name="section[<?php echo $section->getId(); ?>]" type="text" class="form-control" id="sec_<?=$section->getId()?>" maxlength="50" value="<?=$section->getName() ?>" readonly="readonly" />
                                            </div>
                                        </div>
                                    </td>
                                <?php } ?>

                                    <td width="83px">
                                        <?php
                                            $label = $section->getDisable() ? 'Enable' : 'Disable';
                                            $class = $section->getDisable() ? 'success' : 'danger';
                                        ?>
                                        <a href="javascript:void(0)" id="sec_<?=$section->getId()?>" class="btn btn-sm btn-<?php echo $class; ?> btn-block sectionDisableRow" data-id="<?=$section->getId()?>">
                                            <?php echo $label; ?>
                                        </a>
                                        <input value="0" type="hidden" name="disabled[]" class="disableRow">
                                    </td>
                                </tr>
                                <?php
                                    }
                                } else {
                                ?>
                                    <td>
                                        <div class="input-prepend input-append form-group margin-0">
                                            <div class="col-sm-12">
                                                <input name="section[]" type="text" class="form-control" id="sec_0" maxlength="50" value="">
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <a href="javascript:void(0)" class="btn btn-sm btn-danger btn-block sectionRemoveRow">Remove</a>
                                        <input value="0" type="hidden" name="disabled[]" class="removeRow"/>
                                    </td>
                                <?php } ?>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="1"></td>
                                <td>
                                    <a href="javascript:void(0)" class="btn btn-sm btn-primary" id="addMore">Add New</a>
                                    <span id="total_charge_span"></span>
                                    <input type="hidden" value="" name="charge_total" id="charge_total">
                                </td>
                            </tr>
                        </tfoot>
                    </table>
            </fieldset>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <fieldset>
                <legend>
                    Guest Entry and Communication
                </legend>
                <div class="col-sm-6">
                    <?php if ($this->receptionEntryTextline) { ?>
                    <div class="form-group textline-div">
                        <label class="col-sm-6 control-label" for="address">Key Instructions</label>
                        <div class="col-sm-6 help-block">
                            <a href=<?= "/translation/view/p-" . $this->receptionEntryTextline . "-en"?> target="_blank" id="apartment">Reception Entry</a>
                        </div>
                    </div>
                    <?php } ?>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 text-right">
                            <?= $this->formInput($form->get('map_attachment')) ?>
                            <input type="hidden" name="delete_attachment" id="delete_attachment" value="0">
                        </div>
                    </div>
                    <?php if($this->mapAttachment){?>
                        <div id="attachment-container" class="preview">
                            <button id="remove-attachment" value="<?=$this->url('backoffice/default', ['controller' => 'office', 'action' => 'remove-attachment', 'id' => $this->id])?>" class="hidden-file-input"></button>
                            <img style="max-width: 100%; max-height: 350px" src="<?=$this->mapAttachment?>">
                        </div>
                    <?php } ?>
                </div>
            </fieldset>
        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>
    <div class="page-actions container">
        <div class="row text-right">
            <?php echo $this->formButton($form->get('save_button')) ?>
            <?php
            if ($this->global && $this->id > 0) {
                if (!$this->officeSts) {
            ?>
            <a href="#deactivateModal" data-toggle="modal" class="btn btn-danger col-sm-2 col-xs-12 margin-left-10 pull-right">Deactivate Office</a>
            <?php } else { ?>
            <a href="#activateModal" data-toggle="modal" class="btn btn-success col-sm-2 col-xs-12 margin-left-10 pull-right">Activate Office</a>
            <?php
                }
            }
            ?>
        </div>
    </div>
</div>

<?php
if ($this->global) {
    if (!$this->officeSts) {
        ?>
        <div class="modal fade" id="deactivateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header bg-danger text-danger">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">
                            Deactivate Office <span id="deactivate_group"></span>
                        </h4>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure?</p>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal">Close</button>
                        <button class="btn btn-danger" id="office_deactivate_button">Deactivate</button>
                    </div>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div id="activateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header bg-success text-success">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title" id="myModalLabel2">Activate Office</h4>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure?</p>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                        <button class="btn btn-success" id="office_activate_button">Activate</button>
                    </div>
                </div>
            </div>
        </div>
<?php
    }
}
?>
<!-- ADMINISTRATION TAB: END -->

<!-- COSTS TAB: START -->
<?php if ($this->id && $this->roleCosts) { ?>
<div class="tab-pane fade" id="costs">
    <div class="row">
        <div class="col-sm-12">
            <table id="costs-datatable" class="table table-striped table-bordered table-condensed table-hover">
                <thead>
                <tr>
                    <th> TID </th>
                    <th> Category </th>
                    <th> Date </th>
                    <th> CUR </th>
                    <th class="text-center"> Amount </th>
                    <th> Purpose </th>
                    <th> &nbsp; </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td><td></td><td></td><td></td><td></td><td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="container page-actions">
        <div class="row text-right">
            <a href="javascript:void(0)" class="btn btn-info col-sm-2 col-xs-12 pull-left" id="btn_download_filtered_csv">
                <span class="glyphicon glyphicon-download"></span> Download
            </a>
        </div>
    </div>
</div>
<?php } ?>
<!-- COSTS TAB: END -->

</div>
<?php if ($form->has('download')) { ?>
<!-- Delete attachment modal -->
<div id="delete-attachment-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Delete Attachment</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <a class="btn btn-danger" id="rates_delete_button" href="<?= $downladButton->getOption('remove-url') ?>">Delete</a>
            </div>
        </div>
    </div>
</div>
<?php } ?>