<?php
	$this->layout()->viewTitle  = 'Our Offices';
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle($this->layout()->viewTitle);
	$this->layout()->breadcrumb = $this->breadcrumb([
		['Administration'],
		['Our Offices']
	]);

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/module/backoffice/office/main.js');
?>
<script>
    DATATABLE_AJAX_SOURCE = "<?= $ajaxSourceUrl ?>";
</script>
<div id="status-switch">
    <div class="btn-group fn-buttons pull-right">
        <a href="#all" class="btn btn-sm btn-default" data-status="all">All</a>
        <a href="#active" class="btn btn-sm btn-default active" data-status="active">Active</a>
        <a href="#inactive" class="btn btn-sm btn-default" data-status="inactive">Inactive</a>
    </div>
    <input type="hidden" name="show_status" id="show-status" value="1" />
</div>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable_office" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> ST </th>
                <th> Name </th>
                <th> Location </th>
                <th> Address </th>
                <th> Phone </th>
                <th> Staff </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<div class="container page-actions">
    <?php if ($this->global) { ?>

	<div class="row text-right">
	    <a href="<?= $this->url(
            'backoffice/default',
            [
                'controller' => 'office',
                'action'     => 'edit'
            ]
        )?>" class="btn btn-primary col-sm-2 col-xs-12
        pull-right">Add New Office</a>
	</div>
    <?php } ?>
</div>
