<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>CF - Download File Test</title>
    </head>
    <body>
        <div style="width: 100%; text-align: center">
            <p>
                The Ultimate Question of Life, the Universe, and Everything...
                <br>
                Why it is impossible download this file?
            </p>

            <p>
                <form method="get" action="/cloudflare/download">
                    <button type="submit">
                        try to download a file
                    </button>
                </form>
            </p>
        </div>
    </body>
</html>

<?php

exit;