<?php
use DDD\Service\WHOrder\Order;
use Library\Constants\Constants;

$title = $this->basicInfo->getCategoryName() . ', ' .
    $this->basicInfo->getLocationName() . ' (Consumable)';

$this->layout()->viewTitle = $title;
$this->layout()->breadcrumb = $this->breadcrumb([
	['Administration'],
	['Asset Management', $this->url('warehouse/asset', ['controller' => 'asset'])],
	[$title]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
	->appendFile($this->basePath() . '/js/warehouse/asset.consumable.edit.js');

$this->headLink()->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

?>
<script>
    var GLOBAL_SELECTED_LOCATION = '<?php echo $location;?>';
    var GLOBAL_LOCATION_LIST     = <?php echo json_encode($locationList);?>;
	var HISTORY_DATA             = <?php echo $this->historyData; ?>;
</script>

<!-- TABS: START -->
<ul class="nav nav-tabs tabs-general">
    <li class="active">
        <a href="#general" data-toggle="tab" aria-expanded="false" id="general-tab">General</a>
    </li>
    <li class="history-tab pull-right">
        <a href="#history" data-toggle="tab" aria-expanded="false" id="history-tab"><span class="glyphicon glyphicon-list-alt"></span> History</a>
    </li>
</ul>
<!-- TABS: END -->

<div class="tab-content">

<!-- GENERAL TAB: START-->
<div class="tab-pane fade active in" id="general">

<form action="" method="post" name="asset-form" class="form-horizontal" id="asset-form">
    <div class="row">
        <div class="col-sm-12">
            <?php echo $this->formHidden($form->get('id')); ?>
                <div class="form-group hide">
                    <label for="category-id" class="col-sm-2 control-label">Category <?php echo $this->required(); ?></label>
                    <div class="col-sm-4">
                        <?php echo $this->formSelect($form->get('category_id')); ?>
                    </div>
                </div>

            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Quantity <?php echo $this->required(); ?></label>
                <div class="col-sm-4">
                    <?= $this->formInput($form->get('quantity')) ?>
                </div>
            </div>

            <div class="form-group hide">
                <label for="location" class="col-sm-2 control-label">Locations <?php echo $this->required(); ?></label>
                <div class="col-sm-4">
                    <?php echo $this->formSelect($form->get('location')); ?>
                </div>
            </div>


            <div class="form-group">
                <label for="location" class="col-sm-2 control-label">Threshold <?php echo $this->required(); ?></label>
                <div class="col-sm-4">
                    <?php echo $this->formInput($form->get('threshold')); ?>
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Last Updated By</label>
                <div class="col-sm-4">
                    <?= $this->formInput($form->get('last_updated_by')) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="location" class="col-sm-2 control-label">Description</label>
                <div class="col-sm-4">
                    <?php echo $this->formTextarea($form->get('description')); ?>
                </div>
            </div>

        </div>

    </div>

     <div class="page-actions container">
        <div class="row text-right">
                    <button type="submit" class="btn btn-primary col-sm-2 col-xs-12 margin-left-10 pull-right">Save</button>
            <?php
            if ($hasOrderManagementGlobal) {
                $orderParams = [
                    'category_id' => $basicInfo->getCategoryId(),
                    'quantity' => $basicInfo->getQuantity(),
                    'location_id' => $basicInfo->getLocationEntityId(),
                    'location_type' => $basicInfo->getLocationEntityType(),
                ];
                ?>
                <a href="/orders/add?<?= http_build_query($orderParams) ?>" target="_blank" class="btn btn-primary col-sm-2 col-xs-12 margin-left-10 pull-right">Order More</a>

            <?php } ?>
        </div>
    </div>
</form>

<?php if ($ordersRelated->count()  ) { ?>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable-assets-consumable" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
				<th>Status</th>
                <th>Suppliers</th>
                <th>Order Date</th>
                <th>Estimated Delivery</th>
				<th>Quantity</th>
                <th> </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($ordersRelated as $order) {
				$estimateDelivery = '';
				if ($order->getEstimatedDateStart() && $order->getEstimatedDateEnd()) {
					$estimateDelivery = date(Constants::GLOBAL_DATE_FORMAT, strtotime($order->getEstimatedDateStart())) .
						' - ' . date(Constants::GLOBAL_DATE_FORMAT, strtotime($order->getEstimatedDateEnd()));
				}
                ?><tr>
					<td><?php echo Order::getStatusesShipping()[$order->getStatus()]?></td>
                    <td><?php echo $order->getSupplierName()?></td>
                    <td><?php echo date(Constants::GLOBAL_DATE_TIME_FORMAT, strtotime($order->getOrderDate()))?></td>
                    <td><?php echo $estimateDelivery?></td>
                    <td><?php echo $order->getQuantity()?></td>
					<td style="width: 1%;"><a href="/orders/edit/<?= $order->getId() ?>" target="_blank" class="btn btn-xs btn-primary"> View </a></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<?php } else { ?>
<h1>There are no related orders</h1>
<?php } ?>
</div>

<!-- HISTORY TAB: START-->
<div class="tab-pane fade" id="history">
    <div class="row" id="history-block">
        <div class="col-sm-12">
            <table id="datatable_history" class="table table-bordered table-condensed table-hover">
                <thead>
                <tr>
                    <th> Date </th>
                    <th> Employee </th>
                    <th> Message </th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div class="alert alert-success" id="history_clean">
                <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                There are no items to display
            </div>
        </div>
    </div>
</div>
<!-- HISTORY TAB: END-->

</div>
