<?php
use DDD\Service\Warehouse\Category;

$pageTitle = 'Asset Management';

$this->headTitle($pageTitle)->setSeparator(' - ');

$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    ['Asset Management'],
]);

$this->layout()->viewTitle = $pageTitle;

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/warehouse/asset.search.js');

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/pages/assets.css');
?>

<script>
    var GLOBAL_TYPE_CONSUMABLE = <?php echo Category::CATEGORY_TYPE_CONSUMABLE;?>;
    var GLOBAL_TYPE_VALUABLE   = <?php echo Category::CATEGORY_TYPE_VALUABLE;?>;
    var GLOBAL_MAP_OF_CATEGORY_TYPES   = <?php echo json_encode($mapOfCategoryTypes);?>;
</script>

<form id="assets-consumable-search-form" name="assets_consumable_search_form" class="" method="post">
    <div class="row">
        <div class="col-sm-3 form-group">
            <select name="category_id"  class="form-control selectize" id="category-id" required="required" style="width:100%!important">
                <option  value="0">-- Select a Category --</option>
                <option  value="-1">-- All Consumables --</option>
                <option  value="-2">-- All Valuables --</option>

                <?php foreach ($mapOfCategories as $key=>$value) { ?>
                    <option value="<?php echo $key;?>"><?php echo $value;?></option>
                <?php } ?>
            </select>
        </div>
        <div id="category-type-based-part"><p class="help-block">Please select one of categories to start filtering</p></div>
    </div>
    <div class="row">
        <div class="col-sm-10 form-group">
            <button class="btn btn-block btn-primary disabled" disabled="disabled" id="btn_search"><span class="glyphicon glyphicon-search"></span> Search</button>
        </div>
        <div class="col-sm-2 form-group">
            <button class="btn btn-default btn-block filter-reset" id="btn_clear_form">Clear Filter</button>
        </div>
    </div>
</form>

<hr>
<div id="datatable-part"></div>
<?php if ($this->hasGlobalRole) { ?>
<div class="page-actions container">
    <div class="row text-right">
        <a href="/warehouse/asset/add" class="btn btn-primary state col-sm-2 col-xs-12 pull-right" target="_blank">Add New Asset</a>
    </div>
</div>
<?php } ?>