<?php if ($this->pageCount): ?>
    <div class="col-xs-12">
		<ul class="pagination pull-right">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
	                    <i class="icon-angle-left"></i>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
	                    <i class="icon-angle-left"></i>
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
	                    <i class="icon-angle-right"></i>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
	                    <i class="icon-angle-right"></i>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>
