<div class="form-group">
    <input type="text" name="feedback-account" id="feedback-account" class="form-control" placeholder="Which accounts should be removed?" value="">
</div>

<div class="form-group">
    <input type="text" name="feedback-account-username" id="feedback-account-username" class="form-control" placeholder="Account username / email" value="">
</div>

<div class="form-group">
    <input type="text" name="feedback-duedate" id="feedback-duedate" class="form-control" placeholder="Due Date" value="">
</div>

<div class="form-group">
    <label for="feedback-google-drive-transfer-email">To which email should the Google Drive files be transferred to?</label>
    <input type="text" name="feedback-google-drive-transfer-email" id="feedback-google-drive-transfer-email" class="form-control" value="">
</div>
