<div class="form-group">
    <input type="text" name="feedback-account" id="feedback-account" class="form-control" placeholder="Which accounts should be unsuspended?" value="">
</div>

<div class="form-group">
    <input type="text" name="feedback-account-username" id="feedback-account-username" class="form-control" placeholder="Account username / email" value="">
</div>

<div class="form-group">
    <input type="text" name="feedback-duedate" id="feedback-duedate" class="form-control" placeholder="Due Date" value="">
</div>