<?php
use \Library\Constants\Constants;
use DDD\Service\Recruitment\Applicant as ApplicantService;

/** @var \DDD\Domain\Recruitment\Applicant\Applicant $applicantInfo */
$applicantInfo = $this->applicantInfo;
/** @var \Recruitment\Form\Applicant $form */
$form = $this->form;
$actionTitle = 'Applicant';
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Applicant');
$this->layout()->viewTitle = $applicantInfo->getFirstname() . ' ' . $applicantInfo->getLastname();
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    ['Applicant Management', $this->url('recruitment/applicants', ['controller' => 'applicants', 'action' => 'index'])],
    [$actionTitle]
]);
$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/plugins/jquery.datetimepicker.full.min.js')
    ->appendFile($this->basePath() . '/js/pages/applicants.edit.js')
    ->appendFile($this->basePath() . '/js/validation/requirement.applicants.js');

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/plugins/jquery.datetimepicker.css');

$form->prepare();
$form->setAttribute('action', $this->url('recruitment/applicants', ['controller' => 'applicants', 'action' => 'edit']));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'applicant_manage_table');

$readOnlyMode = true;

if ($this->isGlobManager || $this->isHiringManager || $this->isCountryManager) {
    $readOnlyMode = false;
}

?>
<script>
    var GLOBAL_SAVE_DATA        = '<?= $this->url('recruitment/applicants', ['controller' => 'applicants', 'action' => 'ajax-save'])?>';
    var GLOBAL_SAVE_INTERVIEW   = '<?= $this->url('recruitment/applicants', ['controller' => 'applicants', 'action' => 'ajax-save-interview'])?>';
    var GLOBAL_UPLOAD_CV        = '<?= $this->url('recruitment/applicants', ['controller' => 'applicants', 'action' => 'ajax-upload-cv'])?>';
    var COMMENT_AADAtA          = <?= $this->comment ?>;
    var INTERVIEW_MANAGER       = <?= $this->interviewManager ? 'true' : 'false' ?>;
    var GLOBAL_DOWNLOAD_URL     = '/recruitment/applicants/download-cv';
    var CHANGE_APPLICANT_STATUS = '/recruitment/applicants/change-applicant-status';
    var READ_ONLY_MODE          = <?= $readOnlyMode ? 'true' : 'false' ?>;

</script>
<div class="row">
    <div class="col-sm-12">
    <ul class="nav nav-tabs tabs-general" id="applicant-edit-nav">
        <li class="active"><a href="#applicant_details" data-toggle="tab" data-tab-name="applicant">Applicant</a></li>
        <li class="pull-right">
            <a href="#history_details" data-toggle="tab" data-tab-name="history">
                <span class="glyphicon glyphicon-list-alt"></span> History
            </a>
        </li>
    </ul>
<?php echo $this->form()->openTag($form); ?>
<input type="hidden" id="applicant_id" name="applicant_id" value="<?=$this->id; ?>">
    <div class="tab-content">
        <div class="tab-pane active form-horizontal" id="applicant_details">
            <div class="row">
                <div class="col-sm-6">
                    <fieldset name="details">
                    <legend>Details</legend>
                        <div class="form-group">
                            <label class="col-sm-4 col-xs-6 control-label">Name</label>
                            <div class="col-sm-8 col-xs-6 checkbox">
                                <?= $applicantInfo->getFirstname() . ' ' . $applicantInfo->getLastname()?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 col-xs-6 control-label">Status</label>
                            <div class="col-sm-8 col-lg-5 col-xs-6">
                                <select name="status" id="applicant-status" class="form-control"
                                    <?=($readOnlyMode) ? 'disabled="disabled"' : ''?>
                                >
                                    <?php foreach (ApplicantService::$status as $val => $text) { ?>
                                        <option value="<?= $val ?>"<?= ($val == $applicantInfo->getStatus()) ? ' selected' : '' ?>>
                                            <?= $text ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                             <label class="col-sm-4 col-xs-6 control-label">Email</label>
                             <div class="col-sm-8 col-xs-6 checkbox">
                                <?= '<a href="mailto:' . $applicantInfo->getEmail() .'" target="_blank">' . $applicantInfo->getEmail() .'</a>' ?>
                            </div>
                        </div>
                        <div class="form-group">
                             <label class="col-sm-4 col-xs-6 control-label">Position</label>
                             <div class="col-sm-8 col-xs-6 checkbox">
                                <?= $applicantInfo->getPosition() ?>,
                                <?= $applicantInfo->getJobCity() ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-4 col-xs-6 control-label">Phone</label>
                            <div class="col-sm-8 col-xs-6 checkbox">
                                <?= $applicantInfo->getPhone() ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 col-xs-6 control-label">Skype</label>
                            <div class="col-sm-8 col-xs-6 checkbox">
                                <?= ($applicantInfo->getSkype()) ? $applicantInfo->getSkype() : '-' ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 col-xs-6 control-label">Referred By</label>
                            <div class="col-sm-8 col-xs-6 checkbox">
                                <?= ($applicantInfo->getReferredBy()) ? $applicantInfo->getReferredBy() : '-' ?>
                            </div>
                        </div>
                         <div class="form-group">
                            <label class="col-sm-4 col-xs-6 control-label">Applied Date</label>
                            <div class="col-sm-8 col-xs-6 checkbox">
                                <?= date(Constants::GLOBAL_DATE_TIME_FORMAT, strtotime($applicantInfo->getDateApplied())) ?>
                            </div>
                        </div>
                        <?php if ($this->previousApplicants && $this->previousApplicants->count()) { ?>
                        <div class="form-group">
                            <label class="col-sm-4 col-xs-6 control-label">Previous</label>
                            <div class="col-sm-8 col-xs-6 checkbox">
                                <?php foreach ($this->previousApplicants as $row) { ?>
                                    <a href="<?=$this->url('recruitment/applicants', ['controller' => 'applicants', 'action' => 'edit', 'id' => $row->getId()])?>" target="_blank" class="btn-block">
                                        <?= $row->getPosition()?> <?=date(Constants::GLOBAL_DATE_FORMAT, strtotime($row->getDateApplied()))?>
                                    </a>
                                <?php } ?>
                            </div>
                        </div>
                        <?php } ?>
                </div>

                <div class="col-sm-6">
                    <fieldset>
                        <legend>Motivation</legend>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <?= ($applicantInfo->getMotivation()) ? $applicantInfo->getMotivation() : '-'  ?>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="row padding-bottom-40">
                <div class="col-sm-12">
                    <fieldset name="general">
                        <legend>Interview Management</legend>
                        <div id="datatable_interview_table">
                            <table id="datatable_interview" class="table table-striped table-bordered table-condensed table-hover">
                                <thead>
                                    <tr>
                                        <th> Interviewers </th>
                                        <th> From </th>
                                        <th> To </th>
                                        <th> Place </th>
                                        <th> Status </th>
                                        <th> Interviewer Id </th>
                                        <th>  </th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                        <div id="have_not_interview" style="display: none;">
                            <span class="text-muted">Do not have interview</span>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="history_details">
            <table id="datatable_history" class="table table-striped table-bordered table-condensed table-hover">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Author</th>
                        <th>Comment</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>

            <br>

            <div class="col-sm-12">
                <div class="form-group">
                    <fieldset>
                        <legend>Write a Comment</legend>
                    </fieldset>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label class="col-sm-2 control-label"><?= $form->get('comment')->getLabel() ?></label>
                    <div class="col-sm-10 checkbox">
                        <?= $this->formElement($form->get('comment')) ?>
                    </div>
                </div>
            </div>
            <?php if ($this->hasPeopleManagementHrRole) { ?>
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="col-sm-2 control-label"><?= $this->info($form->get('hr_only_comment')->getLabel(), 'Will make this comment only visible to Human Resources.') ?></label>
                        <div class="col-sm-10 checkbox">
                            <?= $this->formElement($form->get('hr_only_comment')) ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>

    <div class="page-actions container">

        <div class="row text-right">
            <div class="col-sm-6 pull-left text-left">
                <div class="form-group col-sm-6">
                    <?=$this->formElement($form->get('attachment_doc'))?>
                    <input type="hidden" name="validAttachment" id="validAttachment" value="0" /><br />
                </div>
                <div class="form-group col-sm-6">
                    <div class='well well-sm margin-1 pull-left file-name soft-hide text-muted'></div>
                </div>
            </div>

            <?php if ($interviewManager) { ?>
            <button type="button" id="add-interview-btn" class="btn btn-primary col-sm-2 col-xs-12 margin-left-10 pull-right state applicant-tab-btn">Add Interview</button>
            <?php echo $this->formButton($form->get('upload-cv-btn'));?>

            <?php } ?>
            <?php echo $this->formButton($form->get('save_button'));
            if ($form->has('download')) {
                $downladButton = $form->get('download');

                echo '<div class="btn-group">';
                echo $this->formButton($form->get('download'));
                echo '<button type="button" name="remove_attachment" id="remove-attachment" data-toggle="modal" data-target="#delete-attachment-modal"  class="btn btn-info pull-left state hidden-file-input"><span class="' . $downladButton->getOption('remove-icon') . '"></span></button>';
                echo '</div>';
            }
            ?>
        </div>
    </div>

    <?php echo $this->form()->closeTag() ?>

</div>

<?php if ($form->has('download')) { ?>
<div id="delete-attachment-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Delete Resume</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <a class="btn btn-danger" id="rates_delete_button" href="<?= $downladButton->getOption('remove-url') ?>">Delete</a>
            </div>
        </div>
    </div>
</div>
<?php } ?>

<div class="modal fade" id="interview-edit-modal" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary text-primary">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">
                    <span id="interview-modal-action">Add</span> interview
                </h4>
            </div>
            <form class="form-horizontal">
            <div class="modal-body">
                <div class="form-group row">
                    <label class="col-sm-4 control-label">
                        Participants <?= $this->required() ?>
                    </label>
                    <div class="col-sm-6">
                        <input type="hidden" name="id" value="0" id="interview_id">
                        <input type="hidden" name="applicant_id" value="<?= $id ?>">
                        <select name="participants[]" class="participants-selectize" multiple>
                            <?php /** @var \DDD\Domain\User\User $user */ ?>
                            <?php foreach ($this->users as $user) { ?>
                                <option value="<?= $user->getId() ?>"><?= $user->getFirstName() . ' ' . $user->getLastName() ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 control-label">
                        From <?= $this->required() ?>
                    </label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <input type="text" class="form-control datetimepicker"  name="from" id="from" data-date-format="MMM DD, YYYY HH:mm">
                            <label class="input-group-addon" for="from"><span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 control-label">
                        To
                    </label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <input type="text" class="form-control datetimepicker"  name="to" id="to" data-date-format="MMM DD, YYYY HH:mm">
                            <label class="input-group-addon" for="to"><span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 control-label">
                        <?= $this->info('Place', 'e.g. Spirit Soft') ?> <?= $this->required() ?>
                    </label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control"  name="place" id="place">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="save-interview">Save</button>
            </div>
            </form>
        </div>
    </div>
</div>

<?php if ($form->has('download')) { ?>
<div id="delete-attachment-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Delete Resume</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <a class="btn btn-danger" id="rates_delete_button" href="<?= $downladButton->getOption('remove-url') ?>">Delete</a>
            </div>
        </div>
    </div>
</div>
<?php } ?>
