<?php

use DDD\Service\Recruitment\Applicant;

$this->layout()->viewTitle = 'Applicants Management';
$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    [$this->layout()->viewTitle]
]);

$searchForm = $this->searchForm;
?>

<script>
    var DATATABLE_AJAX_SOURCE = '<?= $ajaxSourceUrl ?>';

    $(document).click(function(event) {
        var target = $(event.target);

        if (!target.hasClass("daterangepicker") && !target.hasClass("form-control") && target.parents(".daterangepicker").length == 0 && target.parents(".calendar-date").length == 0) {
          $(".daterangepicker").hide();
        }
    });
</script>

<?php
    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/applicants.js');

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

    $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
?>


<div id="status-switch">
    <div class="btn-group fn-buttons pull-right">
        <a href="#all" class="btn btn-sm btn-default" data-status="<?= Applicant::APPLICANT_STATUS_ALL ?>">All</a>
        <?php foreach(Applicant::$status as $val => $text) { ?>
            <a href="#<?= strtolower($text) ?>" class="btn btn-sm btn-default" data-status="<?= $val ?>"><?= $text ?></a>
        <?php } ?>
    </div>
    <input type="hidden" name="show_status" id="show-status" value="1" />
</div>

<div class="row" id="applicant">
    <div class="col-sm-12">
        <table id="datatable_applicants" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> Status </th>
                <th> Name </th>
                <th> Position </th>
                <th> City </th>
                <th> Applied </th>
                <th> Phone </th>
                <th> Email </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
