<?php

use Library\Utility\Helper;
$this->headTitle($this->textline(1367));
$this->headMeta($this->textline(1466), 'description');
$this->headMeta('company', 'og:type');
$this->headMeta($this->textline(1615), 'og:title');
$this->headMeta($this->serverUrl() . '/s/logo/round_right.jpg', 'og:image');
$this->headMeta($this->textline(1466), 'og:description');
$this->headMeta($this->serverUrl(), 'og:url');
$this->headMeta($this->textline(1611), 'og:site_name');
$this->inlineScript()
	->appendFile($this->basePath() . '/js/vendor/bootstrap-datepicker.min.js')
	->appendFile($this->basePath() . '/js/home.search.js')
	->appendFile($this->basePath() . '/js/home.page.js');

$this->headLink()
	->prependStylesheet($this->basePath() . '/css/search.css');

$this->headLink([
    'rel' => 'canonical',
    'href' => $this->serverUrl()]);

?>
	</div>
</div>
<div class="container-fluid index-search grid-sep" data-background="<?=$this->basePath()?>/img/web/bg_cover<?=rand(1,6)?>.jpg">
	<div class="container hidden-xs">
		<div class="row">
			<div class="col-sm-12">
                <div class="index-box">
                    <h1 class="text-center"><?=$this->textline(1382)?></h1>
                    <h3 class="text-center"><?=$this->textline(1441)?></h3>
                </div>
			</div>
		</div>
	</div>

	<div class="search-container">
		<div class="container">
			<div class="row custom-margin">
				<div class="col-sm-12">
					<h2 class="text-center"><?=$this->textline(1383)?></h2>

                    <form class="row search search-general" data-today="<?=$this->options['current_date']?>" action="<?=$this->options['action']?>">
						<div class="col-sm-3 grid-sep col search-location">
                            <input type="hidden" class="destionation" name="city" value="">
							<div class="dropdown input-destination">
								<input data-toggle="dropdown" type="text" class="form-control input-lg" value="" placeholder="<?=$this->textline(1221)?>" readonly>
								<ul class="dropdown-menu col-xs-12" role="menu">
									<?php foreach ($this->options['cities'] as $key => $city) { ?>
                                    <li>
                                        <a href="javascript:void(0)" data-url="<?=$city['city_url']?>" data-currentdate="<?=$city['current_date']?>" data-max-capacity="<?=$city['max_capacity']?>">
                                            <span style="font-size:1.2em"><?=$this->cityname($city['id'])?></span>
                                            <small class="text-muted"><?=$city['short_name']?></small>
                                        </a>
                                    </li>
									<?php } ?>
								</ul>
							</div>
							<i class="glyphicon glyphicon-map-marker text-muted"></i>
						</div>
						<div class="input-daterange">
							<div class="col-xs-6 col-sm-3 col-md-2 grid-sep col search-date padding-right-6-media-max-768px">
                                <input type="text" name="arrival" class="form-control input-lg text-left" value="" placeholder="<?=$this->textline(1222)?>" readonly>
								<i class="glyphicon glyphicon-calendar text-muted"></i>
							</div>
							<div class="col-xs-6 col-sm-3 col-md-2 grid-sep col search-date padding-left-6-media-max-768px">
								<input type="text" name="departure" class="form-control input-lg text-left" value="" placeholder="<?=$this->textline(1223)?>" readonly>
								<i class="glyphicon glyphicon-calendar text-muted"></i>
							</div>
						</div>
						<div class="col-sm-1 grid-sep col search-guest">
                            <select class="form-control input-lg capacity" name="guest">
								<?php foreach ($this->options['guest'] as $key => $guest) {
                                    /**
                                     * @todo replace 2 with constant
                                     */
                                    ?>
									<option value="<?=$key?>" <?php if (2 == $key) echo 'selected="selected"'?>><?=$guest?></option>
								<?php } ?>
							</select>
						</div>
						<div class="col-sm-2 grid-sep col search-button">
							<input type="button" class="btn-block searchButton go-search height46" value="<?=$this->textline(1322)?>"> <!-- btn btn-lg btn-block btn-warning-->
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row gi-services">
		<div class="col-md-12 col-lg-8">
			<div class="row">
				<div class="col-sm-12 grid-sep">
					<h2><?=$this->textline(1384)?></h2>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12 col-sm-6 padding-bottom-15">
					<div class="row">
						<div class="col-xs-2">
							<div class="bg-primary text-center icon-circle">
								<i class="icon icon-food"></i>
							</div>
						</div>
						<div class="col-xs-8">
							<h3 class="margin-top-0"><?=$this->textline(1385)?></h3>
							<p class="text-muted"><?=$this->textline(1386)?></p>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 padding-bottom-15">
					<div class="row">
						<div class="col-xs-2">
							<div class="bg-primary text-center icon-circle">
								<i class="icon icon-user-md"></i>
							</div>
						</div>
						<div class="col-xs-8">
							<h3 class="margin-top-0"><?=$this->textline(1387)?></h3>
							<p class="text-muted"><?=$this->textline(1388)?></p>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12 col-sm-6 padding-bottom-15">
					<div class="row">
						<div class="col-xs-2">
							<div class="bg-primary text-center icon-circle">
								<i class="icon icon-extra-space"></i>
							</div>
						</div>
						<div class="col-xs-8">
							<h3 class="margin-top-0"><?=$this->textline(1389)?></h3>
							<p class="text-muted"><?=$this->textline(1390)?></p>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 padding-bottom-15">
					<div class="row">
						<div class="col-xs-2">
							<div class="bg-primary text-center icon-circle">
								<i class="icon icon-signal"></i>
							</div>
						</div>
						<div class="col-xs-8">
							<h3 class="margin-top-0"><?=$this->textline(1391)?></h3>
							<p class="text-muted"><?=$this->textline(1392)?></p>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12 col-sm-6 padding-bottom-15">
					<div class="row">
						<div class="col-xs-2">
							<div class="bg-primary text-center icon-circle">
								<i class="icon icon-privacy"></i>
							</div>
						</div>
						<div class="col-xs-8">
							<h3 class="margin-top-0"><?=$this->textline(1393)?></h3>
							<p class="text-muted"><?=$this->textline(1394)?></p>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 padding-bottom-15">
					<div class="row">
						<div class="col-xs-2">
							<div class="bg-primary text-center icon-circle">
								<i class="icon icon-home"></i>
							</div>
						</div>
						<div class="col-xs-8">
							<h3 class="margin-top-0"><?=$this->textline(1395)?></h3>
							<p class="text-muted"><?=$this->textline(1396)?></p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-lg-4 visible-lg-block">
			<div class="margin-top-homepic">
				<img alt="Furnished Apartment for Your Stay" src="<?php echo $this->basePath(); ?>/img/web/round_right.jpg" class="img-circle-100">
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-7 col-md-8 grid-sep">
			<h2 class="grid-sep"><?=$this->textline(1397)?></h2>
            <?=$this->textline(1398)?>
        </div>

		<div class="col-sm-5 col-md-4 grid-sep">
			<h2 class="grid-sep"><?=$this->textline(1399)?></h2>
			<div class="panel-group top-destinations" id="accordion">
				<?php $i = 0;
                      foreach ($this->options['locations'] as $key => $city) { ?>
				<div class="panel panel-default">
					<div class="panel-heading">
						<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne_<?=$city['city_id']?>">
							<h4 class="panel-title"><?=$this->cityname($city['city_id']) . ', ' . $this->countryname($city['country_id']);?></h4>
						</a>
					</div>
					<div id="collapseOne_<?=$city['city_id']?>" class="panel-collapse collapse<?php if (!$i++) echo ' in'; ?>">
						<a href="<?=$city['url']?>">
							<div class="panel-body" data-background="<?php echo $city['img']; ?>">
								<div class="row">
		                            <div class="col-xs-offset-1 col-xs-11">
		                                <p><strong><?=$city['capacity']?></strong> <?=$this->textline(1400)?></p>
		                                <p><strong><?=$city['spent_nights']?></strong> <?=$this->textline(1401)?></p>
		                                <p><strong><?=$city['sold_future_nights']?></strong> <?=$this->textline(1402)?></p>
		                            </div>
								</div>
							</div>
						</a>
					</div>
				</div>
                <?php } ?>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid grid-sep home-route">
	<div class="container">
		<div class="row grid-sep">
			<div class="col-sm-12">
				<h2 class="text-center"><?=$this->textline(1404)?></h2>
			</div>
		</div>

		<div class="row home-simple-pic">
			<div class="col-sm-3 text-center homepage-icons" >
				<h3><?=$this->textline(1405)?></h3>
				<div class="grid-sep">
					<img alt="Pack and Get Going" src="<?php echo $this->basePath(); ?>/img/web/simple-ginosi-184.jpg">
				</div>
				<p class="text-muted"><?=$this->textline(1406)?></p>
			</div>

			<div class="col-sm-3 text-center homepage-icons" >
				<h3><?=$this->textline(1407)?></h3>
				<div class="grid-sep">
					<img alt="Feel Local and see the city as your own" src="<?php echo $this->basePath(); ?>/img/web/simple-arrival-184.jpg" >
				</div>
				<p class="text-muted"><?=$this->textline(1408)?></p>
			</div>

			<div class="col-sm-3 text-center homepage-icons" >
				<h3><?=$this->textline(1409)?></h3>
				<div class="grid-sep">
					<img alt="Sleep in comfort of a home" src="<?php echo $this->basePath(); ?>/img/web/simple-stay-184.jpg" >
				</div>
				<p class="text-muted"><?=$this->textline(1410)?></p>
			</div>

			<div class="col-sm-3 text-center homepage-icons" >
				<h3><?=$this->textline(1411)?></h3>
				<div class="grid-sep">
					<img alt="Explore and discover new Ginosi locations" src="<?php echo $this->basePath(); ?>/img/web/simple-lasting-184.jpg" >
				</div>
				<p class="text-muted"><?=$this->textline(1412)?></p>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-12 text-center">
            <div class="alert alert-info blue-box">
                <h2 class="margin-0"><?=Helper::evaluateTextline($this->textline(1414),['{{PEOPLE_COUNT}}' => $this->options['peopleCount'], '{{COUNTRIES_COUNT}}' => $this->options['countryCount']])?></h2>
            </div>
		</div>
	</div>

	<div class="row hidden-xs">
        <div class="col-sm-12 grid-sep">
            <h2><?=$this->textline(1415)?></h2>
        </div>
        <?php foreach ($this->options['bloges'] as $blog){?>
		<div class="col-sm-6">
			<div class="row">
				<div class="col-sm-4 col-md-3 col-lg-2">
					<div class="thumbnail">
                        <h3 class="bg-primary text-center calendar-heading"><?=date('M', strtotime($blog['date']))?></h3>
						<h2 class="text-primary text-center calendar-heading"><?=date('d', strtotime($blog['date']))?></h2>
					</div>
				</div>
				<div class="col-sm-8 col-md-9 col-lg-10">
                    <h4 class="text-primary margin-top-0"><a href="/blog/<?=$blog["slug"]?>"><?=$blog['title']?></a></h4>
					<p class="text-muted"><?=Library\Utility\Helper::getBlogShort($blog['content'], 100, false)?></p>
				</div>
			</div>
		</div>
        <?php } ?>
	</div>
</div>

<div class="container-fluid footer-search hidden-xs">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 text-center">
				<h2><?=$this->textline(1416)?></h2>
			</div>
		</div>

		<form class="row grid-sep search search-general" data-today="<?=$this->options['current_date']?>" action="<?=$this->options['action']?>">
			<div class="col-sm-3 col-md-offset-1 grid-sep col search-location">
                <input type="hidden" class="destionation" name="city">
				<div class="dropdown input-destination">
                    <input data-toggle="dropdown" type="text" class="form-control input-lg" value="" readonly placeholder="<?=$this->textline(1221)?>">
					<ul class="dropdown-menu" role="menu">
						<?php foreach ($this->options['cities'] as $key => $city) { ?>
							<li>
                                <a href="javascript:void(0)" data-url="<?=$city['city_url']?>" data-currentdate="<?=$city['current_date']?>" data-max-capacity="<?=$city['max_capacity']?>">
                                    <span style="font-size:1.2em"><?=$this->cityname($city['id'])?></span>
                                    <small class="text-muted"><?=$city['short_name']?></small>
                                </a>
                            </li>
						<?php } ?>
					</ul>
				</div>
				<i class="glyphicon glyphicon-map-marker text-muted"></i>
			</div>
			<div class="input-daterange">
				<div class="col-xs-6 col-sm-3 col-md-2 grid-sep col search-date">
                    <input type="text" name="arrival" class="form-control input-lg text-left start" readonly value="" placeholder="<?=$this->textline(1222)?>">
					<i class="glyphicon glyphicon-calendar text-muted"></i>
				</div>
				<div class="col-xs-6 col-sm-3 col-md-2 grid-sep col search-date">
                    <input type="text" name="departure" class="form-control input-lg text-left end" readonly value="" placeholder="<?=$this->textline(1223)?>">
					<i class="glyphicon glyphicon-calendar text-muted"></i>
				</div>
			</div>
			<div class="col-sm-1 grid-sep col search-guest">
                <select class="form-control input-lg capacity" name="guest">
					<?php foreach ($this->options['guest'] as $key => $guest) { ?>
						<option value="<?=$key?>" <?php if (2 == $key) echo 'selected="selected"'?>><?=$guest?></option>
					<?php } ?>
				</select>
			</div>
			<div class="col-sm-2 grid-sep col search-button">
				<input type="button" class="btn-lg btn-block go-search searchButton" value="<?=$this->textline(1322)?>">
			</div>
		</form>
<!-- div's close in layout: because we close 2 div in top of this view file
    </div>
</div>
-->
