<?php
$this->headTitle($this->apartelName . ' | Apartel')->setSeparator(' - ');

$layoutViewModel = $this->viewModel()->getRoot();

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/apartel/common.css');

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/apartel/history.js');


$apartelId = $layoutViewModel->apartelId;
?>

<script>
    var historyAaData = <?= json_encode($this->historyAaData) ?>;
</script>

<?php echo $this->apartelHeader($apartelId); ?>

<div class="row">
    <div class="col-sm-12">
        <?php if (count($this->historyAaData)) { ?>
        <table id="history" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> Date </th>
                <th> User </th>
                <th> Message </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <?php } else { ?>
        <div class="alert alert-info">
            <span class="glyphicon glyphicon-info-sign"></span>
            <strong><?= $this->apartelName ?></strong> history data is empty.
        </div>
        <?php } ?>
    </div>
</div>
