<?php

$this->headTitle($this->textline(1448))->setSeparator(' - ');

?>

<div class="col-xs-12">
	<p><?=$this->textline(1424)?></p>
    <h1>404</h1>
	<p><?=$this->textline(1425)?></p>
	<p><a href="//<?= \Library\Constants\DomainConstants::WS_DOMAIN_NAME . $this->url('home')?>"><?=$this->textline(1428)?></a></p>
	<p><a href="//<?= \Library\Constants\DomainConstants::WS_DOMAIN_NAME . $this->url('about-us')?>"><?=$this->textline(1427)?></a></p>
	<p><a href="//<?= \Library\Constants\DomainConstants::WS_DOMAIN_NAME . $this->url('location')?>"><?=$this->textline(1320)?></a></p>
    <p><a href="//<?= \Library\Constants\DomainConstants::WS_DOMAIN_NAME . $this->url('jobs')?>"><?=$this->textline(1368)?></a></p>
    <p><a href="//<?= \Library\Constants\DomainConstants::WS_DOMAIN_NAME . $this->url('contact-us')?>"><?=$this->textline(1426)?></a></p>
</div>