<?php
/**
 * @var \DDD\Domain\Contacts\Card $card
 */

use Library\Constants\Constants;


if (!isset($card) || empty($card)) {
    return null;
}
?>

<div class="bs-callout bs-callout-primary">
    <h4>
        <span>
            <?php echo $card['name']; ?>
        </span>
    </h4>
    <table class="table table-condensed">


        <?php if (!empty($card['city_name'])) { ?>
        <tr>
            <td>City</td>
            <td>
                <span>
                    <?php echo $card['city_name']; ?>
                </span>
            </td>
        </tr>
        <?php } ?>

        <?php if (!empty($card['address'])) { ?>
            <tr>
                <td>Address</td>
                <td>
                    <span>
                        <?php echo $card['address']; ?>
                    </span>
                </td>
            </tr>
        <?php } ?>


        <?php if (!empty($card['phone'])) { ?>
            <tr>
                <td>Phone</td>
                <td>
                    <span>
                        <?php if (($userInternalNumber && $card['phone'])) { ?>
                        <a href="<?php echo sprintf(Constants::GINOSI_CALL_CENTER_URL, $userInternalNumber, filter_var($card['phone'], FILTER_SANITIZE_NUMBER_INT)); ?>" target="_blank">
                            <?php echo $card['phone']; ?>
                        </a>
                        <?php } else { ?>
                            <span><?php echo $card['phone']; ?></span>
                        <?php } ?>
                    </span>
                </td>
            </tr>
        <?php } ?>



    </table>

    <?php if ($hasGlobal) { ?>
    <div class="text-right">
        <a
            class="btn btn-primary btn-sm hand-task-button"
            href="/office/edit/<?php echo $card['id']?>"
            target="_blank">
            Edit
        </a>
    </div>
    <?php } ?>
</div>
