<?php
use Library\Constants\Constants;
?>
<fieldset>
    <legend>Guest should pay additional</legend>
</fieldset>
<table class="table table-bordered table-condensed">
    <thead>
    <tr>
        <th>Type</th>
        <th>Rate Name</th>
        <th class="hidden-xs">Date</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $total = 0;
    foreach ($this->data as $row) {
        $total += $row['price'];
        ?>
        <tr class="chargedView">
            <td><?=$row['type']?></td>
            <td class="text-center"><?=(isset($row['rate_name']) && $row['rate_name']) ? $row['rate_name'] : ''?></td>
            <td class="text-center"><?=date(Constants::GLOBAL_DATE_FORMAT, strtotime($row['date']))?></td>
            <td class="text-right"><?=$row['price']?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3"><strong>Total</strong></td>
        <td class="text-right"><strong><?= number_format($total, 2, '.', '') ?></strong></td>
    </tr>
    </tfoot>
</table>
