<?php

$current = $this->id ? $this->form->get('name')->getValue() : 'Add Review Codes';
$this->layout()->viewTitle = $current;
$this->layout()->breadcrumb = $this->breadcrumb([
	['Apartment'],
	['Review Codes', $this->url('apartment_review_category', ['controller' => 'apartment-review-category'])],
	[$current]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->InlineScript()
	->appendFile($this->basePath() . '/js/validation/apartment.review.category.js')
    ->appendFile($this->basePath() . '/js/pages/apartment.review.category.edit.js');
?>

<script>
    var URL_DELETE_REVIEW_CATEGORY = '<?= $this->url('apartment_review_category', ['controller' => 'apartment-review-category', 'action' => 'delete']) ?>';
</script>

<?php echo $this->form()->openTag($this->form); ?>
<div class="row">
    <div class="col-sm-12">
        <fieldset name="General">
            <legend>General</legend>
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Name <?php echo $this->required(); ?></label>
                <div class="col-sm-5">
                    <input type="hidden" id="review_category_id" name="review_category_id" value="<?= $this->id ?>">
                    <?= $this->formInput($form->get('name')) ?>
                </div>
            </div>
            <div class="form-group">
                <label for="money_account_id" class="col-sm-2 control-label">Type <?php echo $this->required(); ?></label>
                <div class="col-sm-2">
                    <?php echo $this->formSelect($form->get('type')); ?>
                </div>
            </div>
        </fieldset>
    </div>
</div>
 <div class="page-actions container">
    <div class="row text-right">
        <?= $this->formInput($form->get('save')) ?>
        <a href="#modal_remove_review_category" data-toggle="modal" class="btn btn-danger col-sm-2 col-xs-12 margin-left-10 pull-right">Delete</a>
    </div>
</div>
<?=$this->form()->closeTag(); ?>

<div class="modal fade" id="modal_remove_review_category" tabindex="-1" role="dialog" aria-labelledby="RemoveReviewCategory" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">
                    Remove Review Category <span id="deactivate_group"></span>
                </h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to remove this review category and all the reviews in this category?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
                <button class="btn btn-danger" id="btn_remove_apartment_review_category">Delete</button>
            </div>
        </div>
    </div>
</div>
