<?php

$this->layout()->viewTitle = 'Review Codes';
$this->layout()->breadcrumb = $this->breadcrumb([
	['Apartment'],
	[$this->layout()->viewTitle]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->InlineScript()
	->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
	->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/pages/review.codes.js');

$this->headLink()
	->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

$data = $this->data;
?>

<script>
    aaData = <?= $aaData ?>;
</script>
<div class="datatables-container">
    <table id="apartment-review-category-table" class="table table-striped table-bordered table-condensed table-hover">
        <thead>
        <tr>
            <th> Name </th>
            <th> Type </th>
            <th> &nbsp; </th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<div class="page-actions container">
	<div class="row text-right">
		<a href="<?php echo $this->url('apartment_review_category', ['controller' => 'apartment-review-category', 'action' => 'edit']); ?>" class="btn btn-primary state col-sm-2 col-xs-12 pull-right">Add New Code</a>
	</div>
</div>
