<?php
    use \DDD\Service\Document\Document as DocumentService;

    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Building Documents');

    $this->layout()->breadcrumb = $this->breadcrumb([
        ['Apartment'],
        ['Apartment Groups', $this->url('backoffice/default', ['controller' => 'apartment-group', 'action' => 'index'])],
        [$apartmentGroupName],
        ['Documents']
    ]);
    $this->layout()->viewTitle = $apartmentGroupName;

	$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/apartment/common.css');

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/apartment-group.document.js');
?>
<script>
    var aaData = <?= $aaData ?>;
</script>
<div class="row">
    <div class="col-sm-12">
        <hr>
        <?= $this->apartmentGroupNavigation($this->apartmentGroupId, 'apartment-group/document')?>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <table id="documents" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> Type </th>
                <th class="hidden-xs"> Date </th>
                <th class="hidden-xs"> Security </th>
                <th class="hidden-xs"> Description </th>
                <th> &nbsp; </th>
                <th> &nbsp; </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td></td><td class="hidden-xs"></td><td class="hidden-xs"></td><td class="hidden-xs"></td><td></td><td></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <?php $addUrl = $this->url(
            'documents/edit_document',
            [],
            [
                'query' => [
                    'entity_id' => $this->apartmentGroupId,
                    'entity_type' => DocumentService::ENTITY_TYPE_APARTMENT_GROUP,
                    'entity_name' => $apartmentGroupName
                ]
            ]
        ); ?>
        <a class="btn btn-primary pull-right" href="<?= $addUrl ?>" target="_blank">Add New Document</a>
    </div>
</div>
