<?php
use DDD\Service\Warehouse\Category as CategoryService;
use DDD\Service\Warehouse\Category;
if ($this->id) {
    $pageTitle = $this->form->get('name')->getValue() .
        ' (' . CategoryService::$categoryTypes[$this->form->get('type')->getValue()] . ')';
} else {
    $pageTitle = 'Add Category';
}
$this->layout()->viewTitle = $pageTitle;
$this->layout()->breadcrumb = $this->breadcrumb([
	['Administration'],
	['Assets Category', $this->url('warehouse/category', ['controller' => 'category'])],
	[$pageTitle]
]);
$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/warehouse/category.edit.js');

$this->headLink()->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')

?>
<script>
    var CATEGORY_TYPE = <?= $this->categoryType ?>;
    var CATEGORY_ID = <?= $this->id ?>;
    var CHECK_UNIQUE_URL = '<?= $this->url('warehouse/category', ['controller' => 'category', 'action' => 'check-alias-uniqueness'])?>';
    var MERGE_CATEGORY = '<?= $this->url('warehouse/category', ['controller' => 'category', 'action' => 'merge-category'])?>';
    var HISTORY_DATA   = <?= $this->historyData; ?>;

</script>

<!-- TABS: START -->
<ul class="nav nav-tabs tabs-general">
    <li class="active">
        <a href="#general" data-toggle="tab" aria-expanded="false" id="general-tab">General</a>
    </li>
    <li class="history-tab pull-right">
        <a href="#history" data-toggle="tab" aria-expanded="false" id="history-tab"><span class="glyphicon glyphicon-list-alt"></span> History</a>
    </li>
</ul>
<!-- TABS: END -->

<div class="tab-content">

<div class="tab-pane fade active in" id="general">

<?php echo $this->form()->openTag($this->form); ?>
<div class="row">
    <div class="col-sm-12">
        <fieldset name="General">
            <legend>General</legend>
            <div class="form-group">
                <label for="name" class="col-sm-1 control-label">Name <?php echo $this->required(); ?></label>
                <div class="col-sm-5">
                    <?= $this->formInput($form->get('name')) ?>
                </div>
            </div>
            <div class="form-group <?= $this->id ? ' hide' : '' ?>">
                <label for="type" class="col-sm-1 control-label">Type <?php echo $this->required(); ?></label>
                <div class="col-sm-5">
					<?= $this->formSelect($form->get('type')) ?>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <fieldset name="general">
            <legend>Aliases</legend>
            <table class="table table-striped table-bordered table-condensed" id="aliases_table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th class="w1"></th>
                </tr>
                <tr>
                    <td>
                        <?= $this->formInput($form->get('aliases[]')) ?>
                    </td>
                    <td class="text-center">
                        <a href="javascript:void(0)" class="btn btn-sm btn-primary" id="add-aliases">Add</a>
                        <input type="hidden" value="" name="charge_total" id="charge_total">
                    </td>
                </tr>
                </thead>
                <tbody>
                <?php if (($this->aliases) && $this->aliases->count()) { ?>
                    <?php foreach ($this->aliases as $alias) { ?>
                <tr class="alias_tr">
                    <td>
                        <div class="input-prepend input-append form-group margin-0">
                            <div class="col-sm-12">
                                <input name="aliases[<?= $alias['id']; ?>]" type="text" class="form-control" id="alias_<?=$alias['id']?>" maxlength="50" value="<?=$alias['name'] ?>" data-id="<?=$alias['id']?>" onblur="checkAliasUniqueness(this)">
                            </div>
                        </div>
                    </td>

                    <td width="83px">
                        <a href="javascript:void(0)" id="alias_<?=$alias['id']?>" class="btn btn-sm btn-danger btn-block aliasRemoveRow" data-id="<?=$alias['id']?>">
                            Delete
                        </a>
                    </td>
                </tr>
                <?php
                    }
                }?>
                </tbody>

            </table>
        </fieldset>
    </div>
    <div class="col-sm-6">
        <fieldset name="SKU" class="sku-container">
            <legend>SKU</legend>
            <?php if ($this->id) { ?>
                <table class="table table-condensed table-bordered">
                    <thead>
                        <tr>
                            <th>Identifier</th>
                            <th class="w1">&nbsp;</th>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->formInput($form->get('sku_names[]')) ?>
                            </td>
                            <td class="text-center">
                                <a class="btn btn-sm btn-primary add-sku">Add</a>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                    <?php if (count($this->skuList)) { ?>

                        <?php foreach ($this->skuList as $sku) { ?>
                        <tr>
                            <td><?php echo $sku; ?></td>
                            <th>&nbsp;</th>
                        </tr>
                        <?php } ?>

                    <?php } ?>
                    </tbody>
                </table>
            <?php } ?>
        </fieldset>
    </div>
</div>
 <div class="page-actions container">
    <div class="row text-right">
        <?= $this->formInput($form->get('save')) ?>

        <?php if ($this->id) { ?>
            <a href="#modal_merge_category" data-toggle="modal" class="btn btn-success col-sm-2 col-xs-12 margin-left-10 pull-right">Merge Category</a>
        <?php } ?>
        <?php if ($this->id) {?>
            <?php if (!$this->status) {?>
                <a href="#modal_deactivate_category" data-toggle="modal" class="btn btn-danger col-sm-2 col-xs-12 margin-left-10 pull-right">Deactivate Category</a>
                <?php } else { ?>
                <a href="#modal_activate_category" data-toggle="modal" class="btn btn-success col-sm-2 col-xs-12 margin-left-10 pull-right">Activate Category</a>
            <?php } ?>
        <?php } ?>
    </div>
</div>
<?=$this->form()->closeTag(); ?>

</div>

<!-- GENERAL TAB: END-->

<!-- HISTORY TAB: START-->
<div class="tab-pane fade" id="history">
    <div class="row" id="history-block">
        <div class="col-sm-12">
            <table id="datatable_history" class="table table-bordered table-condensed table-hover">
                <thead>
                <tr>
                    <th> Date </th>
                    <th> Employee </th>
                    <th> Message </th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div class="alert alert-success" id="history_clean">
                <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                There are no items to display
            </div>
        </div>
    </div>
</div>
<!-- HISTORY TAB: END-->
</div>
<!-- MODAL SECTION -->
<?php if ($this->id) {?>
    <div class="modal fade" id="modal_deactivate_category" tabindex="-1" role="dialog" aria-labelledby="deactivateCategory" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger text-danger">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">
                        Deactivate Category <span id="deactivate_group"></span>
                    </h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to deactivate this category?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">Close</button>
                    <a class="btn btn-danger" href="/warehouse/category/change-status/<?=$this->id?>/<?=Category::CATEGORY_STATUS_INACTIVE?>">Deactivate</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal_activate_category" tabindex="-1" role="dialog" aria-labelledby="activateCategory" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-success text-success">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">
                        Activate Category <span id="deactivate_group"></span>
                    </h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to activate this category?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">Close</button>
                    <a class="btn btn-success" href="/warehouse/category/change-status/<?=$this->id?>/<?=Category::CATEGORY_STATUS_ACTIVE?>">Activate</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal_merge_category" tabindex="-1" role="dialog" aria-labelledby="activateCategory" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-info text-info">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel"> Merge Category <span id="merge"></span>
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group">
                            <p class="col-sm-12">All existing assets and orders under this category will be moved to new category.</p>

                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 checkbox">Select Category</label>
                            <div class="form-group col-sm-9">
                                <select class="form-control" id="merge_category_id">
                                    <?php
                                    /**
                                     * @var \DDD\Domain\Booking\ChargeAuthorization\ChargeAuthorizationCreditCard $ccForAuthorization
                                     */
                                    ?>
                                    <?php foreach ($this->categories as $category) { ?>
                                        <option value="<?= $category->getId() ?>"><?= $category->getName()?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-success" href="javascript:void(0)" id="merge-category">Yes</a>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
<?php if ($this->error) { ?>
<script>
    $(function() {
        notification({
            status: 'error',
            msg: '<?php echo addslashes($this->error); ?>'
        });
    })
</script>
<?php } ?>
