<?php

$this->layout()->viewTitle = 'Asset Categories';
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    [$this->layout()->viewTitle]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/warehouse/category.js');

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');
?>

<script>
    DATATABLE_AJAX_SOURCE = "<?= $this->ajaxSourceUrl ?>";
</script>
<div id="status-switch">
    <div class="btn-group fn-buttons pull-right">
        <a href="#all" class="btn btn-sm btn-default" data-status="all">All</a>
        <a href="#active" class="btn btn-sm btn-default active" data-status="active">Active</a>
        <a href="#inactive" class="btn btn-sm btn-default" data-status="inactive">Inactive</a>
    </div>
    <input type="hidden" name="show_status" id="show-status" value="1" />
</div>

<div class="row">
    <div class="col-sm-12">

        <table id="asset-category-table" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> Status </th>
                <th> Name </th>
                <th> Type </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <a href="<?= $this->url('warehouse/category', ['controller' => 'category', 'action' => 'edit']); ?>" class="btn btn-primary state col-sm-2 col-xs-12 pull-right">Add New Category</a>
    </div>
</div>
