<?php use Library\Constants\Objects;?>
<div class="row">
    <div class="col-sm-12">
        <fieldset name="ota_connection">
            <legend>OTA Connection</legend>
        </fieldset>

        <form id="ota-form" action="<?=$this->formAction?>">
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Date Listed</th>
                        <th>Date Edited</th>
                        <th>Reference</th>
                        <th>URL</th>
                        <th colspan="2">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->OTAList as $ota) { ?>
                    <tr>
                        <td><?=$ota['partner_name']?></td>
                        <td><?=Objects::getOTADistributionStatusList()[$ota['status']]?></td>
                        <td><?=($ota['date_listed']) ? date('j M, Y', strtotime($ota['date_listed'])) : ''?></td>
                        <td><?=($ota['date_edited'] ? date('j M, Y H:i', strtotime($ota['date_edited'])) : '<span class="label label-warning">Not Edited</span>')?></td>
                        <td><?=$ota['reference']?></td>
                        <td>
                            <?php if ($ota['url']) { ?>
                            <a href="<?=$ota['url']?>" class="btn btn-xs btn-info" target="_blank">View <i class="glyphicon glyphicon-share"></i></a>
                            <?php } ?>
                        </td>
                        <td class="w1"><a href="#" data-url="<?php echo $this->url('apartel/connection/remove-ota', ['apartel_id' => $this->apartelId, 'ota_id' => $ota['id']]); ?>" data-loading-text="Deleting..." class="btn btn-xs btn-danger delete-ota" data-toggle="modal">Delete</a></td>
                        <td class="w1"><a href="#" data-url="<?php echo $this->url('apartel/connection/ajax-check-ota', ['apartel_id' => $this->apartelId, 'ota_id' => $ota['partner_id']]); ?>" data-loading-text="Checking..." class="btn btn-xs btn-primary check-button">Check</a></td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <td>
                            <div class="form-group margin-0">
                            <select class="form-control input-md" name="ota_name">
                            <?php if ($this->partnerList->count()) { ?>
                                <option value="0">-- Please Select --</option>
                                <?php foreach ($this->partnerList as $ota) { ?>
                                <option value="<?=$ota['gid']?>"><?=$ota['partner_name']?></option>
                                <?php } ?>
                            <?php } ?>
                            </select>
                            </div>
                        </td>
                        <td>
                            <div class="form-group margin-0">
                            <select class="form-control input-md" name="ota_status" disabled>
                                <option value="1">Pending</option>
                            </select>
                            </div>
                        </td>
                        <td></td>
                        <td></td>
                        <td><div class="form-group margin-0"><input type="text" class="form-control input-md"  name="ota_ref"></div></td>
                        <td><div class="form-group margin-0"><input type="text" class="form-control input-md"  name="ota_url" placeholder="http://example.com"></div></td>
                        <td colspan="2"><a href="javascript:void(0)" class="btn btn-primary btn-block btn-md" id="ota-button" data-loading-text="Adding...">Add</a></td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>