<style>
	.form-horizontal .controls {
		margin-left: 0px;
	}
</style>
<?php
	//Form object
	$form           = $this->form;
	$formType       = $this->formType;

	$form->prepare();

?>
<!-- Controlled form display -->

<!-- Form opening tag -->
<?= $this->form()->openTag($form); ?>

<!-- First Row -->
<div class="row">
	<div class="col-sm-2 col-md-2">
        <div class="form-group">
            <?= $this->formSelect($form->get('category')) ?>
        </div>
	</div>

	<div class="col-sm-2 col-md-2 product_type">
		<div class="form-group">
			<?= $this->formSelect($form->get('product_type')) ?>
		</div>
	</div>


	<div class="col-sm-8 col-md-6 srch_txt">
        <div class="form-group">
            <?= $this->formInput($form->get('srch_txt')) ?>
        </div>
	</div>

	<div class="col-sm-10 col-md-3 description">
		<div class="form-group">
			<?= $this->formInput($form->get('description')) ?>
		</div>
	</div>

    <div class="col-sm-2 col-md-1">
        <div class="form-group">
            <?= $this->formInput($form->get('id_translation')) ?>
        </div>
	</div>
</div>
<div class="row">

	<div class="col-sm-12 un_type">
        <div class="form-group">
            <?= $this->formSelect($form->get('un_type')) ?>
        </div>
	</div>


</div>
<!-- Form close tag -->
<?= $this->form()->closeTag() ?>
