<?php
use Library\Constants\DomainConstants;

$form = $this->jobForm;
$actionTitle = ($this->id ? $form->get('title')->getValue() : 'Add Job');
$this->headTitle()->setSeparator(' - ');
$this->headTitle($actionTitle . ' | Job');
$this->layout()->viewTitle = $actionTitle;
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    ['Job Management', $this->url('recruitment/jobs', ['controller' => 'jobs', 'action' => 'index'])],
    [$actionTitle]
]);

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/pages/jobs.edit.js')
    ->appendFile($this->basePath() . '/js/validation/jobs.js');

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/pages/job-edit.css');


$form->prepare();
$form->setAttribute('action', $this->url('recruitment/jobs', ['controller' => 'jobs', 'action' => 'edit']));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'job_manage_table');

$jobUrl = '//'.DomainConstants::WS_DOMAIN_NAME.'/jobs/'.$this->jobSlug;

$environment = getenv('APPLICATION_ENV') ?: 'production';
echo "<script src='{$this->basePath()}/js/vendor/tinymce/tinymce.min.js' type='text/javascript'></script>";
?>

<script>
    var GLOBAL_SAVE_DATA  = '<?= $this->url('recruitment/jobs', ['controller' => 'jobs', 'action' => 'ajaxsave'])?>';
    var GET_PROVINCE_LIST = '<?= $this->url('recruitment/jobs', ['controller' => 'jobs', 'action' => 'get-province-options'])?>';
    var GET_CITY_LIST     = '<?= $this->url('recruitment/jobs', ['controller' => 'jobs', 'action' => 'get-city-options'])?>';
    var DELETE_JOB        = '<?= $this->url('recruitment/jobs', ['controller' => 'jobs', 'action' => 'ajax-delete-job'])?>';
    var ACT_DEACT_JOB     = '<?= $this->url('recruitment/jobs', ['controller' => 'jobs', 'action' => 'ajax-change-activation-job'])?>';


</script>

<div class="row">
    <div class="col-sm-12" id="job-badges">
        <?php if ($this->jobStatus == '2') { ?>
        <a href="<?php echo $jobUrl; ?>" class="action-item label label-info pull-right margin-left-5" target="_blank">
            See on website <span class="glyphicon glyphicon-share"></span>
        </a>
        <?php } ?>
    </div>
    <div class="col-sm-12">
    <?php echo $this->form()->openTag($form); ?>

    <div class="tab-content">
         <div class="tab-pane active" id="job_details">
            <div class="row">
                <div class="col-sm-6">
                    <fieldset name="general">
                        <legend>General</legend>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="name">Title <?php echo $this->required(); ?></label>
                            <div class="col-sm-8">
                                <input type="hidden" name="userId" value="<?=$this->userId; ?>">
                                <input type="hidden" id="job_id" name="job_id" value="<?=$this->id; ?>">
                                <?php echo $this->formInput($form->get('title')); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="name">Subtitle </label>
                            <div class="col-sm-8">
                                <?php echo $this->formInput($form->get('subtitle')); ?>
                            </div>
                        </div>
                         <div class="form-group">
                            <label class="col-sm-4 control-label"
                            for="city_id">Status</label>
                            <div class="col-sm-8">

                                <?php
                                if ($this->isGlobManager || $this->isHiringTeam) {
                                    echo $this->formSelect($form->get('status'));
                                } else {
                                    echo '<i>' . $this->jobOption . '</i>'; ?>
                                    <input id="status" class="form-control" type="hidden" value="<?= $this->jobStatus ?>" name="status">
                                <?php } ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="hiring_manager_id">Hiring Manager <?php echo $this->required(); ?></label>
                            <?php
                            if ($this->isGlobManager || $this->isCountryMngr || $this->isHiringTeam) { ?>
                                <div class="col-sm-8">
                                    <?php echo $this->formSelect($form->get('hiring_manager_id')); ?>
                                </div>

                            <?php } else { ?>
                                <div class="col-sm-8 checkbox">
                                    <?php echo '<i>' . $this->hiringMng . '</i>'; ?>
                                    <input id="hiring_manager_id" class="form-control" type="hidden" value="<?= $this->hiringMngId ?>" name="hiring_manager_id">

                                </div>
                            <?php } ?>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="hiring_team_id">Hiring Team</label>
                            <?php
                            if ($this->isGlobManager || $this->isCountryMngr || $this->isHiringTeam) { ?>
                                <div class="col-sm-8">
                                    <?php echo $this->formSelect($form->get('hiring_team_id')); ?>
                                </div>

                            <?php } else { ?>
                                <div class="col-sm-8 checkbox">
                                    <?php echo '<i>' . $this->hiringTeam . '</i>'; ?>
                                    <input id="hiring_team_id" class="form-control" type="hidden" value="<?= $this->hiringTeamId ?>" name="hiring_team_id">

                                </div>
                            <?php } ?>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="hiring_manager_id">Department <?php echo $this->required(); ?></label>
                            <div class="col-sm-8">
                                <?php echo $this->formSelect($form->get('department_id')); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="meta_description">
                                <?= $this->info('Short Description', 'This short description is for SEO purposes and will be used when sharing the announcement in FB.<br /><span class="text-muted">Max: 70 characters.</span>') ?>
                                <?= $this->required(); ?>
                            </label>
                            <div class="col-sm-8 checkbox">
                                <?=$this->formTextarea($form->get('meta_description'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="cv_required">
                                <?= $this->info('CV Required', 'Shows whether CV is required for applicants or not.') ?>
                            </label>
                            <div class="col-sm-8 checkbox">
                                <?=$this->formCheckbox($form->get('cv_required'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="cv_required">
                                <?= $this->info('Notify Manager', 'If checked the hiring manager will receive a notification on applying to this job') ?>
                            </label>
                            <div class="col-sm-8 checkbox">
                                <?=$this->formCheckbox($form->get('notify_manager'))?>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div class="col-sm-6">
                    <fieldset name="location">
                        <legend>Date &amp; Location</legend>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="start_date">Start Date <?php echo $this->required(); ?></label>
                            <div class="col-sm-8">
                                <div class="input-group">
                                    <?=$this->formInput($form->get('start_date'))?>
                                    <label class="input-group-addon" for="start_date">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"
                            for="country_id">Country <?php echo $this->required(); ?></label>
                            <div class="col-sm-8">
                                <?php echo $this->formSelect($form->get('country_id')); ?>
                            </div>
                        </div>

                       <div class="form-group">
                            <label class="col-sm-4 control-label"
                            for="province_id">Province <?php echo $this->required();?></label>
                            <div class="col-sm-8">
                                <?php echo $this->formSelect($form->get('province_id')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-4 control-label"
                            for="city_id">City <?php echo $this->required(); ?></label>
                            <div class="col-sm-8">
                                <?php echo $this->formSelect($form->get('city_id')); ?>
                            </div>
                        </div>

                    </fieldset>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <fieldset name="description">
                        <legend>Description <?php echo $this->required(); ?></legend>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="description"></label>
                            <div class="col-sm-10 controls">
                                <?php echo $this->formElement($form->get('description')); ?>
                                <div class="help-block"></div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset name="requirements">
                        <legend>Requirements</legend>
                        <div class="form-group">

                            <label class="col-sm-2 control-label" for="requirements"></label>
                            <div class="col-sm-10 controls">
                                <?php echo $this->formElement($form->get('requirements')); ?>
                                <div class="help-block"></div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>

    <?php echo $this->form()->closeTag() ?>
    <div class="page-actions container">
        <div class="row text-right">
            <?php echo $this->formButton($form->get('save_button'));
            if ($this->id > 0) {
                if ($this->jobStatus != 3) { ?>
            <a href="#deactivateModal" data-toggle="modal" class="btn btn-danger col-sm-2 col-xs-12 margin-left-10 pull-right">Deactivate Job</a>
            <?php } else { ?>

            <a href="#activateModal" data-toggle="modal" class="btn btn-success col-sm-2 col-xs-12 margin-left-10 pull-right">Activate Job</a>
            <?php }
            }?>

        </div>
    </div>

    <?php
    if ($this->jobStatus == 3) { ?>
       <div id="activateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header bg-success text-success">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel2">Activate Job</h4>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure?</p>
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-default" data-dismiss="modal" href="javascript:void(0)">Cancel</a>
                        <a class="btn btn-success" id="job_activate_button" data-job-status="<?= $this->jobStatus ?>" href="javascript:void(0)">Activate</a>
                    </div>
                </div>
            </div>
        </div>

<?php } else { ?>
    <div class="modal fade" id="deactivateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger text-danger">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Deactivate Job <span id="deactivate_group"></span></h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure?</p>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default" data-dismiss="modal" href="javascript:void(0)">Cancel</a>
                    <a class="btn btn-danger" id="job_deactivate_button" data-job-status="<?= $this->jobStatus ?>" href="javascript:void(0)">Deactivate</a>
                </div>
            </div>
        </div>
    </div>
<?php } ?>