<table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr>
        <td colspan="3" style="font-size: 20px; padding-bottom: 10px;">
            <?= $this->textline(1242) ?>
        </td>
    </tr>
    <?php foreach ($this->chargesList as $charge) {
            if ($charge['type'] != 'total') { ?>
                <tr valign="top" style="font-weight:bold; color: #757575;font-size: 14px;<?= $charge['type'] == 'discount' ? ' color: #E57373;' : '' ?>">
                    <td colspan="2">
                        <?= $charge['label'] ?>
                    </td>
                    <td align="right" style="padding: 5px 0;">
                        <?= $charge['price_view'] ?>
                    </td>
                </tr>
    <?php   } else { ?>
                <tr valign="top" style="font-size: 14px;">
                    <td colspan="2" style="padding: 5px 0 20px; border-top: 1px solid #EEEEEE">
                        <?= $charge['label'] ?>
                    </td>
                    <td align="right" style="padding: 5px 0 20px; font-weight: bold; border-top: 1px solid #EEEEEE">
                        <?= $charge['price_view'] ?>
                    </td>
                </tr>
    <?php   }
    } ?>
</table>