<?php
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('Languages');

    $this->layout()->breadcrumb = '<li>Administration</li>
                                   <li class="active">Languages</li>';
    $this->layout()->viewTitle  = 'Languages';

    $this->InlineScript()->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/language.js');

    $this->headLink()->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');
?>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable_languages" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> ID </th>
                <th> ISO 639-1 Code </th>
                <th> English Name </th>
                <th> Status </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
