<?php
	$this->headTitle()->setSeparator(' - ');
	$this->layout()->viewTitle = 'Occupancy Statistics';
	$this->headTitle($this->layout()->viewTitle);
	$this->headTitle()->setSeparator(' - ');
	$this->layout()->breadcrumb = $this->breadcrumb([
		['Apartment'],
		['Occupancy Statistics'],
	]);

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/apartment/occupancy.statistics.css');

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/plugins/fnReloadAjax.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/apartment/occupancy.statistics.js');
?>
<script>
    var STATISTICS_PAGE_ADDRESS            = '<?= $this->url('apartments', ['controller' => 'occupancy-statistics', 'action' => 'statistics'])?>';
    var DATATABLE_AJAX_SOURCE              = '<?= $ajaxSourceUrl ?>';
    var FIND_COUNTRY_CITY_AUTOCOMPLETE_URL = '<?= $this->url('apartments', ['controller' => 'apartment', 'action' => 'search-country-city'], ['query' => ['justCity' => true]])?>';
    var BUILDING_NAME_AUTOCOMPLETE_URL     = '<?= $this->url('apartments', ['controller' => 'apartment', 'action' => 'get-autocomplete-building'])?>';
</script>
<div class="row">
    <div class="col-sm-12">
        <?= $this->formOutput ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <a href="javascript:void(0)" class="btn btn-medium btn-block btn-primary" id="btn_search_statistics"><i class="icon-search icon-white"></i> Search</a>
    </div>
</div>
<div class="clearfix"></div>
<hr>

<div class="row hidden" id="datatable_statistics_container">
    <div class="col-sm-12">
        <table id="datatable_statistics_info" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Building</th>
                    <th>City</th>
                    <th style="width: 40px;">PAX</th>
                    <th>Bedrooms</th>
                    <th style="width: 100px;">Unsold (10d)</th>
                    <th class='month1'></th>
                    <th class='month2'></th>
                    <th class='month3'></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
