<?php
$current = 'PO Item search';
$this->layout()->viewTitle = $current;
$this->layout()->breadcrumb = $this->breadcrumb([
	['Finance'],
	[$current]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);


$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/pages/expense.item.search.js');
$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/pages/expense.item.search.css');
?>

<div class="row">
    <div class="col-sm-12">
        <?= $this->form()->openTag($form); ?>
        <div class="row">
            <div class="col-sm-3 padding-bottom-5">
                <?= $this->formSelect($form->get('item-search-supplier')) ?>
            </div>

            <div class="col-sm-3 padding-bottom-5">
                <?= $this->formInput($form->get('item-search-reference')) ?>
            </div>

            <div class="col-sm-3 padding-bottom-5">
                <?= $this->formSelect($form->get('item-search-cost-center')) ?>
            </div>

            <div class="col-sm-3 padding-bottom-5">
                <?= $this->formSelect($form->get('item-search-category')) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3 padding-bottom-5">
                <?= $this->formSelect($form->get('creator_id')) ?>
            </div>

            <div class="col-sm-3 padding-bottom-5">
                <div class="input-group">
                    <?= $this->formInput($form->get('item-search-creation-date')) ?>
                    <div class="input-group-addon">
                        <i class="glyphicon glyphicon-calendar"></i>
                    </div>
                </div>
            </div>

            <div class="col-sm-3 padding-bottom-5">
                <div class="input-group">
                    <?= $this->formInput($form->get('item-search-period')) ?>
                    <div class="input-group-addon">
                        <i class="glyphicon glyphicon-calendar"></i>
                    </div>
                </div>
            </div>

            <div class="col-sm-3 padding-bottom-5">
                <?= $this->formInput($form->get('item-search-amount')) ?>
            </div>


        </div>

        <div class="row">
            <div class="col-sm-2 margin-top-5">
                <a href="" class="btn btn-info btn-block download">
                    <span class="glyphicon glyphicon-download"></span>
                    Download
                </a>
            </div>
            <div class="col-sm-8 margin-top-5">
                <a href="javascript:void(0)" class="btn btn-medium btn-block btn-primary" id="btn-search-po-items"><i class="icon-search icon-white"></i> Search</a>
            </div>

            <div class="col-sm-2 margin-top-5">
                <a href="javascript:void(0)" class="btn btn-default btn-block filter-reset">Clear Filter</a>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>


<hr>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable-po-items" class="table table-striped table-bordered table-condensed table-hover hidden">
            <thead>
            <tr>
                <th> Created </th>
                <th> Period </th>
                <th> Supplier </th>
                <th> Reference </th>
                <th> Cost Centers </th>
                <th> Category </th>
                <th> Subcategory </th>
                <th> Amount </th>
                <th> &nbsp; </th>
                <th> <i class="glyphicon glyphicon-comment"></i> </th>
                <th> Type </th>
                <th> PO </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
