<?php
    $form        = $this->form;
    $actionTitle = ($this->id ? $form->get('name')->getValue() : 'Add Group');
    $receptionEntryTextlineId  = $this->receptionEntryTextlineId;

    $this->headTitle()->setSeparator(' - ');
    $this->headTitle($actionTitle . ' | Product Groups');
    $this->layout()->viewTitle = $actionTitle;
    $this->layout()->breadcrumb = $this->breadcrumb([
        ['Apartment'],
        ['Apartment Groups', $this->url('backoffice/default', ['controller' => 'apartment-group', 'action' => 'index'])],
        [$actionTitle]
    ]);

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/validation/apartment-group-building.js')
        ->appendFile($this->basePath() . '/js/pages/apartment-group-building.js');

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/pages/apartment.group.css');

    $form->prepare();
    $form->setAttribute('action', $this->url('backoffice/default', ['controller' => 'apartment-group', 'action' => 'ajaxsave']));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('id', 'form_apartment_group_building');
?>
<script>
    var GLOBAL_SAVE_DATA    = '<?= $this->url('backoffice/default', array('controller' => 'apartment-group-building', 'action' => 'ajaxsave'))?>';
    var GLOBAL_SAVE_SECTION = '<?= $this->url('backoffice/default', array('controller' => 'apartment-group-building', 'action' => 'ajax-save-section'))?>';
    var APARTMENT_GROUP_ID  = '<?= $this->id ?>';
</script>
<?php if ($this->id > 0) { ?>
       <div class="row">
        <div class="col-sm-12">
            <hr>
            <?= $this->apartmentGroupNavigation($this->id, 'apartment-group/building')?>
        </div>
    </div>
<?php } ?>
<?php echo $this->form()->openTag($form); ?>

<div id="building">
    <?php if($this->id && $this->global) {?>
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-5">
                    <fieldset class="form-horizontal">
                        <legend>General</legend>
                    </fieldset>
                    <div class="form-group">
                        <label class="col-sm-4 control-label pull-left" for="phone">Phone</label>
                        <div class="col-sm-7">
                            <?php echo $this->formInput($form->get('building_phone')); ?>
                        </div>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="row">
                        <div class="col-sm-12">
                            <fieldset class="form-horizontal">
                                <legend>Sections</legend>
                            </fieldset>
                            <table class="table table-striped table-bordered table-condensed">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Key Instructions</th>
                                    <th>Lock</th>
                                    <th>Lots</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                            <?php foreach ($this->sectionList as $key => $section) { ?>
                                <tr>
                                    <td><?= $section['name']?></td>
                                    <td>
                                        <?php if ($section['apartment_entry_textline_id']) { ?>
                                            <a href="<?= "/translation/view/p-" . $section['apartment_entry_textline_id'] . "-en"?>" target="_blank" id="apartment">Apartment Entry</a>
                                        <?php } else { ?>
                                            No KI
                                        <?php } ?>
                                    </td>
                                    <td><?= $section['lock_name']?></td>
                                    <td>
                                        <?php
                                        if ($section['lots_name']) {
                                            echo $section['lots_name'];
                                        }
                                        ?>
                                    </td>
                                    <td width="1" style="white-space: nowrap">
                                        <a href="javascript:void(0)" class="btn btn-primary margin-right-5 btn-xs edit-section"
                                           data-id="<?=$section['id']?>"
                                           data-name="<?=$section['name']?>"
                                           data-lock="<?=$section['lock_id']?>"
                                           data-lots="<?=$section['lots_id']?>"
                                            >Edit</a>
                                        <?php if (!$section['count_apartment'] && $key) { ?>
                                            <a href="javascript:void(0)" class="btn btn-danger btn-xs delete-item-section" data-id="<?=$section['id']?>">Delete</a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <fieldset id="div_facilities" class="form-horizontal">
                <legend>Guest Entry and Communication</legend>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="row textline-div">
                            <label class="col-xs-6 col-sm-4 control-label">Building Conduct</label>
                            <div class="col-xs-6 help-block">
                                <a href="/translation/view/p-<?= $this->groupUsage['id'] ?>-en" target="_blank" id="group_usage">Welcome note</a>
                            </div>
                        </div>
                        <div class="row textline-div">
                            <label class="col-xs-6 col-sm-4 control-label">Facilities (Building)</label>
                            <div class="col-xs-6 help-block">
                                <a href="/translation/view/p-<?= $this->groupFacility['id'] ?>-en" target="_blank" id="group_facility">Welcome note</a>
                            </div>
                        </div>
                        <div class="row textline-div">
                            <label class="col-xs-6 col-sm-4 control-label">Building policy</label>
                            <div class="col-xs-6 help-block">
                                <a href="/translation/view/p-<?= $this->groupPolicy['id'] ?>-en" target="_blank" id="group_policy">Welcome note</a>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('key_instruction_page_type')->getAttribute('id') ?>">
                                <?= $this->info($form->get('key_instruction_page_type')->getLabel(), 'If the policy requires the guests to visit the reception desk - choose Reception, otherwise - Direct.'); ?>
                            </label>
                            <div class="col-xs-6">
                                <?= $this->formSelect($form->get('key_instruction_page_type')) ?>
                            </div>
                        </div>
                        <div class="form-group location_part soft-hide">
                            <label class="col-xs-6 col-sm-4 control-label" for="<?= $form->get('assigned_office_id')->getAttribute('id') ?>">
                                <?= $this->info($form->get('assigned_office_id')->getLabel(), 'Choose office assigned to this apartment. It should be office which is represented as front desk for this apartment.') ?> <?php echo $this->required(); ?>
                            </label>
                            <div class="col-xs-6">
                                <?= $this->formSelect($form->get('assigned_office_id')) ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="col-xs-12 text-right">
                                <?= $this->formInput($form->get('map_attachment')) ?>
                                <input type="hidden" name="delete_attachment" id="delete_attachment" value="0">
                            </div>
                        </div>
                        <?php if($this->mapAttachment){?>
                            <div id="attachment-container" class="preview">
                                <button id="remove-attachment" value="<?=$this->url('apartment-group/building', ['action' => 'remove-map', 'id' => $this->id])?>" class="hidden-file-input"></button>
                                <img style="max-width: 100%; max-height: 350px" src="<?=$this->mapAttachment?>">
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="col-sm-12">
            <fieldset id="div_facilities" class="form-horizontal">
                <legend>Facilities</legend>
                <div class="row">
                <?php if($this->facilitiesList->count()) { ?>
                    <?php foreach($this->facilitiesList as $facility) { ?>
                    <label class="control-label col-sm-2 col-xs-6" for="facility_<?= $facility->getId(); ?>">
                        <?= $facility->getName() ?>
                    </label>
                    <div class="checkbox col-sm-1 col-xs-6">
                        <input type="hidden" name="facilities[<?= $facility->getId(); ?>]" value="0">
                        <input type="checkbox" name="facilities[<?= $facility->getId(); ?>]" id="facility_<?= $facility->getId(); ?>"<?php if(in_array($facility->getId(), $this->buildingFacilities)) {?> checked="checked"<?php } ?> value="1">
                    </div>
                    <?php } ?>
                <?php } ?>
                </div>
            </fieldset>
            <br />
        </div>
    <?php } ?>
</div>
<div class="page-actions container">
    <div class="row text-right">
        <?php
        if ($this->isActive) {
            echo $this->formButton($form->get('save_button'));
            ?>
            <a href="javascript:void(0)" class="btn btn-primary col-sm-2 col-xs-12 margin-left-10 pull-right add-new-section">Add Section</a>
        <?php } ?>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<?php if ($this->id) {?>
    <div id="section-dialog" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="section-dialog" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary text-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Section</h4>
                </div>
                <div class="modal-body">
                    <form id="section-form" name="section-form">
                        <div class="row margin-bottom-10">
                            <div class="col-sm-3 text-right">
                                <label class="form-control-static">Name <?php echo $this->required(); ?></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" name="section_name" class="form-control" id="section_name">
                            </div>
                        </div>
                        <div class="row margin-bottom-10">
                            <div class="col-sm-3 text-right">
                                <label class="form-control-static">Lock <?php echo $this->required(); ?></label>
                            </div>
                            <div class="col-sm-8">
                                <select name="lock" id="lock" class="form-control" placeholder="Lock">
                                    <?php foreach($this->lock as $key => $value){ ?>
                                        <option value="<?=$key?>"><?=$value?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="row margin-bottom-10">
                            <div class="col-sm-3 text-right">
                                <label class="form-control-static">Lots</label>
                            </div>
                            <div class="col-sm-8">
                                <select name="lots[]" id="lots" class="form-control selectize" multiple placeholder="Lots">
                                    <?php foreach($this->lots as $key => $value){ ?>
                                        <option value="<?=$key?>"><?=$value?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <input type="hidden" name="section_id" id="section_id">
                        <input type="hidden" name="building_id" value="<?=$this->id?>">
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                    <a href="javascript:void(0)" class="btn btn-primary save-section">Add Section</a>
                </div>
            </div>
        </div>
    </div>

    <div id="delete-dialog" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="delete-dialog" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger text-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title text-danger">Delete Section</h4>
                </div>
                <div class="modal-body">
                    Are you sure ?
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                    <a href="javascript:void(0)" class="btn btn-danger delete-section">Delete Section</a>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

