<?php
    $actionTitle = $this->apartmentGroupName;

    $this->headTitle()->setSeparator(' - ');
    $this->headTitle($actionTitle . ' | Product Groups');
    $this->layout()->viewTitle = $actionTitle;
    $this->layout()->breadcrumb = $this->breadcrumb([
        ['Apartment'],
        ['Apartment Groups', $this->url('backoffice/default', ['controller' => 'apartment-group', 'action' => 'index'])],
        [$actionTitle]
    ]);

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/apartment-group-contact.js');

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/pages/apartment.group.css');
?>

<script>
    var contactsData = <?= $contactsData ?>;
</script>
<div class="row">
    <div class="col-sm-12">
        <hr>
        <?= $this->apartmentGroupNavigation($this->id, 'apartment-group/contacts')?>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <table id="datatable-contacts" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <tr>
                <th> Contact Name </th>
                <th> Company </th>
                <th> Mobile </th>
                <th> Email </th>
                <th> &nbsp; </th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
