<?php
$environment = getenv('APPLICATION_ENV') ?: 'production';

echo "<script src='{$this->basePath()}/js/vendor/tinymce/tinymce.min.js' type='text/javascript'></script>";

?>

<script>
    var GLOBAL_SAVE       = '<?= $this->url('backoffice/default', array('controller' => 'news', 'action' => 'ajaxsave'))?>';
    var GLOBAL_DELETE     = '<?= $this->url('backoffice/default', array('controller' => 'news', 'action' => 'ajaxdelete'))?>';
</script>
<?php
	$newsTitle = $this->newsForm->get('title')->getValue();
    if (is_null($newsTitle)) {
        $newsTitle = 'Add News';
    }

    $this->headTitle()->setSeparator(' - ');
    $this->headTitle($newsTitle);
    $this->layout()->breadcrumb = '<li>Content</li>
                                   <li><a href="'.$this->url('backoffice/default', array('controller' => 'news', 'action' => 'index')).'">News</a></li>
                                   <li class="active">' . $newsTitle . '</li>';
    $this->layout()->viewTitle = $newsTitle;
    $this->InlineScript()
		->appendFile($this->basePath() . '/js/plugins/jquery.form.min.js')
		->appendFile($this->basePath() . '/js/pages/news.edit.js');

    $form = $this->newsForm;

    if (is_object($form)) {
	    $form->prepare();
	    $form->setAttribute('action', $this->url('backoffice/default', array('controller' => 'news', 'action' => 'edit')));
	    $form->setAttribute('method', 'post');
	    $form->setAttribute('class', 'form-horizontal');
	    $form->setAttribute('id', 'news_form');?>

<?php
    echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-md-12">
     <fieldset name="general">
        <legend>General</legend>
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label class="col-md-3 control-label" for="title">Title  <?php echo $this->required(); ?></label>
                    <div class="col-md-9 controls">
                        <?php
                            echo $this->formInput($form->get('title'));
                        ?>
                        <div class="help-block"></div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label class="col-sm-6 control-label" for="date">Date <?php echo $this->required(); ?></label>
                    <div class="col-sm-6">
                        <?=$this->formInput($form->get('date'))?>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label" for="body">Body <?php echo $this->required(); ?></label>
            <div class="col-md-10 controls">
                <?php
                    echo $this->formElement($form->get('body'));
                ?>
                <div class="help-block"></div>
            </div>
        </div>
    </fieldset>
    </div>
</div>
<div class="page-actions container">
    <div class="row text-right">
        <?php if ($this->edit > 0) { ?>
            <a href="<?=$this->urlSie?>" target="_blank" data-toggle="modal" class="btn btn-info pull-left col-sm-2 col-xs-12">View on Website</a>
        <?php } ?>
        <?php
            echo $this->formInput($form->get('edit_id'));
            echo $this->formButton($form->get('save_button'));
        ?>
        <?php if ($this->edit > 0) { ?>
            <a href="#deleteModal" data-toggle="modal" class="btn btn-danger col-sm-2 col-xs-12 margin-left-10 pull-right">Delete News</a>
        <?php } ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete News</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button class="btn btn-danger" id="delete_button">Delete</button>
            </div>
        </div>
    </div>
</div>
<?php } else { ?>
<div style="font-size: 20px;text-align: center;height: 600px;">Aweee, </div>
<?php } ?>
