<?php

$this->InlineScript()
    ->appendFile( $this->basePath() . '/js/plugins/jquery.form.min.js' )
    ->appendFile($this->basePath() . '/js/pages/moneyaccounts.document.js');

$environment = getenv('APPLICATION_ENV') ?: 'production';
echo "<script src='{$this->basePath()}/js/vendor/tinymce/tinymce.min.js' type='text/javascript'></script>";

?>

<script>
    $(function() {
        tinymce.init({
            selector: ".tinymce",
            skin: "clean",
            plugins: [
                "code", "autoresize", "link"
            ],
            menu : {},
            toolbar: "undo redo | styleselect | bold italic underline |  aligncenter alignjustify alignleft alignright | bullist numlist outdent indent | link | print | fontsizeselect | code | removeformat",
            browser_spellcheck : true,
            autoresize_min_height:280,
            extended_valid_elements : "i[*]",
            verify_html : false
        });

    });

    var GLOBAL_UPLOAD_FILES     = '<?= $this->url('finance/default', ['controller' => 'money-account', 'action' => 'ajax-upload-files'])?>';
    var GLOBAL_DELETE_ATACHMENT = '<?= $this->url('finance/default', ['controller' => 'money-account', 'action' => 'ajax-delete-attachment'])?>';
</script>

<div class="row">
    <div class="col-sm-12">
        <fieldset>
            <legend>
                Description
                <?= $this->required(); ?>
            </legend>
            <div class="form-group">
                <div class="col-sm-12">
                    <?= $this->formElement($form->get('doc_description')); ?>
                    <?= $this->formElement($form->get('delete_data')); ?>
                    <?= $this->formElement($form->get('money_account_id')); ?>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>
                Attachment
            </legend>
            <div class="form-group">
                <div class="col-sm-12 base">
                    <?=$this->formElement($form->get('uploaded_files'))?>
                    <input type="hidden" name="validAttachment" id="validAttachment" value="0" />
                </div>
                <div id="reservoir"></div>
                <div class='col-sm-12'>
                    <div class='col-sm-6'>
                        <ul class="attach_files list-group">
                        </ul>
                    </div>
                </div>
            </div>
            <a href="javascript:void(0)" class="btn btn-success uploadAttachment"  id="uploadAttachment"><span class="glyphicon glyphicon-upload"></span>&nbsp;Select File</a>
            <a href="javascript:void(0)" class="btn btn-danger uploadAttachment"  id="deleteFiles"> Delete All Files</a>
            <a href="javascript:void(0)" class="btn btn-primary pull-right margin-left-5 saveNewAttachBtn" style="" id="saveNewAttachBtn">Upload</a>
            <a href="javascript:void(0)" class="btn btn-default pull-right margin-left-5 cancelAttachBtn" style="" id="cancelAttachBtn">Cancel</a>
        </fieldset>
    </div>
</div>
