<?php
use DDD\Service\MoneyAccount as MoneyAccountService;

$this->layout()->viewTitle = 'Money Account Management';
$this->layout()->breadcrumb = $this->breadcrumb([
	['Finance'],
	[$this->layout()->viewTitle]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->InlineScript()
	->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
	->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/pages/moneyaccount.management.js');

$this->headLink()
	->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

?>

<div id="status-switch" xmlns="http://www.w3.org/1999/html">
    <div class="btn-group fn-buttons pull-right">
        <a href="#all" class="btn btn-sm btn-default" data-status="all">All</a>
        <a href="#active" class="btn btn-sm btn-default active" data-status="active">Active</a>
        <a href="#inactive" class="btn btn-sm btn-default" data-status="inactive">Inactive</a>
    </div>
    <input type="hidden" name="show_status" id="show-status" value="1">
</div>

<div class="datatables-container">
    <table id="bank-accounts-table" class="table table-striped table-bordered table-condensed table-hover">
        <thead>
        <tr>
            <th>ST</th>
            <th>Money Accounts</th>
            <th>Type</th>
            <th><div class="text-left">Balance</div></th>
            <th>Currency</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<?php if ($this->bankAccountCreator) { ?>
<div class="page-actions container">
	<div class="row text-right">
		<a href="<?php echo $this->url('finance/default', ['controller' => 'money-account', 'action' => 'edit']); ?>" class="btn btn-primary state col-sm-2 col-xs-12 pull-right">Add Money Account</a>
	</div>
</div>
<?php } ?>
