<?php
    use DDD\Service\Venue\Venue as VenueService;
    if ($this->venueId > 0) {
        $subject = $this->venue->getName();
        $breadcrumbTitle = 'Edit Venue';
    } else {
        $subject = $breadcrumbTitle = 'Add Venue';
    }

    $data = $this->data;
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Edit Venue');
    $this->layout()->breadcrumb = '<li>Administration</li>
                                   <li><a href="'.$this->url('venue', array('controller' => 'venue')).'">Venue Management</a></li>
                                   <li class="active">'. $breadcrumbTitle .'</li>';

    $this->InlineScript()
        ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
        ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
        ->appendFile($this->basePath() . '/js/pages/venue.edit.js');

    $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/pages/venue.edit.css');
?>

<script>
    var GLOBAL_VENUE_ID      = <?= $this->venueId ?>;
    var GENERAL_SAVE_VENUE   = '<?=$this->url('venue', ['action' => 'ajaxSave']) ?>';
    var GENERAL_DELETE_VENUE = '<?=$this->url('venue', ['action' => 'delete']) ?>';
    var GLOBAL_VENUE_CHARGE_GET_SUPPLIERS_URI = '<?=$this->url('venue', ['action' => 'ajax-get-suppliers']) ?>';
    var CHARGES_DATA         = <?=$this->chargesData?>;
    var GLOBAL_IS_VENUE_MANAGER     = <?= ($this->isVenueManager) ? 'true' : 'false' ?>;
    var GLOBAL_IS_CHARGE_MANAGER    = <?= ($this->isChargeManager)  ? 'true' : 'false' ?>;
    var GLOBAL_SAVE_ITEMS           = '<?= $this->url('venue-items', ['action' => 'ajax-save']); ?>';
</script>

<div class="row">
    <div class="col-sm-12 main-title">
        <h1>
            <?=$subject?>
        </h1>
    </div>
</div>

<?php if ($this->venueId > 0) { ?>

<div class="row">
    <div class="col-sm-12 mobile-text-center margin-bottom-15">
        <span class="label label-primary margin-right-5">Currency: <?=$this->venue->getCurrencyCode()?></span>
    </div>
</div>

<ul class="nav nav-tabs tabs-general">
    <li class="active">
        <a href="#general" data-toggle="tab" aria-expanded="true" id="general-tab">General</a>
    </li>
    <li>
        <a href="#charges" data-toggle="tab" aria-expanded="true" id="charges-tab">Charges</a>
    </li>
    <li>
        <a href="#items" data-toggle="tab" aria-expanded="true" id="items-tab">Items</a>
    </li>
</ul>

<div class="tab-content">

    <div class="tab-pane fade active in" id="general">
<?php } ?>

        <!-- Form opening tag -->
        <?php echo $this->form()->openTag($this->form); ?>

        <!-- First Row -->
        <div class="row">
            <div class="col-md-12">
                <fieldset>
                    <legend>General</legend>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="name">
                                    <?= $this->form->get('name')->getOption('label') . ' ' . $this->required() ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= $this->formInput($this->form->get('name'));?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="cityId">
                                    <?= $this->form->get('cityId')->getOption('label') . ' ' . $this->required() ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= $this->formSelect($this->form->get('cityId'));?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="account_id">
                                    <?= $this->form->get('account_id')->getOption('label') . ' ' . $this->required() ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= $this->formSelect($this->form->get('account_id')->setAttributes([
                                        'data-unique-id' => $this->venue ? $this->venue->getUniqueId() : '',
                                        'data-account-id' => $this->venue ? $this->venue->getAccountId() : '',
                                        'data-account-name' => $this->venue ? $this->venue->getAccountName() : '',
                                        'data-account-type' => $this->venue ? $this->venue->getAccountType() : '',
                                    ]))?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="managerId">
                                    <?= $this->form->get('managerId')->getOption('label') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= $this->formSelect($this->form->get('managerId')->setAttributes([
                                        'data-id' => $this->venue ? $this->venue->getManagerId() : ''
                                    ]));?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="cashierId">
                                    <?= $this->form->get('cashierId')->getOption('label') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= $this->formSelect($this->form->get('cashierId')->setAttributes([
                                        'data-id' => $this->venue ? $this->venue->getCashierId() : ''
                                    ]));?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="acceptOrders">
                                    <?= $this->form->get('acceptOrders')->getOption('label') ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= $this->formSelect($this->form->get('acceptOrders')->setAttributes([
                                        'data-id' => $this->venue ? $this->venue->getAcceptOrders() : ''
                                    ]));?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="currencyId">
                                    <?= $this->form->get('currencyId')->getOption('label') . ' ' . $this->required() ?>
                                </label>
                                <div class="col-sm-8">
                                    <?= $this->formSelect($this->form->get('currencyId'));?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="thresholdPrice">
                                    <?= $this->form->get('thresholdPrice')->getOption('label') ?>
                                </label>
                                <div class="col-sm-8">
                                    <div class="input-group">
                                        <?= $this->formInput($this->form->get('thresholdPrice'));?>
                                        <span class="input-group-addon"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="discountPrice">
                                    <?= $this->form->get('discountPrice')->getOption('label') ?>
                                </label>
                                <div class="col-sm-8">
                                    <div class="input-group">
                                        <?= $this->formInput($this->form->get('discountPrice'));?>
                                        <span class="input-group-addon"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="perdayMinPrice">
                                    <?= $this->form->get('perdayMinPrice')->getOption('label') ?>
                                </label>
                                <div class="col-sm-8">
                                    <div class="input-group">
                                        <?= $this->formInput($this->form->get('perdayMinPrice'));?>
                                        <span class="input-group-addon"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="perdayMaxPrice">
                                    <?= $this->form->get('perdayMaxPrice')->getOption('label') ?>
                                </label>
                                <div class="col-sm-8">
                                    <div class="input-group">
                                        <?= $this->formInput($this->form->get('perdayMaxPrice'));?>
                                        <span class="input-group-addon"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="type">
                                    <?php $requiredAsterisk = (!$venueId) ? $this->required() : ''; ?>
                                    <?= $this->form->get('type')->getOption('label') . ' ' . $requiredAsterisk ?>
                                </label>
                                <div class="col-sm-8">
                                    <?php if (!$venueId) {
                                        echo $this->formSelect($this->form->get('type'));
                                    } else { ?>
                                        <span class="label label-primary type-label"><?php echo VenueService::getVenueTypesForSelect()[$this->form->get('type')->getValue()];?></span>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                        </div>

                </fieldset>
            </div>
        </div>

        <?php if ($this->isVenueManager) { ?>
        <div class="col-sm-12">
            <div class="page-actions container hidden-print">
                <div class="row">
                    <div class="col-xs-12">
                        <?= $this->formInput($this->form->get('id'));?>
                        <?= $this->formInput($this->form->get('status'));?>
                        <?php if ($this->venueId > 0) : ?>
                            <a href="javascript:void(0)" class="btn btn-danger pull-left"  data-toggle="modal" data-target="#delete_venue">Deactivate</a>
                        <?php endif; ?>
                        <a href="javascript:void(0)" class="btn btn-primary pull-right margin-left-10" id="save_data">Save Changes</a>
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>

        <!-- Form close tag -->
        <?= $this->form()->closeTag(); ?>
    </div>

<?php if ($this->venueId > 0) { ?>
    <div class="tab-pane fade" id="charges">
        <div class="row">
            <div class="col-sm-12">
                <table id="datatable_charges" class="table table-bordered table-condensed table-hover">
                    <thead>
                    <tr>
                        <th> Payment </th>
                        <th> Order </th>
                        <th> Created </th>
                        <th> Charged </th>
                        <th> Description </th>
                        <th> Amount </th>
                        <th> </th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <div class="alert alert-success" id="charges_clean">
                    <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    There are no items to display
                </div>
            </div>

            <?php if ($this->isVenueManager || $this->isChargeManager) { ?>
            <div class="col-sm-12">
                <div class="page-actions container">
                    <div class="row">
                        <div class="col-xs-12">
                            <a target="new"
                               href="<?php echo $this->url('venue-charges', ['action' => 'add', 'id' => $this->venueId]); ?>"
                               class="btn btn-primary pull-right margin-left-10" id="add_charge">Add Charge</a>
                        </div>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>

<?php if ($this->venueId > 0) { ?>
    <div class="tab-pane fade" id="items">

        <div class="row">

            <form method="post" name="venue-items-form" class="form-horizontal" id="venue-items-add-form">
                <div class="col-sm-12 margin-bottom-15">
                    <table class="table table-striped table-bordered table-condensed" id="items_table_for_add">
                        <tbody>
                            <tr>
                                <td class="venue-item-title">
                                    <?= $this->formInput($itemsForm->get('titles[]')) ?>
                                </td>
                                <td class="venue-item-description">
                                    <?= $this->formInput($itemsForm->get('descriptions[]')) ?>
                                </td>
                                <td class="venue-item-price">
                                    <?= $this->formInput($itemsForm->get('prices[]')) ?>
                                </td>
                                <td class="venue-item-availability">
                                    <?= $this->formSelect($itemsForm->get('availabilities[]')) ?>
                                </td>
                                <td class="text-center venue-item-edit-column">
                                    <a href="javascript:void(0)" class="btn btn-sm btn-primary" id="add-item">Add</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </form>

            <?php echo $this->form()->openTag($this->itemsForm); ?>

            <input type="hidden" name="venue_id" value="<?=$this->venueId?>">

            <div class="col-sm-12">
                <fieldset name="items">

                    <table class="table table-striped table-bordered table-condensed" id="items_table">
                        <thead>
                            <tr>
                                <th class="venue-item-title"> Name </th>
                                <th class="venue-item-description"> Description </th>
                                <th class="venue-item-price"> Price </th>
                                <th class="venue-item-availability"> Availability </th>
                                <th class="venue-item-edit-column"></th>
                            </tr>
                        </thead>
                        <tbody id="items-list">
                        <?php if (($this->venueItems) && $this->venueItems->count()) { ?>
                            <?php foreach ($this->venueItems as $key => $venueItem) { ?>
                                <tr class="item_tr">
                                    <td>
                                        <div class="input-prepend input-append form-group margin-0">
                                            <div class="col-sm-12">
                                                <input name="titles[]" type="text" class="form-control venue-item-title" value="<?=$venueItem->getTitle() ?>">
                                            </div>
                                        </div>
                                    </td>

                                    <td>
                                        <div class="input-prepend input-append form-group margin-0">
                                            <div class="col-sm-12">
                                                <input name="descriptions[]" type="text" class="form-control venue-item-description" value="<?=$venueItem->getDescription() ?>">
                                            </div>
                                        </div>
                                    </td>

                                    <td>
                                        <div class="input-prepend input-append form-group margin-0">
                                            <div class="col-sm-12">
                                                <input name="prices[]" type="text" class="form-control venue-item-price" value="<?=$venueItem->getPrice() ?>">
                                            </div>
                                        </div>
                                    </td>

                                    <td>
                                        <?php
                                        $selectAvailable    = 'selected';
                                        $selectNotAvailable = '';

                                        if ($venueItem->getIsAvailable() == \DDD\Service\Venue\Items::STATUS_NOT_AVAILABLE) {
                                            $selectAvailable    = '';
                                            $selectNotAvailable = 'selected';
                                        }
                                        ?>
                                        <div class="input-prepend input-append form-group margin-0">
                                            <div class="col-sm-12">
                                                <select name="availabilities[]" class="form-control venue-item-availability has-success" id="availability_0" value="1" data-id="" aria-invalid="false">
                                                    <option value="1" <?=$selectAvailable?>>Available</option>
                                                    <option value="2" <?=$selectNotAvailable?>>Not Available</option>
                                                </select>
                                            </div>
                                        </div>
                                    </td>

                                    <td>
                                        <a href="javascript:void(0)" id="venue_item_<?=$venueItem->getId()?>" class="btn btn-sm btn-danger btn-block itemRemoveRow" data-id="<?=$venueItem->getId()?>">
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                            <?php }
                        } ?>
                        </tbody>
                    </table>
                </fieldset>
            </div>

            <?php if ($this->isVenueManager || $this->isChargeManager) { ?>
            <div class="col-sm-12">
                <div class="page-actions container">
                    <div class="row">
                        <div class="col-xs-12">
                            <a class="btn btn-primary pull-right margin-left-10" id="save_items">Save Changes</a>
                        </div>
                    </div>
                </div>
            </div>
            <?php } ?>

        </div>

        <?=$this->form()->closeTag(); ?>
    </div>

</div>
<?php } ?>

<?php if ($this->venueId > 0 && $this->isVenueManager) { ?>
<!-- Delete Modal -->
<div class="modal fade" id="delete_venue" tabindex="-1" role="dialog" aria-labelledby="delete_venue">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger text-danger">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Deactivate Venue</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to deactivate this venue ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <a href="<?= $this->url('venue', ['action' => 'delete', 'id' => $venueId]) ?>" class="btn btn-danger">Yes, Deactivate</a>
            </div>
        </div>
    </div>
</div>
<?php } ?>