<?php
    $this->layout()->viewTitle = 'Venue Management';
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle($this->layout()->viewTitle);
    $this->layout()->breadcrumb = $this->breadcrumb([
        ['Administration'],
        [$this->layout()->viewTitle]
    ]);

    $this->InlineScript()
         ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
         ->appendFile($this->basePath() . '/js/plugins/fnReloadAjax.js')
         ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
         ->appendFile($this->basePath() . '/js/pages/venue.js');

    $this->headLink()
         ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');
?>

<script>
    var DATATABLE_AJAX_SOURCE   = '<?= $ajaxSourceUrl ?>';
    var GLOBAL_IS_VENUE_MANAGER = <?= ($this->isVenueManager) ? 'true' : 'false' ?>
</script>

<!-- Form opening tag -->
<?php echo $this->form()->openTag($this->searchForm); ?>

<!-- First Row -->
<div class="row">
    <!-- Cities -->
    <div class="col-sm-4">
        <div class="form-group">
            <?= $this->formSelect($this->searchForm->get('cityId')); ?>
        </div>
    </div>
    <!-- Manager -->
    <div class="col-sm-4">
        <div class="form-group">
            <?= $this->formSelect($this->searchForm->get('managerId')); ?>
        </div>
    </div>
    <!-- Cashier -->
    <div class="col-sm-4">
        <div class="form-group">
            <?= $this->formSelect($this->searchForm->get('cashierId')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <a href="javascript:void(0)" class="btn btn-block btn-primary" id="btn_search_venue"><span class="glyphicon glyphicon-search"></span> Search</a>
        </div>
    </div>
</div>

<!-- Form close tag -->
<?= $this->form()->closeTag(); ?>

<div class="row hidden" id="datatable_venue_container">
    <div class="col-sm-12">
        <table id="datatable_venue_info" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
                <tr>
                    <th> Accept Orders </th>
                    <th> Name </th>
                    <th> City </th>
                    <th> Manager </th>
                    <th> Cashier </th>
                    <th>  </th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

<?php if ($this->isVenueManager) { ?>
<div class="col-sm-12">
    <div class="page-actions container hidden-print">
        <div class="row">
            <div class="col-xs-12">
                <a href="<?= $this->url('venue', ['action' => 'edit']) ?>" class="btn btn-primary pull-right margin-left-10">Add New Venue</a>
            </div>
        </div>
    </div>
</div>
<?php } ?>
