<?php

use Library\Constants\DomainConstants;
use FileManager\Constant\DirectoryStructure;

$this->headTitle($this->apartelName . ' | Apartel')->setSeparator(' - ');

$layoutViewModel = $this->viewModel()->getRoot();

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/apartel/common.css')
    ->appendStylesheet($this->basePath() . '/css/apartel/general.css');

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.form.min.js')
    ->appendFile($this->basePath() . '/js/apartel/content.js');


$apartelId = $layoutViewModel->apartelId;
echo "<script src='{$this->basePath()}/js/vendor/tinymce/tinymce.min.js' type='text/javascript'></script>";
?>
<script>
    var GLOBAL_IMAGE_PATH = '<?php
        $bgImagePath = 'https://' . DomainConstants::IMG_DOMAIN_NAME . '/'
            . DirectoryStructure::FS_IMAGES_APARTEL_BG_IMAGE
            . $this->apartelId . '/';
        echo $bgImagePath;
        ?>';
    var GLOBAL_GENERAL_SAVE_PATH = '/apartel/' + <?php echo $this->apartelId; ?> + '/content/save';
</script>

<?php echo $this->apartelHeader($apartelId); ?>

<?php
echo $this->form()->openTag($form);
echo $this->formInput($form->get('id'));
?>

<div class="row">
    <div class="col-sm-6">
        <fieldset>
            <legend>Background Image</legend>

            <?php
            if (!empty($this->bgImage)) {
                $bgImage = $bgImagePath . $this->bgImage;
                $bgImageCssHeight = '200px';
            } else {
                $bgImage = '';
                $bgImageCssHeight = '0px';
            }
            ?>
            <div class="col-xs-12 margin-bottom-10" id="bg-image"
                 style="background: url(<?php echo $bgImage; ?>) 0% 0% no-repeat; background-size: cover; height: <?php echo $bgImageCssHeight; ?>;">
            </div>

            <div class="row form-group">
                <div class="col-xs-9">
                    <?php
                        echo $this->formElement($form->get('bg_image'));
                        echo $this->formHidden($form->get('bg_image_file_name'));
                    ?>
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>Moto</legend>

            <div class="row form-group">
                <div class="col-xs-12">
                    <?php echo $this->formTextarea($form->get('moto_textline')); ?>
                </div>
            </div>
        </fieldset>

        <fieldset>
            <legend>Meta Description</legend>

            <div class="row form-group">
                <div class="col-xs-12">
                    <?php echo $this->formTextarea($form->get('meta_description_textline')); ?>
                </div>
            </div>
        </fieldset>
    </div>

    <div class="col-sm-6">
        <fieldset>
            <legend>Content</legend>

            <div class="row form-group">
                <div class="col-xs-12">
                    <?php echo $this->formTextarea($form->get('content_textline')); ?>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <?= $this->formInput($form->get('save_button')) ?>
    </div>
</div>

<?php echo  $this->form()->closeTag(); ?>
