<?php
use DDD\Service\Finance\Budget;

$current = $this->id ? 'Edit Budget' : 'Add Budget';
$this->layout()->viewTitle = $current;
$this->layout()->breadcrumb = $this->breadcrumb([
	['Administration'],
	['Budget Management', $this->url('finance/budget', ['controller' => 'budget'])],
	[$current]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css')
    ->appendStylesheet($this->basePath() . '/css/finance/budget.css');

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/pages/budget.edit.js');

$budgetData = $this->budgetData;
?>
<?php if ($budgetData) { ?>
    <div class="row">
        <div class="col-sm-12">
            <div class="balance-container text-right">
                <div class="balance">Balance <span class="balance-amount"><?= $budgetData['balance']; ?></span> <span class="text-primary font-size18"><?= Budget::BUDGET_CURRENCY ?></span></div>
            </div>
        </div>
    </div>
<?php } ?>
<?php echo $this->form()->openTag($this->form); ?>
<div class="row">
    <div class="col-sm-6">
        <fieldset name="General">
            <legend>General</legend>
            <div class="form-group">
                <label for="name" class="col-sm-3 control-label">Name <?php echo $this->required(); ?></label>
                <div class="col-sm-9">
                    <?= $this->formInput($form->get('name')) ?>
                </div>
            </div>
            <div class="form-group">
                <label for="status" class="col-sm-3 control-label">Status <?php echo $this->required(); ?></label>
                <div class="col-sm-9">
                    <?php echo $this->formSelect($form->get('status')); ?>
                </div>
            </div>
			<div class="form-group">
				<label class="col-sm-3 control-label" for="department_id">Department <?php echo $this->required(); ?></label>
				<div class="col-sm-9">
					<?=$this->formElement($form->get('department_id'))?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label" for="country_id">Country</label>
				<div class="col-sm-9">
					<?=$this->formElement($form->get('country_id'))?>
				</div>
			</div>
            <div class="form-group">
                <label for="period" class="col-sm-3 control-label">Period <?php echo $this->required(); ?></label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <?= $this->formInput($form->get('period')) ?>
                        <label class="input-group-addon" for="interval">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="amount" class="col-sm-3 control-label">Amount <?php echo $this->required(); ?></label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <?= $this->formInput($form->get('amount')) ?>
                        <label class="input-group-addon" for="interval"><?=Budget::BUDGET_CURRENCY?></label>
                    </div>
                </div>
            </div>
			<div class="form-group">
				<label class="col-sm-3 control-label" for="is_global">
					<?= $this->info('Global', 'Global budgets are being used for the needs of the whole company, but still have departments responsible for them.'); ?>
				</label>
				<div class="col-sm-9">
					<div class="checkbox">
						<?= $this->formElement($form->get('is_global')); ?>
					</div>
				</div>
			</div>
            <div class="form-group">
                <label for="description" class="col-sm-3 control-label">Description <?php echo $this->required(); ?></label>
                <div class="col-sm-9">
                    <?= $this->formElement($form->get('description')) ?>
                </div>
            </div>
        </fieldset>
    </div>
    <?php if ($this->id != 0
        &&
        $this->id != Budget::BUDGET_NULL_ID
        &&
        $posAttachedToThisBudget
        &&
        $posAttachedToThisBudget->count()
    ) { ?>
    <div class="col-sm-6">
        <fieldset name="General">
            <legend>Purchase orders</legend>
            <table class="table table-striped table-bordered table-condensed table-hover">
                <thead>
                <tr>
                    <th> Purchase order </th>
                    <th> Limit </th>
                    <th> &nbsp; </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($posAttachedToThisBudget as $poAttachedToThisBudget) { ?>
                    <tr>
                        <td><?php echo $poAttachedToThisBudget['title'];?></td>
                        <td><?php echo $poAttachedToThisBudget['limit'] . ' ' . $poAttachedToThisBudget['currency'];?></td>
                        <td width="1"><a class="btn btn-xs btn-primary" target="_blank" href="/finance/purchase-order/ticket/<?php echo $poAttachedToThisBudget['id'];?>">View</a></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </fieldset>
    </div>
    <?php } ?>

</div>
 <div class="page-actions container">
    <div class="row text-right">
        <?= $this->formInput($form->get('save')) ?>
        <?php if ($this->id) {?>
            <?php if (!$this->frozen) {?>
                <a href="#modal_frozen" data-toggle="modal" class="btn btn-danger col-sm-2 col-xs-12 margin-left-10 pull-right">Freeze</a>
                <?php } else { ?>
                <a href="#modal_unfrozen" data-toggle="modal" class="btn btn-success col-sm-2 col-xs-12 margin-left-10 pull-right">Unfreeze</a>
            <?php } ?>

            <?php if (!$this->archived) {?>
                <a href="#modal_archive" data-toggle="modal" class="btn btn-danger col-sm-2 col-xs-12 margin-left-10 pull-right">Archive</a>
            <?php } else { ?>
                <a href="#modal_unarchive" data-toggle="modal" class="btn btn-success col-sm-2 col-xs-12 margin-left-10 pull-right">Unarchive</a>
            <?php } ?>

        <?php } ?>
    </div>
</div>
<?=$this->form()->closeTag(); ?>
<?php if ($this->id) {?>
    <div class="modal fade" id="modal_frozen" tabindex="-1" role="dialog" aria-labelledby="deactivate" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger text-danger">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">
                        Freeze <span id="deactivate_group"></span>
                    </h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to freeze this budget?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">Close</button>
                    <a class="btn btn-danger" href="/finance/budget/frozen/<?=$this->id?>/<?=Budget::BUDGET_FROZEN?>">Freeze</a>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal_unfrozen" tabindex="-1" role="dialog" aria-labelledby="activate" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-success text-success">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">
                        Unfreeze <span id="deactivate_group"></span>
                    </h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to unfreeze this budget?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">Close</button>
                    <a class="btn btn-success" href="/finance/budget/frozen/<?=$this->id?>/<?=Budget::BUDGET_UNFROZEN?>">Unfreeze</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal_archive" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger text-danger">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">
                        Archive <span id="deactivate_group"></span>
                    </h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to archive this budget?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">Close</button>
                    <a class="btn btn-danger" href="/finance/budget/archive/<?=$this->id?>/<?=Budget::BUDGET_ARCHIVED?>">Archive</a>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal_unarchive" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-success text-success">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">
                        Unarchive <span id="deactivate_group"></span>
                    </h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to unarchive this budget?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">Close</button>
                    <a class="btn btn-success" href="/finance/budget/archive/<?=$this->id?>/<?=Budget::BUDGET_UNARCHIVED?>">Unarchive</a>
                </div>
            </div>
        </div>
    </div>
    <script>
        var DISABLE_FORM = '<?=$this->disableForm?>';
    </script>
<?php } ?>
