<?php

$this->layout()->viewTitle = 'Budget Management';
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Administration'],
    [$this->layout()->viewTitle]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css')
    ->appendStylesheet($this->basePath() . '/css/plugins/selectize.bootstrap3.css');

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/plugins/selectize/selectize.min.js')
    ->appendFile($this->basePath() . '/js/pages/budget.js');
?>
<?php echo $this->form()->openTag($this->form); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="col-sm-3">
                <?= $this->formInput($form->get('name')) ?>
            </div>
            <div class="col-sm-3">
                <?= $this->formSelect($form->get('status')) ?>
            </div>
            <div class="col-sm-3">
                <?= $this->formSelect($form->get('country')) ?>
            </div>
            <div class="col-sm-3">
                <?= $this->formSelect($form->get('user')) ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="col-sm-3">
                <div class="input-group">
                    <label class="input-group-addon" for="interval">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </label>
                    <?= $this->formInput($form->get('period')) ?>
                </div>
            </div>
            <div class="col-sm-2">
                <?= $this->formSelect($form->get('frozen')) ?>
            </div>
            <div class="col-sm-2">
                <?= $this->formSelect($form->get('archived')) ?>
            </div>
            <div class="col-sm-3">
                <?= $this->formSelect($form->get('department')) ?>
            </div>
            <div class="col-sm-2">
                <?= $this->formSelect($form->get('global')) ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="col-sm-10">
                <a href="javascript:void(0)" class="btn btn-primary btn-block search" data-url="<?=$this->url('finance/budget/get-datatable');?>">
                    <i class="glyphicon glyphicon-search"></i> Search
                </a>
            </div>
            <div class="col-sm-2">
                <a href="#clear" class="btn btn-default btn-block clearForm">Clear Filter</a>
            </div>
        </div>
    </div>
</div>

<?=$this->form()->closeTag(); ?>

<hr>

<div class="row hidden dt-data">
    <div class="col-sm-12">

        <table id="budget-management-table" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
                <tr>
                    <th> Status </th>
                    <th> Name </th>
                    <th> Department </th>
                    <th> Period </th>
                    <th> Amount </th>
                    <th> Balance </th>
                    <th> Created by </th>
                    <th> &nbsp; </th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

    </div>
</div>

<div class="page-actions container">
    <div class="row text-right">
        <a href="<?= $this->url('finance/budget/edit', ['controller' => 'budget', 'action' => 'edit']); ?>" class="btn btn-primary state col-sm-2 col-xs-12 pull-right">Add New Budget</a>
    </div>
</div>
