<?php

$this->layout()->viewTitle = 'ESPM Management';
$this->layout()->breadcrumb = $this->breadcrumb([
    ['Finance'],
    [$this->layout()->viewTitle]
]);

$this->headTitle()->setSeparator(' - ');
$this->headTitle($this->layout()->viewTitle);

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/datatable/datatables.bootstrap.css');

$this->InlineScript()
    ->appendFile($this->basePath() . '/js/plugins/jquery.dataTables.min.js')
    ->appendFile($this->basePath() . '/js/DT_bootstrap.js')
    ->appendFile($this->basePath() . '/js/plugins/selectize/selectize.min.js')
    ->appendFile($this->basePath() . '/js/module/finance/espm.js');
?>
<form method="post" name="espm-form" class="form-horizontal" id="espm-form">
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <div class="col-sm-8">
                    <input name="reason" id="reason" type="text" class="form-control" maxlength="500" placeholder="Reason">
                </div>
                <div class="col-sm-2">
                    <input name="amount" id="amount" type="text" class="form-control" maxlength="12" placeholder="Amount">
                </div>
                <div class="col-sm-2">
                    <div class="archive-status">
                        <div class="btn-group fn-buttons pull-right">
                            <a href="#all" class="btn btn-sm btn-default" data-status="all">All</a>
                            <a href="#normal" class="btn btn-sm btn-default active" data-status="normal">Normal</a>
                            <a href="#Archived" class="btn btn-sm btn-default" data-status="archived">Archived</a>
                        </div>
                        <input type="hidden" name="is_archived" id="is_archived" class="is-archived" value="0" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">

                <div class="col-sm-3">
                    <select name="transaction_account" id="transaction_account" class="form-control selectized" data-placeholder="Supplier"></select>
                </div>
                <div class="col-sm-3">
                    <select name="account" id="account" class="form-control selectized" data-placeholder="Account"></select>
                </div>
                <div class="col-sm-3">
                    <select name="type" id="type" class="form-control selectized" data-placeholder="Type">
                        <?php foreach ($this->types as $key => $type) {?>
                            <option value="<?= $key?>"><?= $type ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="col-sm-3">
                    <select name="status" id="status" class="form-control selectized" data-placeholder="Status">
                        <?php foreach ($this->statuses as $key => $status) {?>
                            <option value="<?= $key?>"><?= $status ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <div class="col-sm-10">
                    <a href="javascript:void(0)" class="btn btn-primary btn-block search" data-url="<?=$this->url('finance/espm/get-datatable');?>">
                        <i class="glyphicon glyphicon-search"></i> Search
                    </a>
                </div>
                <div class="col-sm-2">
                    <a href="#clear" class="btn btn-default btn-block clearForm">Clear Filter</a>
                </div>
            </div>
        </div>
    </div>
</form>

<hr>

<div class="row hidden dt-data">
    <div class="col-sm-12">

        <table id="espm-management-table" class="table table-striped table-bordered table-condensed table-hover">
            <thead>
                <tr>
                    <th> Status </th>
                    <th> Type </th>
                    <th> Supplier </th>
                    <th> Account </th>
                    <th> Amount </th>
                    <th> Created by </th>
                    <th> &nbsp; </th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

    </div>
</div>
<?php if ($this->hasCreatorRole) {?>
<div class="page-actions container">
    <div class="row text-right">
        <a href="<?= $this->url('finance/espm/edit', ['controller' => 'budget', 'action' => 'edit']); ?>" class="btn btn-primary state col-sm-2 col-xs-12 pull-right">Add Payment</a>
    </div>
</div>
<?php } ?>
<script>
    var SUPPLIER_URL = '<?= $this->url('finance/purchase-order/get-accounts'); ?>';
    var GET_SUPPLIER_ACCOUNT = '<?= $this->url('finance/espm/get-supplier-account'); ?>';
</script>
